from __future__ import annotations

from cdmw.ui.archive_browser.static_replacement_shared_context import (
    shared_context_container,
)

def _remaining_source_material_plan_refresh_step_001(_state):
    _state.state = _state._StaticReplacementDialogState(_state.context)
    _state.TEXTURE_PLAN_STATUS_READY = _state.context.get('TEXTURE_PLAN_STATUS_READY')
    _state.TEXTURE_PLAN_STATUS_REVIEW = _state.context.get('TEXTURE_PLAN_STATUS_REVIEW')
    _state.TEXTURE_PLAN_STATUS_SUPPORT_ONLY = _state.context.get('TEXTURE_PLAN_STATUS_SUPPORT_ONLY')
    _state._alignment_startup_step = _state.context.get('_alignment_startup_step')
    _state._alignment_startup_texture_plan_progress_text_helper = _state.context.get('_alignment_startup_texture_plan_progress_text_helper')
    _state._apply_source_material_texture_overrides_to_ui_texture_sets = _state.context.get('_apply_source_material_texture_overrides_to_ui_texture_sets')
    _state._clear_tree_current_item = _state.context.get('_clear_tree_current_item')
    _state._current_dialog_mappings_for_preview = _state.context.get('_current_dialog_mappings_for_preview')
    _state._deferred_material_plan_display_state_helper = _state.context.get('_deferred_material_plan_display_state_helper')
    _state._empty_material_plan_display_state_helper = _state.context.get('_empty_material_plan_display_state_helper')
    _state._fit_alignment_tree_height_to_rows = _state.context.get('_fit_alignment_tree_height_to_rows')
    _state._fit_material_plan_tree_columns = _state.context.get('_fit_material_plan_tree_columns')
    _state._fit_material_routing_tree_columns = _state.context.get('_fit_material_routing_tree_columns')
    _state._is_marker_source = _state.context.get('_is_marker_source')
    _state._material_contract_block = _state.context.get('_material_contract_block')
    _state._material_plan_profile_stats_helper = _state.context.get('_material_plan_profile_stats_helper')
    _state._material_plan_route_stats_helper = _state.context.get('_material_plan_route_stats_helper')
    _state._material_plan_summary_block = _state.context.get('_material_plan_summary_block')
    _state._material_route_status_color = _state.context.get('_material_route_status_color')
    _state._material_routing_conflict_messages = _state.context.get('_material_routing_conflict_messages')
    _state._refresh_added_part_texture_tree = _state.context.get('_refresh_added_part_texture_tree')
    _state._replacement_texture_plan_item_helper = _state.context.get('_replacement_texture_plan_item_helper')
    _state._replacement_texture_plan_row_states_helper = _state.context.get('_replacement_texture_plan_row_states_helper')
    _state._replacement_texture_plan_target_name_helper = _state.context.get('_replacement_texture_plan_target_name_helper')
    _state._reset_selected_texture_plan_source_state_helper = _state.context.get('_reset_selected_texture_plan_source_state_helper')
    _state._source_display_name = _state.context.get('_source_display_name')
    _state._source_indices_for_material_name_helper = _state.context.get('_source_indices_for_material_name_helper')
    _state._source_indices_for_route_parts_helper = _state.context.get('_source_indices_for_route_parts_helper')
    _state._source_material_output_path = _state.context.get('_source_material_output_path')
    _state._source_material_part_summary_helper = _state.context.get('_source_material_part_summary_helper')
    _state._source_material_plan_display_state_helper = _state.context.get('_source_material_plan_display_state_helper')
    _state._source_material_route_item_helper = _state.context.get('_source_material_route_item_helper')
    _state._source_material_route_row_states_helper = _state.context.get('_source_material_route_row_states_helper')
    _state._source_texture_path_for_plan_row = _state.context.get('_source_texture_path_for_plan_row')
    _state._sync_texture_transform_materials = _state.context.get('_sync_texture_transform_materials')
    _state._target_index_for_name = _state.context.get('_target_index_for_name')
    _state._texture_plan_status_color = _state.context.get('_texture_plan_status_color')
    _state.alignment_startup_text = _state.context.get('alignment_startup_text')
    _state.apply_selected_source_textures_button = _state.context.get('apply_selected_source_textures_button')
    _state.apply_texture_plan_button = _state.context.get('apply_texture_plan_button')
    _state.build_replacement_texture_plan_rows = _state.context.get('build_replacement_texture_plan_rows')
    _state.build_source_material_routing_plan = _state.context.get('build_source_material_routing_plan')
    _state.conflict_messages = _state.context.get('conflict_messages')
    _state.dds_detail_panel = _state.context.get('dds_detail_panel')
    _state.detected_slot_count = _state.context.get('detected_slot_count')
    _state.display_state = _state.context.get('display_state')
    _state.entry = _state.context.get('entry')
    _state.force = _state.context.get('force')
    _state.group_replacement_texture_sets = _state.context.get('group_replacement_texture_sets')
    _state.material_contract_label = _state.context.get('material_contract_label')
    _state.material_name = _state.context.get('material_name')
    _state.material_plan_blocked = _state.context.get('material_plan_blocked')
    _state.material_plan_summary = _state.context.get('material_plan_summary')
    _state.material_plan_tree = _state.context.get('material_plan_tree')
    _state.material_routing_blocked = _state.context.get('material_routing_blocked')
    _state.material_routing_tree = _state.context.get('material_routing_tree')
    _state.plan_row_states = _state.context.get('plan_row_states')
    _state.plan_rows = _state.context.get('plan_rows')
    _state.plan_state = _state.context.get('plan_state')
    _state.profile_stats = _state.context.get('profile_stats')
    _state.route_source_indices = _state.context.get('route_source_indices')
    _state.route_state = _state.context.get('route_state')
    _state.route_stats = _state.context.get('route_stats')
    _state.routing_rows = _state.context.get('routing_rows')
    _state.row_index = _state.context.get('row_index')
    _state.selected_texture_plan_source = _state.context.get('selected_texture_plan_source')
    _state.sidecar_bindings_for_advanced = _state.context.get('sidecar_bindings_for_advanced')
    _state.source_indices_for_plan = _state.context.get('source_indices_for_plan')
    _state.source_path = _state.context.get('source_path')
    _state.source_preview_path = _state.context.get('source_preview_path')
    _state.source_texture_evidence = _state.context.get('source_texture_evidence')
    _state.target_name_for_plan = _state.context.get('target_name_for_plan')
    _state.texture_files_for_mapping = shared_context_container(_state.context, 'texture_files_for_mapping', list)
    _state.texture_material_plan_loaded = _state.context.get('texture_material_plan_loaded')
    _state.texture_set = _state.context.get('texture_set')
    _state.texture_transform_group = _state.context.get('texture_transform_group')

def _remaining_source_material_plan_refresh_step_002(_state):

    def _refresh_source_material_plan(*, force: bool=False) -> None:
        material_plan_blocked = _state.material_plan_tree.blockSignals(True)
        material_routing_blocked = _state.material_routing_tree.blockSignals(True)
        try:
            _state._clear_tree_current_item(_state.material_plan_tree)
            _state._clear_tree_current_item(_state.material_routing_tree)
            _state.material_plan_tree.clear()
            _state.material_routing_tree.clear()
        finally:
            _state.material_plan_tree.blockSignals(material_plan_blocked)
            _state.material_routing_tree.blockSignals(material_routing_blocked)
        _state._reset_selected_texture_plan_source_state_helper(_state.selected_texture_plan_source)
        _state.dds_detail_panel.setVisible(False)
        _state.texture_transform_group.setVisible(False)
        if not force and (not bool(_state.texture_material_plan_loaded.get('loaded'))):
            display_state = _state._deferred_material_plan_display_state_helper(_state.state.texture_sets)
            _state.material_plan_summary.setText(_state._material_plan_summary_block(**display_state.summary_kwargs))
            _state.material_contract_label.setText(_state._material_contract_block(**display_state.contract_kwargs))
            _state.material_routing_tree.setVisible(display_state.routing_visible)
            _state.material_plan_tree.setVisible(display_state.plan_visible)
            _state.apply_texture_plan_button.setEnabled(display_state.apply_texture_plan_enabled)
            _state.apply_selected_source_textures_button.setEnabled(display_state.apply_selected_source_enabled)
            return
        _state.texture_material_plan_loaded['loaded'] = True
        _state._alignment_startup_step(_state.alignment_startup_text['replacement_material_maps'])
        _state.state.texture_sets = _state.group_replacement_texture_sets(_state.texture_files_for_mapping, obj_mesh=_state.state.replacement_mesh_for_mapping)
        _state._apply_source_material_texture_overrides_to_ui_texture_sets(_state.state.texture_sets)
        _state._sync_texture_transform_materials()
        try:
            _state._refresh_added_part_texture_tree()
        except NameError:
            pass
        detected_slot_count = sum((len(getattr(texture_set, 'slots', {}) or {}) for texture_set in _state.state.texture_sets.values()))
        if not _state.state.texture_sets:
            display_state = _state._empty_material_plan_display_state_helper()
            _state.material_plan_summary.setText(_state._material_plan_summary_block(**display_state.summary_kwargs))
            _state.material_contract_label.setText(_state._material_contract_block(**display_state.contract_kwargs))
            _state.material_routing_tree.setVisible(display_state.routing_visible)
            _state.material_plan_tree.setVisible(display_state.plan_visible)
            _state.apply_texture_plan_button.setEnabled(display_state.apply_texture_plan_enabled)
            _state.apply_selected_source_textures_button.setEnabled(display_state.apply_selected_source_enabled)
            return
        profile_stats = _state._material_plan_profile_stats_helper(tuple(_state.source_texture_evidence or ()))
        conflict_messages = _state._material_routing_conflict_messages(_state._current_dialog_mappings_for_preview())
        routing_rows = _state.build_source_material_routing_plan(_state.state.replacement_mesh_for_mapping, _state.state.texture_sets, _state._current_dialog_mappings_for_preview())
        route_stats = _state._material_plan_route_stats_helper(_state.state.texture_sets, routing_rows, conflict_messages)
        display_state = _state._source_material_plan_display_state_helper(_state.state.texture_sets, detected_slot_count=detected_slot_count, route_count=len(routing_rows), route_stats=route_stats, profile_stats=profile_stats, has_sidecar_bindings=bool(_state.sidecar_bindings_for_advanced))
        _state.material_plan_summary.setText(_state._material_plan_summary_block(**display_state.summary_kwargs))
        _state.material_contract_label.setText(_state._material_contract_block(**display_state.contract_kwargs))
        _state.material_routing_tree.setVisible(display_state.routing_visible)
        for route_state in _state._source_material_route_row_states_helper(routing_rows):
            route_source_indices = _state._source_indices_for_route_parts_helper(route_state.source_part_names, _state.state.replacement_mesh_for_mapping, source_material_name=route_state.source_material_name, source_display_name=_state._source_display_name, source_indices_for_material_name=lambda material_name: _state._source_indices_for_material_name_helper(material_name, _state.state.replacement_mesh_for_mapping, texture_set_count=len(_state.state.texture_sets), is_marker_source=_state._is_marker_source), is_marker_source=_state._is_marker_source)
            _state.material_routing_tree.addTopLevelItem(_state._source_material_route_item_helper(route_state.route, source_indices=route_source_indices, target_index=_state._target_index_for_name(route_state.target_material_name), status_color=_state._material_route_status_color(route_state.status_label)))
        _state._fit_alignment_tree_height_to_rows(_state.material_routing_tree, minimum=80, screen_margin=420, maximum=180)
        _state._fit_material_routing_tree_columns()
        _state.material_plan_tree.setVisible(display_state.plan_visible)
        _state.apply_texture_plan_button.setEnabled(display_state.apply_texture_plan_enabled)
        plan_rows = _state.build_replacement_texture_plan_rows(_state.state.texture_sets, final_path_for_source=lambda source_path: _state._source_material_output_path(source_path, _state.entry.path), part_summary_for_material=lambda material_name: _state._source_material_part_summary_helper(material_name, _state.state.replacement_mesh_for_mapping, texture_set_count=len(_state.state.texture_sets), is_marker_source=_state._is_marker_source))
        plan_row_states = _state._replacement_texture_plan_row_states_helper(plan_rows, ready_statuses=(_state.TEXTURE_PLAN_STATUS_READY, _state.TEXTURE_PLAN_STATUS_REVIEW), support_only_statuses=(_state.TEXTURE_PLAN_STATUS_SUPPORT_ONLY,))
        for row_index, plan_state in enumerate(plan_row_states):
            if row_index and row_index % 24 == 0:
                _state._alignment_startup_step(_state._alignment_startup_texture_plan_progress_text_helper(row_index))
            source_indices_for_plan = _state._source_indices_for_material_name_helper(plan_state.material_name, _state.state.replacement_mesh_for_mapping, texture_set_count=len(_state.state.texture_sets), is_marker_source=_state._is_marker_source)
            source_preview_path = _state._source_texture_path_for_plan_row(plan_state.plan_row, plan_state.material_name, _state.state.texture_sets)
            target_name_for_plan = _state._replacement_texture_plan_target_name_helper(source_indices_for_plan, _state._current_dialog_mappings_for_preview())
            _state.material_plan_tree.addTopLevelItem(_state._replacement_texture_plan_item_helper(plan_state.plan_row, source_indices=source_indices_for_plan, target_index=_state._target_index_for_name(target_name_for_plan), target_name=target_name_for_plan, material_name=plan_state.material_name, source_preview_path=source_preview_path, preview_status=plan_state.preview_status, status_color=_state._texture_plan_status_color(plan_state.status_label), status_foreground=plan_state.status_foreground))
        _state._fit_alignment_tree_height_to_rows(_state.material_plan_tree, minimum=76, screen_margin=420, maximum=190)
        _state._fit_material_plan_tree_columns()
    _state._refresh_source_material_plan = _refresh_source_material_plan

def _remaining_source_material_plan_refresh_step_003(_state):
    _state._factory_result_values.update({'_refresh_source_material_plan': _state._refresh_source_material_plan})

STEPS = (
    _remaining_source_material_plan_refresh_step_001,
    _remaining_source_material_plan_refresh_step_002,
    _remaining_source_material_plan_refresh_step_003,
)
