from __future__ import annotations

def _texture_material_step_001(_state):
    _state.Any = _state.context.get('Any')
    _state.Callable = _state.context.get('Callable')
    _state.CollapsibleSection = _state.context.get('CollapsibleSection')
    _state.Dict = _state.context.get('Dict')
    _state.List = _state.context.get('List')
    _state.Mapping = _state.context.get('Mapping')
    _state.NameError = _state._context_builtin(_state.context, 'NameError')
    _state.Optional = _state.context.get('Optional')
    _state.QApplication = _state.context.get('QApplication')
    _state.QBrush = _state.context.get('QBrush')
    _state.QCheckBox = _state.context.get('QCheckBox')
    _state.QColor = _state.context.get('QColor')
    _state.QComboBox = _state.context.get('QComboBox')
    _state.QFileDialog = _state.context.get('QFileDialog')
    _state.QFrame = _state.context.get('QFrame')
    _state.QGridLayout = _state.context.get('QGridLayout')
    _state.QGroupBox = _state.context.get('QGroupBox')
    _state.QHBoxLayout = _state.context.get('QHBoxLayout')
    _state.QLabel = _state.context.get('QLabel')
    _state.QMessageBox = _state.context.get('QMessageBox')
    _state.QProgressBar = _state.context.get('QProgressBar')
    _state.QPushButton = _state.context.get('QPushButton')
    _state.QSizePolicy = _state.context.get('QSizePolicy')
    _state.QSplitter = _state.context.get('QSplitter')
    _state.QTextBrowser = _state.context.get('QTextBrowser')
    _state.QTimer = _state.context.get('QTimer')
    _state.QTreeWidget = _state.context.get('QTreeWidget')
    _state.QTreeWidgetItem = _state.context.get('QTreeWidgetItem')
    _state.QVBoxLayout = _state.context.get('QVBoxLayout')
    _state.QWidget = _state.context.get('QWidget')
    _state.Qt = _state.context.get('Qt')
    _state.SCENE_TEXTURE_SOURCE_EXTENSIONS = _state.context.get('SCENE_TEXTURE_SOURCE_EXTENSIONS')
    _state.Sequence = _state.context.get('Sequence')
    _state.self = _state.context.get('self')
    _state.StaticSubmeshMapping = _state.context.get('StaticSubmeshMapping')
    _state.StaticTextureSlotOverride = _state.context.get('StaticTextureSlotOverride')
    _state.TEXTURE_UV_ROTATION_OPTIONS = _state.context.get('TEXTURE_UV_ROTATION_OPTIONS')
    _state.Tuple = _state.context.get('Tuple')
    _state._added_part_texture_control_text_helper = _state.context.get('_added_part_texture_control_text_helper')
    _state._added_texture_editor_loading_initial_state_helper = _state.context.get('_added_texture_editor_loading_initial_state_helper')
    _state._advanced_dds_apply_guidance_state_helper = _state.context.get('_advanced_dds_apply_guidance_state_helper')
    _state._advanced_dds_control_text_helper = _state.context.get('_advanced_dds_control_text_helper')
    _state._advanced_dds_loading_busy_text_helper = _state.context.get('_advanced_dds_loading_busy_text_helper')
    _state._advanced_dds_loading_start_text_helper = _state.context.get('_advanced_dds_loading_start_text_helper')
    _state._advanced_dds_override_row_scan_state_helper = _state.context.get('_advanced_dds_override_row_scan_state_helper')
    _state._advanced_dds_overrides_clear_loading_helper = _state.context.get('_advanced_dds_overrides_clear_loading_helper')
    _state._advanced_dds_overrides_initial_state_helper = _state.context.get('_advanced_dds_overrides_initial_state_helper')
    _state._advanced_dds_overrides_loaded_helper = _state.context.get('_advanced_dds_overrides_loaded_helper')
    _state._advanced_dds_overrides_loading_helper = _state.context.get('_advanced_dds_overrides_loading_helper')
    _state._advanced_dds_overrides_mark_loaded_helper = _state.context.get('_advanced_dds_overrides_mark_loaded_helper')
    _state._advanced_dds_overrides_mark_loading_helper = _state.context.get('_advanced_dds_overrides_mark_loading_helper')
    _state._advanced_dds_preparing_rows_text_helper = _state.context.get('_advanced_dds_preparing_rows_text_helper')
    _state._advanced_dds_scanning_candidates_text_helper = _state.context.get('_advanced_dds_scanning_candidates_text_helper')
    _state._advanced_dds_suggested_source_counts_helper = _state.context.get('_advanced_dds_suggested_source_counts_helper')
    _state._alignment_contract_preview_path = _state.context.get('_alignment_contract_preview_path')
    _state._alignment_startup_advanced_dds_classification_progress_text_helper = _state.context.get('_alignment_startup_advanced_dds_classification_progress_text_helper')
    _state._alignment_startup_advanced_dds_guidance_progress_text_helper = _state.context.get('_alignment_startup_advanced_dds_guidance_progress_text_helper')
    _state._alignment_startup_step = _state.context.get('_alignment_startup_step')
    _state._alignment_virtual_contract_preview_specs_helper = _state.context.get('_alignment_virtual_contract_preview_specs_helper')
    _state._alignment_virtual_contract_rows_helper = _state.context.get('_alignment_virtual_contract_rows_helper')
    _state._alignment_virtual_sidecar_contract_state_helper = _state.context.get('_alignment_virtual_sidecar_contract_state_helper')
    _state._apply_source_material_texture_overrides_to_ui_texture_sets = _state.context.get('_apply_source_material_texture_overrides_to_ui_texture_sets')
    _state._best_source_for_slot = _state.context.get('_best_source_for_slot')
    if not callable(_state._best_source_for_slot):
        _state._best_source_for_slot = lambda *_args, **_kwargs: ''
    _state._binding_matches_target_callback = _state.context.get('_binding_matches_target')
    _state._binding_matches_target_helper = _state.context.get('_binding_matches_target_helper')
    _state._commit_spinbox_text = _state.context.get('_commit_spinbox_text')
    _state._configure_alignment_tree = _state.context.get('_configure_alignment_tree')
    _state._configure_texture_mapping_tree = _state.context.get('_configure_texture_mapping_tree')
    _state._confirm_texture_assignment_action_helper = _state.context.get('_confirm_texture_assignment_action_helper')
    _state._copied_source_texture_preview_specs_helper = _state.context.get('_copied_source_texture_preview_specs_helper')
    _state._copied_source_texture_slot_overrides_helper = _state.context.get('_copied_source_texture_slot_overrides_helper')
    _state._current_dialog_mappings_for_preview = _state.context.get('_current_dialog_mappings_for_preview')
    _state._fit_alignment_tree_height_to_rows = _state.context.get('_fit_alignment_tree_height_to_rows')
    _state._inline_help_button_helper = _state.context.get('_inline_help_button_helper')
    _state._is_marker_source = _state.context.get('_is_marker_source')
    _state._make_double_spin_helper = _state.context.get('_make_double_spin_helper')
    _state._material_authority_donor_control_text_helper = _state.context.get('_material_authority_donor_control_text_helper')
    _state._material_plan_control_text_helper = _state.context.get('_material_plan_control_text_helper')
    _state._original_part_texture_intent_rows = _state.context.get('_original_part_texture_intent_rows')
    _state._original_texture_preview_checkbox_tooltip_helper = _state.context.get('_original_texture_preview_checkbox_tooltip_helper')
    _state._original_texture_preview_control_text_helper = _state.context.get('_original_texture_preview_control_text_helper')
    _state._original_texture_preview_help_text_helper = _state.context.get('_original_texture_preview_help_text_helper')
    _state._original_texture_preview_material_preview_enabled_helper = _state.context.get('_original_texture_preview_material_preview_enabled_helper')
    _state._original_texture_preview_note_text_helper = _state.context.get('_original_texture_preview_note_text_helper')
    _state._original_texture_preview_note_tooltip_helper = _state.context.get('_original_texture_preview_note_tooltip_helper')
    _state._populate_combo_options_helper = _state.context.get('_populate_combo_options_helper')
    _state._queue_alignment_post_open_task = _state.context.get('_queue_alignment_post_open_task')
    _state._queue_static_preview_refresh = _state.context.get('_queue_static_preview_refresh')
    _state._queue_texture_preview_refresh = _state.context.get('_queue_texture_preview_refresh')
    _state._register_texture_source_files_helper = _state.context.get('_register_texture_source_files_helper')
    _state._registered_texture_sources_action_state_helper = _state.context.get('_registered_texture_sources_action_state_helper')
    _state._selected_added_part_texture_row_initial_state_helper = _state.context.get('_selected_added_part_texture_row_initial_state_helper')
    _state._selected_source_material_texture_action_state_helper = _state.context.get('_selected_source_material_texture_action_state_helper')
    _state._selected_texture_editor_loading_initial_state_helper = _state.context.get('_selected_texture_editor_loading_initial_state_helper')
    _state._selected_texture_plan_source_initial_state_helper = _state.context.get('_selected_texture_plan_source_initial_state_helper')
    _state._selected_texture_row_initial_state_helper = _state.context.get('_selected_texture_row_initial_state_helper')
    _state._selected_texture_source_committing_initial_state_helper = _state.context.get('_selected_texture_source_committing_initial_state_helper')
    _state._source_display_name = _state.context.get('_source_display_name')
    _state._source_indices_for_material_name_helper = _state.context.get('_source_indices_for_material_name_helper')

def _texture_material_step_002(_state):
    _state._source_indices_for_target_contract_helper = _state.context.get('_source_indices_for_target_contract_helper')
    _state._source_indices_for_target_name = _state.context.get('_source_indices_for_target_name')
    _state._source_preview_path = _state.context.get('_source_preview_path')
    _state._source_slot_for_texture_row_helper = _state.context.get('_source_slot_for_texture_row_helper')
    _state._sync_texture_row_assignment_state_helper = _state.context.get('_sync_texture_row_assignment_state_helper')
    _state._target_index_for_name = _state.context.get('_target_index_for_name')
    _state._texture_assignment_slot_item_helper = _state.context.get('_texture_assignment_slot_item_helper')
    _state._texture_assignment_summary_html = _state.context.get('_texture_assignment_summary_html')
    _state._texture_editor_control_text_helper = _state.context.get('_texture_editor_control_text_helper')
    _state._texture_override_row_sort_key = _state.context.get('_texture_override_row_sort_key')
    _state._texture_role_label_for_slot = _state.context.get('_texture_role_label_for_slot')
    _state._texture_row_current_source_indices_helper = _state.context.get('_texture_row_current_source_indices_helper')
    _state._texture_row_effective_source_helper = _state.context.get('_texture_row_effective_source_helper')
    _state._texture_row_is_assigned_helper = _state.context.get('_texture_row_is_assigned_helper')
    _state._texture_row_is_shared = _state.context.get('_texture_row_is_shared')
    _state._texture_row_override_key = _state.context.get('_texture_row_override_key')
    _state._texture_row_source_summary_helper = _state.context.get('_texture_row_source_summary_helper')
    _state._texture_set_for_source_index = _state.context.get('_texture_set_for_source_index')
    _state._texture_slot_contract_key = _state.context.get('_texture_slot_contract_key')
    _state._texture_source_choices_for_row_helper = _state.context.get('_texture_source_choices_for_row_helper')
    _state._texture_source_key = _state.context.get('_texture_source_key')
    _state._texture_transform_controls_loading_initial_state_helper = _state.context.get('_texture_transform_controls_loading_initial_state_helper')
    _state._texture_uv_control_text_helper = _state.context.get('_texture_uv_control_text_helper')
    _state._virtual_contract_sidecar_text_for_path_helper = _state.context.get('_virtual_contract_sidecar_text_for_path_helper')
    _state.alignment_startup_text = _state.context.get('alignment_startup_text')
    _state.alignment_virtual_texture_contract = _state.context.get('alignment_virtual_texture_contract')
    _state.args = _state.context.get('args')
    _state.bool = _state._context_builtin(_state.context, 'bool')
    _state.checked = _state.context.get('checked')
    _state.classify_texture_binding = _state.context.get('classify_texture_binding')
    _state.control_tabs = _state.context.get('control_tabs')
    _state.copied_original_texture_disabled_sources = _state.context.get('copied_original_texture_disabled_sources')
    _state.copied_original_texture_intents_by_source = _state.context.get('copied_original_texture_intents_by_source')
    _state.create_alignment_added_part_texture_callbacks = _state.context.get('create_alignment_added_part_texture_callbacks')
    _state.create_alignment_added_part_texture_choice_callbacks = _state.context.get('create_alignment_added_part_texture_choice_callbacks')
    _state.create_alignment_added_part_texture_override_callbacks = _state.context.get('create_alignment_added_part_texture_override_callbacks')
    _state.create_alignment_material_plan_column_callbacks = _state.context.get('create_alignment_material_plan_column_callbacks')
    _state.create_alignment_material_plan_final_preview_callbacks = _state.context.get('create_alignment_material_plan_final_preview_callbacks')
    _state.create_alignment_original_texture_material_callbacks = _state.context.get('create_alignment_original_texture_material_callbacks')
    _state.create_alignment_preview_pixmap_callbacks = _state.context.get('create_alignment_preview_pixmap_callbacks')
    _state.create_alignment_source_material_plan_refresh_callbacks = _state.context.get('create_alignment_source_material_plan_refresh_callbacks')
    _state.create_alignment_texture_detail_uv_callbacks = _state.context.get('create_alignment_texture_detail_uv_callbacks')
    _state.create_alignment_texture_table_callbacks = _state.context.get('create_alignment_texture_table_callbacks')
    _state.current = _state.context.get('current')
    _state.defer_original_texture_preview = _state.context.get('defer_original_texture_preview')
    _state.dialog = _state.context.get('dialog')
    _state.enumerate = _state._context_builtin(_state.context, 'enumerate')
    _state.expanded = _state.context.get('expanded')
    _state.getattr = _state._context_builtin(_state.context, 'getattr')
    _state.globals = _state._context_builtin(_state.context, 'globals')
    _state.group_replacement_texture_sets = _state.context.get('group_replacement_texture_sets')
    _state.index = _state.context.get('index')
    _state.inject_base_color_checkbox = _state._LateLocalProxy(_state.context.get('inject_base_color_checkbox'), 'inject_base_color_checkbox')
    _state.int = _state._context_builtin(_state.context, 'int')
    _state.is_shared_material_layer_texture = _state.context.get('is_shared_material_layer_texture')
    _state.kwargs = _state.context.get('kwargs')
    _state.len = _state._context_builtin(_state.context, 'len')
    _state.limit = _state.context.get('limit')
    _state.list = _state._context_builtin(_state.context, 'list')
    _state.locals = _state._context_builtin(_state.context, 'locals')
    _state.mapping_index = _state.context.get('mapping_index')
    _state.material_name = _state.context.get('material_name')
    _state.max = _state._context_builtin(_state.context, 'max')
    _state.modify_original_clone_mode = _state.context.get('modify_original_clone_mode')
    _state.name = _state.context.get('name')
    _state.normalize_texture_reference_for_sidecar_lookup = _state.context.get('normalize_texture_reference_for_sidecar_lookup')
    _state.obj_path = _state.context.get('obj_path')
    _state.object = _state._context_builtin(_state.context, 'object')
    _state.occupied_keys = _state.context.get('occupied_keys')
    _state.original_texture_preview_state = _state.context.get('original_texture_preview_state')
    _state.parsed_mappings = _state.context.get('parsed_mappings')
    _state.prune_unmapped_original_dds_checkbox = _state._LateLocalProxy(_state.context.get('prune_unmapped_original_dds_checkbox'), 'prune_unmapped_original_dds_checkbox')
    _state.reason = _state.context.get('reason')
    _state.rebuild_sidecar_checkbox = _state._LateLocalProxy(_state.context.get('rebuild_sidecar_checkbox'), 'rebuild_sidecar_checkbox')
    _state.refresh_status = _state.context.get('refresh_status')
    _state.replacement_mesh_for_mapping = _state.context.get('replacement_mesh_for_mapping')
    _state.rows_override = _state.context.get('rows_override')
    _state.scan_count = _state.context.get('scan_count')
    _state.seen_texture_file_keys = _state.context.get('seen_texture_file_keys')
    _state.selected_source_part = _state.context.get('selected_source_part')
    _state.set = _state._context_builtin(_state.context, 'set')
    _state.sidecar_bindings = _state.context.get('sidecar_bindings')
    _state.sidecar_key = _state.context.get('sidecar_key')
    _state.sidecar_text_values = _state.context.get('sidecar_text_values')
    _state.sidecar_texts_by_basename = _state.context.get('sidecar_texts_by_basename')
    _state.sidecar_texts_by_normalized_path = _state.context.get('sidecar_texts_by_normalized_path')
    _state.spin = _state.context.get('spin')
    _state.state = _state.context.get('state')
    _state.str = _state._context_builtin(_state.context, 'str')
    _state.suggested_mappings = _state.context.get('suggested_mappings')
    _state.texture_files_for_mapping = _state.context.get('texture_files_for_mapping')
    _state.texture_filter_refresh = _state.context.get('texture_filter_refresh')
    _state.texture_items_by_source = _state.context.get('texture_items_by_source')
    _state.texture_override_assignments = _state.context.get('texture_override_assignments')
    _state.texture_override_rows = _state.context.get('texture_override_rows')
    _state.textures_layout = _state.context.get('textures_layout')
    _state.textures_tab = _state.context.get('textures_tab')
    _state.title = _state.context.get('title')
    _state.tree = _state.context.get('tree')
    _state.tuple = _state._context_builtin(_state.context, 'tuple')

def _texture_material_step_003(_state):

    def _binding_matches_target(binding: object, target_name: str) -> bool:
        if callable(_state._binding_matches_target_callback):
            return _state.bool(_state._binding_matches_target_callback(binding, target_name))
        if callable(_state._binding_matches_target_helper):
            return _state.bool(_state._binding_matches_target_helper(binding, target_name))
        binding_names = (_state.str(_state.getattr(binding, 'part_name', '') or ''), _state.str(_state.getattr(binding, 'submesh_name', '') or ''), _state.str(_state.getattr(binding, 'material_name', '') or ''))
        target_key = _state.str(target_name or '').strip().lower()
        return _state.bool(target_key) and any((name.strip().lower() == target_key for name in binding_names))
    _state._binding_matches_target = _binding_matches_target

def _texture_material_step_004(_state):
    _state.texture_sets = _state.group_replacement_texture_sets(_state.texture_files_for_mapping, obj_mesh=_state.replacement_mesh_for_mapping)
    _state._apply_source_material_texture_overrides_to_ui_texture_sets(_state.texture_sets)
    _state.selected_texture_plan_source: _state.Dict[_state.str, _state.object] = _state.context.get('selected_texture_plan_source')
    if not isinstance(_state.selected_texture_plan_source, dict):
        _state.selected_texture_plan_source = _state._selected_texture_plan_source_initial_state_helper()
    _state.sidecar_bindings_for_advanced = _state.tuple(_state.sidecar_bindings or ())
    _state.donor_control_text = _state._material_authority_donor_control_text_helper()
    _state.donor_material_group = _state.QGroupBox(_state.str(_state.donor_control_text['group_title']))
    _state.donor_material_group.setSizePolicy(_state.QSizePolicy.Expanding, _state.QSizePolicy.Maximum)
    _state.donor_material_group.setMaximumHeight(126)
    _state.donor_material_group.setToolTip(_state.str(_state.donor_control_text['group_tooltip']))
    _state.donor_material_layout = _state.QVBoxLayout(_state.donor_material_group)
    _state.donor_material_layout.setContentsMargins(5, 3, 5, 3)
    _state.donor_material_layout.setSpacing(3)
    _state.donor_material_hint = _state.QLabel(_state.str(_state.donor_control_text['hint']))
    _state.donor_material_hint.setObjectName('HintLabel')
    _state.donor_material_hint.setWordWrap(True)
    _state.donor_material_layout.addWidget(_state.donor_material_hint)
    _state.donor_material_action_row = _state.QHBoxLayout()
    _state.donor_material_action_row.setContentsMargins(0, 0, 0, 0)
    _state.donor_material_action_row.setSpacing(4)
    _state.use_another_original_mesh_button = _state.QPushButton(_state.str(_state.donor_control_text['use_button']))
    _state.use_another_original_mesh_button.setMinimumWidth(0)
    _state.use_another_original_mesh_button.setToolTip(_state.str(_state.donor_control_text['use_button_tooltip']))
    _state.clear_donor_material_button = _state.QPushButton(_state.str(_state.donor_control_text['clear_button']))
    _state.clear_donor_material_button.setMinimumWidth(0)
    _state.clear_donor_material_button.setToolTip(_state.str(_state.donor_control_text['clear_button_tooltip']))
    _state.donor_material_action_row.addWidget(_state.use_another_original_mesh_button)
    _state.donor_material_action_row.addWidget(_state.clear_donor_material_button)
    _state.donor_material_action_row.addStretch(1)
    _state.donor_material_layout.addLayout(_state.donor_material_action_row)
    _state.donor_material_plan_tree = _state.QTreeWidget()
    _state.donor_material_plan_tree.setHeaderLabels(_state.list(_state.donor_control_text['plan_headers']))
    _state.donor_material_plan_tree.setMinimumHeight(74)
    _state.donor_material_plan_tree.setMaximumHeight(92)
    _state._configure_alignment_tree(_state.donor_material_plan_tree, (160, 120, 180, 160, 110), max_height=92, stretch_columns=(0, 2, 3), persist_key='donor_material_sources')
    _state.donor_material_plan_tree.setVisible(False)
    _state.donor_material_layout.addWidget(_state.donor_material_plan_tree, 0)
    _state.textures_layout.addWidget(_state.donor_material_group, 0)
    _state.alignment_original_texture_material_callbacks = _state.create_alignment_original_texture_material_callbacks({**_state.context, **_state._factory_globals, **vars(_state)})
    _state._stop_original_reference_texture_worker = _state.alignment_original_texture_material_callbacks._stop_original_reference_texture_worker
    _state._cleanup_original_reference_texture_worker_refs = _state.alignment_original_texture_material_callbacks._cleanup_original_reference_texture_worker_refs
    _state._handle_original_reference_texture_preview_error = _state.alignment_original_texture_material_callbacks._handle_original_reference_texture_preview_error
    _state._load_original_reference_texture_preview = _state.alignment_original_texture_material_callbacks._load_original_reference_texture_preview
    _state._highlight_texture_plan_item = _state.alignment_original_texture_material_callbacks._highlight_texture_plan_item
    _state._source_material_names_for_mapping = _state.alignment_original_texture_material_callbacks._source_material_names_for_mapping
    _state._material_routing_conflict_messages = _state.alignment_original_texture_material_callbacks._material_routing_conflict_messages
    _state._refresh_donor_material_plan_tree = _state.alignment_original_texture_material_callbacks._refresh_donor_material_plan_tree
    _state._clear_selected_donor_material_source = _state.alignment_original_texture_material_callbacks._clear_selected_donor_material_source
    _state._open_original_material_source_picker = _state.alignment_original_texture_material_callbacks._open_original_material_source_picker
    _state._set_original_texture_preview_enabled = _state.alignment_original_texture_material_callbacks._set_original_texture_preview_enabled
    _state.use_another_original_mesh_button.clicked.connect(_state._open_original_material_source_picker)
    _state.clear_donor_material_button.clicked.connect(_state._clear_selected_donor_material_source)
    _state._refresh_donor_material_plan_tree()
    _state.original_texture_preview_control_text = _state._original_texture_preview_control_text_helper()
    _state.original_texture_preview_group = _state.QGroupBox(_state.original_texture_preview_control_text['group_title'])
    _state.original_texture_preview_layout = _state.QVBoxLayout(_state.original_texture_preview_group)
    _state.original_texture_preview_layout.setContentsMargins(5, 3, 5, 3)
    _state.original_texture_preview_layout.setSpacing(3)
    _state.original_texture_preview_checkbox = _state.QCheckBox(_state.original_texture_preview_control_text['checkbox_label'])
    _state.original_texture_preview_checkbox.setChecked(_state._original_texture_preview_material_preview_enabled_helper(_state.modify_original_clone_mode, _state.original_texture_preview_state))
    _state.original_texture_preview_checkbox.setEnabled(_state.bool(_state.modify_original_clone_mode))
    _state.original_texture_preview_checkbox.setToolTip(_state._original_texture_preview_checkbox_tooltip_helper())
    _state.original_texture_preview_row = _state.QHBoxLayout()
    _state.original_texture_preview_row.setContentsMargins(0, 0, 0, 0)
    _state.original_texture_preview_row.addWidget(_state.original_texture_preview_checkbox)
    _state.original_texture_preview_row.addStretch(1)
    _state.original_texture_preview_row.addWidget(_state._inline_help_button_helper(_state._original_texture_preview_help_text_helper()))
    _state.original_texture_preview_layout.addLayout(_state.original_texture_preview_row)
    _state.original_texture_preview_note = _state.QLabel(_state._original_texture_preview_note_text_helper(modify_original_clone_mode=_state.modify_original_clone_mode, defer_original_texture_preview=_state.defer_original_texture_preview))
    _state.original_texture_preview_note.setObjectName('HintLabel')
    _state.original_texture_preview_note.setWordWrap(True)
    _state.original_texture_preview_note.setToolTip(_state._original_texture_preview_note_tooltip_helper(modify_original_clone_mode=_state.modify_original_clone_mode, defer_original_texture_preview=_state.defer_original_texture_preview))
    _state.original_texture_preview_layout.addWidget(_state.original_texture_preview_note)
    _state.original_texture_preview_note.setVisible(_state.bool(_state.modify_original_clone_mode and _state.defer_original_texture_preview))
    _state.textures_layout.addWidget(_state.original_texture_preview_group, 0)
    # Shown only once parented; visible-while-parentless briefly makes the group
    # its own top-level window during construction.
    _state.original_texture_preview_group.setVisible(_state.bool(_state.modify_original_clone_mode))
    _state.original_texture_preview_checkbox.toggled.connect(_state._set_original_texture_preview_enabled)
    _state.added_texture_control_text = _state._added_part_texture_control_text_helper()
    _state.added_texture_group = _state.QGroupBox(_state.str(_state.added_texture_control_text['group_title']))
    _state.added_texture_group.setToolTip(_state.str(_state.added_texture_control_text['group_tooltip']))
    _state.added_texture_layout = _state.QVBoxLayout(_state.added_texture_group)
    _state.added_texture_layout.setContentsMargins(5, 3, 5, 3)
    _state.added_texture_layout.setSpacing(3)
    _state.added_texture_layout.setAlignment(_state.Qt.AlignTop)
    _state.added_texture_tree = _state.QTreeWidget()
    _state.added_texture_tree.setHeaderLabels(_state.list(_state.added_texture_control_text['headers']))
    _state.added_texture_tree.setMinimumHeight(116)
    _state.added_texture_tree.setMaximumHeight(240)
    _state._configure_alignment_tree(_state.added_texture_tree, (170, 170, 150, 130, 130, 130, 130, 120), max_height=240, stretch_columns=(0, 1, 2), persist_key='added_part_textures')
    _state.added_texture_layout.addWidget(_state.added_texture_tree, 0)
    _state.added_texture_empty_label = _state.QLabel(_state.str(_state.added_texture_control_text['empty_label']))
    _state.added_texture_empty_label.setObjectName('HintLabel')
    _state.added_texture_empty_label.setSizePolicy(_state.QSizePolicy.Expanding, _state.QSizePolicy.Fixed)
    _state.added_texture_empty_label.setVisible(False)
    _state.added_texture_layout.addWidget(_state.added_texture_empty_label)
    _state.added_texture_editor = _state.QWidget()
    _state.added_texture_editor_layout = _state.QGridLayout(_state.added_texture_editor)
    _state.added_texture_editor_layout.setContentsMargins(0, 0, 0, 0)
    _state.added_texture_editor_layout.setHorizontalSpacing(4)
    _state.added_texture_editor_layout.setVerticalSpacing(2)
    _state.added_texture_role_combo = _state.QComboBox()

def _texture_material_step_005(_state):
    for _state.slot_kind, _state.label in _state.tuple(_state.added_texture_control_text['slot_options']):
        _state.added_texture_role_combo.addItem(_state.label, _state.slot_kind)
    _state.added_texture_source_combo = _state.QComboBox()
    _state.added_texture_source_combo.setSizePolicy(_state.QSizePolicy.Expanding, _state.QSizePolicy.Fixed)
    _state.added_texture_assign_button = _state.QPushButton(_state.str(_state.added_texture_control_text['assign_button']))
    _state.added_texture_assign_detected_button = _state.QPushButton(_state.str(_state.added_texture_control_text['assign_detected_button']))
    _state.added_texture_clear_button = _state.QPushButton(_state.str(_state.added_texture_control_text['clear_button']))
    _state.added_texture_choose_base_button = _state.QPushButton(_state.str(_state.added_texture_control_text['choose_base_button']))
    _state.added_texture_choose_normal_button = _state.QPushButton(_state.str(_state.added_texture_control_text['choose_normal_button']))
    _state.added_texture_choose_mask_button = _state.QPushButton(_state.str(_state.added_texture_control_text['choose_mask_button']))
    _state.added_texture_choose_height_button = _state.QPushButton(_state.str(_state.added_texture_control_text['choose_height_button']))
    for _state.button in (_state.added_texture_assign_button, _state.added_texture_assign_detected_button, _state.added_texture_clear_button, _state.added_texture_choose_base_button, _state.added_texture_choose_normal_button, _state.added_texture_choose_mask_button, _state.added_texture_choose_height_button):
        _state.button.setMinimumWidth(0)
    _state.added_texture_assign_detected_button.setToolTip(_state.str(_state.added_texture_control_text['assign_detected_tooltip']))
    _state.added_texture_choose_base_button.setToolTip(_state.str(_state.added_texture_control_text['choose_base_tooltip']))
    _state.added_texture_choose_normal_button.setToolTip(_state.str(_state.added_texture_control_text['choose_normal_tooltip']))
    _state.added_texture_choose_mask_button.setToolTip(_state.str(_state.added_texture_control_text['choose_mask_tooltip']))
    _state.added_texture_choose_height_button.setToolTip(_state.str(_state.added_texture_control_text['choose_height_tooltip']))
    _state.added_texture_clear_button.setToolTip(_state.str(_state.added_texture_control_text['clear_tooltip']))
    _state.added_texture_editor_layout.addWidget(_state.QLabel(_state.str(_state.added_texture_control_text['role_label'])), 0, 0)
    _state.added_texture_editor_layout.addWidget(_state.added_texture_role_combo, 0, 1)
    _state.added_texture_editor_layout.addWidget(_state.QLabel(_state.str(_state.added_texture_control_text['source_label'])), 0, 2)
    _state.added_texture_editor_layout.addWidget(_state.added_texture_source_combo, 0, 3, 1, 3)
    _state.added_texture_editor_layout.addWidget(_state.added_texture_assign_button, 0, 6)
    _state.added_texture_editor_layout.addWidget(_state.added_texture_clear_button, 0, 7)
    _state.added_texture_editor_layout.addWidget(_state.added_texture_assign_detected_button, 1, 0, 1, 2)
    _state.added_texture_editor_layout.addWidget(_state.added_texture_choose_base_button, 1, 2)
    _state.added_texture_editor_layout.addWidget(_state.added_texture_choose_normal_button, 1, 3)
    _state.added_texture_editor_layout.addWidget(_state.added_texture_choose_mask_button, 1, 4)
    _state.added_texture_editor_layout.addWidget(_state.added_texture_choose_height_button, 1, 5)
    _state.added_texture_editor_layout.setColumnStretch(3, 1)
    _state.added_texture_layout.addWidget(_state.added_texture_editor)
    _state.textures_layout.addWidget(_state.added_texture_group, 0)
    _state.selected_added_part_texture_row: _state.Dict[_state.str, _state.int] = _state.context.get('selected_added_part_texture_row')
    if not isinstance(_state.selected_added_part_texture_row, dict):
        _state.selected_added_part_texture_row = _state._selected_added_part_texture_row_initial_state_helper()
    _state.added_texture_editor_loading = _state._added_texture_editor_loading_initial_state_helper()
    _state.alignment_added_part_texture_override_callbacks = _state.create_alignment_added_part_texture_override_callbacks({**_state.context, **_state._factory_globals, **vars(_state), '_refresh_added_part_texture_tree': lambda *args, **kwargs: _state._refresh_added_part_texture_tree(*args, **kwargs), '_refresh_source_material_plan': lambda *args, **kwargs: _state._refresh_source_material_plan(*args, **kwargs)})
    _state._set_added_part_texture_override = _state.alignment_added_part_texture_override_callbacks._set_added_part_texture_override
    _state.alignment_added_part_texture_callbacks = _state.create_alignment_added_part_texture_callbacks({**_state.context, **_state._factory_globals, **vars(_state)})
    _state._sync_added_part_texture_group_size = _state.alignment_added_part_texture_callbacks._sync_added_part_texture_group_size
    _state._highlight_added_part_texture_source = _state.alignment_added_part_texture_callbacks._highlight_added_part_texture_source
    _state._refresh_added_part_texture_editor = _state.alignment_added_part_texture_callbacks._refresh_added_part_texture_editor
    _state._refresh_added_part_texture_tree = _state.alignment_added_part_texture_callbacks._refresh_added_part_texture_tree
    _state._current_added_part_texture_source_index = _state.alignment_added_part_texture_callbacks._current_added_part_texture_source_index
    _state._register_added_part_texture_file = _state.alignment_added_part_texture_callbacks._register_added_part_texture_file
    _state._assign_added_part_selected_texture = _state.alignment_added_part_texture_callbacks._assign_added_part_selected_texture
    _state._assign_detected_added_part_textures = _state.alignment_added_part_texture_callbacks._assign_detected_added_part_textures
    _state._choose_added_part_texture = _state.alignment_added_part_texture_callbacks._choose_added_part_texture
    _state._clear_added_part_texture_override = _state.alignment_added_part_texture_callbacks._clear_added_part_texture_override
    _state._added_texture_tree_selection_changed = _state.alignment_added_part_texture_callbacks._added_texture_tree_selection_changed
    _state._added_texture_role_changed = _state.alignment_added_part_texture_callbacks._added_texture_role_changed
    _state.alignment_added_part_texture_choice_callbacks = _state.create_alignment_added_part_texture_choice_callbacks({**_state.context, **_state._factory_globals, **vars(_state), '_refresh_source_material_plan': lambda *args, **kwargs: _state._refresh_source_material_plan(*args, **kwargs)})
    _state._choose_added_part_texture = _state.alignment_added_part_texture_choice_callbacks._choose_added_part_texture
    _state.added_texture_tree.currentItemChanged.connect(_state._added_texture_tree_selection_changed)
    _state.added_texture_role_combo.currentIndexChanged.connect(_state._added_texture_role_changed)
    _state.added_texture_assign_button.clicked.connect(_state._assign_added_part_selected_texture)
    _state.added_texture_assign_detected_button.clicked.connect(_state._assign_detected_added_part_textures)
    _state.added_texture_clear_button.clicked.connect(_state._clear_added_part_texture_override)
    _state.added_texture_choose_base_button.clicked.connect(lambda: _state._choose_added_part_texture('base'))
    _state.added_texture_choose_normal_button.clicked.connect(lambda: _state._choose_added_part_texture('normal'))
    _state.added_texture_choose_mask_button.clicked.connect(lambda: _state._choose_added_part_texture('material'))
    _state.added_texture_choose_height_button.clicked.connect(lambda: _state._choose_added_part_texture('height'))
    _state._refresh_added_part_texture_tree()
    _state.material_plan_control_text = _state._material_plan_control_text_helper()
    _state.material_plan_group = _state.QGroupBox(_state.str(_state.material_plan_control_text['group_title']))
    _state.material_plan_group.setSizePolicy(_state.QSizePolicy.Expanding, _state.QSizePolicy.Maximum)
    _state.material_plan_layout = _state.QVBoxLayout(_state.material_plan_group)
    _state.material_plan_layout.setAlignment(_state.Qt.AlignTop)
    _state.material_plan_layout.setContentsMargins(5, 3, 5, 3)
    _state.material_plan_layout.setSpacing(3)
    _state.material_plan_summary = _state.QLabel()
    _state.material_plan_summary.setWordWrap(True)
    _state.material_plan_summary.setTextFormat(_state.Qt.RichText)
    _state.material_plan_summary.setTextInteractionFlags(_state.Qt.TextSelectableByMouse)
    _state.material_plan_summary.setMaximumHeight(44)
    _state.material_plan_layout.addWidget(_state.material_plan_summary)
    _state.material_contract_label = _state.QLabel()
    _state.material_contract_label.setWordWrap(True)
    _state.material_contract_label.setTextFormat(_state.Qt.RichText)
    _state.material_contract_label.setTextInteractionFlags(_state.Qt.TextSelectableByMouse)
    _state.material_contract_label.setToolTip(_state.str(_state.material_plan_control_text['contract_tooltip']))
    _state.material_contract_label.setMaximumHeight(28)
    _state.material_plan_layout.addWidget(_state.material_contract_label)
    _state.material_plan_action_row = _state.QHBoxLayout()
    _state.apply_texture_plan_button = _state.QPushButton(_state.str(_state.material_plan_control_text['apply_suggested']))
    _state.apply_texture_plan_button.setMinimumWidth(0)
    _state.apply_texture_plan_button.setToolTip(_state.str(_state.material_plan_control_text['apply_suggested_tooltip']))
    _state.apply_selected_source_textures_button = _state.QPushButton(_state.str(_state.material_plan_control_text['use_selected']))
    _state.apply_selected_source_textures_button.setMinimumWidth(0)
    _state.apply_selected_source_textures_button.setEnabled(False)
    _state.apply_selected_source_textures_button.setToolTip(_state.str(_state.material_plan_control_text['use_selected_tooltip']))
    _state.material_use_route_source_button = _state.QPushButton(_state.str(_state.material_plan_control_text['use_route_source']))
    _state.material_keep_original_button = _state.QPushButton(_state.str(_state.material_plan_control_text['keep_original']))
    _state.material_choose_file_button = _state.QPushButton(_state.str(_state.material_plan_control_text['choose_file']))
    _state.material_neutralize_button = _state.QPushButton(_state.str(_state.material_plan_control_text['neutralize']))
    _state.material_do_not_emit_button = _state.QPushButton(_state.str(_state.material_plan_control_text['do_not_emit']))
    for _state.texture_action_button in (_state.material_use_route_source_button, _state.material_keep_original_button, _state.material_choose_file_button, _state.material_neutralize_button, _state.material_do_not_emit_button):
        _state.texture_action_button.setMinimumWidth(0)
        _state.texture_action_button.setEnabled(False)
    _state.material_use_route_source_button.setToolTip(_state.str(_state.material_plan_control_text['use_route_source_tooltip']))
    _state.material_keep_original_button.setToolTip(_state.str(_state.material_plan_control_text['keep_original_tooltip']))

def _texture_material_step_006(_state):
    _state.material_choose_file_button.setToolTip(_state.str(_state.material_plan_control_text['choose_file_tooltip']))
    _state.material_neutralize_button.setToolTip(_state.str(_state.material_plan_control_text['neutralize_tooltip']))
    _state.material_do_not_emit_button.setToolTip(_state.str(_state.material_plan_control_text['do_not_emit_tooltip']))
    _state.material_plan_action_row.addWidget(_state.apply_texture_plan_button)
    _state.material_plan_action_row.addWidget(_state.apply_selected_source_textures_button)
    _state.material_plan_action_row.addWidget(_state.material_use_route_source_button)
    _state.material_plan_action_row.addWidget(_state.material_keep_original_button)
    _state.material_plan_action_row.addWidget(_state.material_choose_file_button)
    _state.material_plan_action_row.addWidget(_state.material_neutralize_button)
    _state.material_plan_action_row.addWidget(_state.material_do_not_emit_button)
    _state.material_plan_action_row.addStretch(1)
    _state.material_plan_action_row.addWidget(_state._inline_help_button_helper(_state.str(_state.material_plan_control_text['help'])))
    _state.material_plan_layout.addLayout(_state.material_plan_action_row)
    _state.material_plan_advanced_section = _state.CollapsibleSection(_state.str(_state.material_plan_control_text['advanced_routes']), expanded=False)
    _state.material_routing_tree = _state.QTreeWidget()
    _state.material_routing_tree.setHeaderLabels(_state.list(_state.material_plan_control_text['material_routing_headers']))
    _state.material_routing_tree.setMinimumHeight(80)
    _state.material_routing_tree.setMinimumWidth(0)
    _state._configure_alignment_tree(_state.material_routing_tree, (130, 130, 150, 90, 70, 180), max_height=180, stretch_columns=(2, 5), persist_key='replacement_material_routing')
    _state.material_plan_advanced_section.body_layout.addWidget(_state.material_routing_tree)
    _state.material_plan_tree = _state.QTreeWidget()
    _state.material_plan_tree.setHeaderLabels(_state.list(_state.material_plan_control_text['material_plan_headers']))
    _state.material_plan_tree.setMinimumHeight(76)
    _state.material_plan_tree.setMinimumWidth(0)
    _state._configure_alignment_tree(_state.material_plan_tree, (80, 64, 170, 240, 64, 120), max_height=190, stretch_columns=(2, 3), persist_key='replacement_texture_plan')
    _state.material_plan_layout.addWidget(_state.material_plan_tree)
    _state.dds_detail_panel = _state.QFrame()
    _state.dds_detail_panel.setObjectName('DDSDetailPane')
    _state.dds_detail_panel.setMaximumHeight(150)
    _state.dds_detail_layout = _state.QHBoxLayout(_state.dds_detail_panel)
    _state.dds_detail_layout.setContentsMargins(0, 0, 0, 0)
    _state.dds_detail_layout.setSpacing(8)
    _state.dds_detail_thumbnail_label = _state.QLabel(_state.str(_state.material_plan_control_text['dds_detail_no_preview']))
    _state.dds_detail_thumbnail_label.setObjectName('DDSDetailThumbnail')
    _state.dds_detail_thumbnail_label.setAlignment(_state.Qt.AlignCenter)
    _state.dds_detail_thumbnail_label.setFixedSize(128, 128)
    _state.dds_detail_thumbnail_label.setScaledContents(False)
    _state.dds_detail_thumbnail_label.setStyleSheet('QLabel#DDSDetailThumbnail { border: 1px solid #30363d; background: #0d1117; color: #8b949e; }')
    _state.dds_detail_label = _state.QLabel(_state.str(_state.material_plan_control_text['dds_detail_select_row']))
    _state.dds_detail_label.setObjectName('HintLabel')
    _state.dds_detail_label.setWordWrap(True)
    _state.dds_detail_label.setTextInteractionFlags(_state.Qt.TextSelectableByMouse)
    _state.dds_detail_label.setTextFormat(_state.Qt.RichText)
    _state.dds_detail_layout.addWidget(_state.dds_detail_thumbnail_label, 0)
    _state.dds_detail_layout.addWidget(_state.dds_detail_label, 1)
    _state.material_plan_layout.addWidget(_state.dds_detail_panel)
    _state.dds_detail_panel.setVisible(False)
    _state.alignment_preview_pixmap_callbacks = _state.create_alignment_preview_pixmap_callbacks({**_state.context, **_state._factory_globals, **vars(_state)})
    _state._read_preview_pixmap = _state.alignment_preview_pixmap_callbacks._read_preview_pixmap
    _state.texture_uv_control_text = _state._texture_uv_control_text_helper()
    _state.texture_transform_group = _state.QGroupBox(_state.texture_uv_control_text['transform_group'])
    _state.texture_transform_group.setSizePolicy(_state.QSizePolicy.Expanding, _state.QSizePolicy.Maximum)
    _state.texture_transform_layout = _state.QGridLayout(_state.texture_transform_group)
    _state.texture_transform_layout.setContentsMargins(5, 3, 5, 3)
    _state.texture_transform_layout.setHorizontalSpacing(5)
    _state.texture_transform_layout.setVerticalSpacing(2)
    _state.texture_transform_layout.setColumnStretch(1, 1)
    _state.texture_transform_note = _state.QLabel(_state.texture_uv_control_text['note'])
    _state.texture_transform_note.setObjectName('HintLabel')
    _state.texture_transform_note.setWordWrap(True)
    _state.texture_transform_note.setToolTip(_state.texture_uv_control_text['help'])
    _state.texture_transform_note.setVisible(False)
    _state.texture_transform_header_row = _state.QHBoxLayout()
    _state.texture_transform_header_row.setContentsMargins(0, 0, 0, 0)
    _state.texture_transform_header_row.addWidget(_state.texture_transform_note, 1)
    _state.texture_transform_header_row.addWidget(_state._inline_help_button_helper(_state.texture_uv_control_text['help']))
    _state.texture_transform_layout.addLayout(_state.texture_transform_header_row, 0, 0, 1, 6)
    _state.texture_transform_material_combo = _state.QComboBox()
    _state.texture_transform_material_combo.setSizePolicy(_state.QSizePolicy.Expanding, _state.QSizePolicy.Fixed)
    _state.texture_transform_material_combo.setToolTip(_state.texture_uv_control_text['material_tooltip'])
    _state.texture_transform_rotate_combo = _state.QComboBox()
    _state._populate_combo_options_helper(_state.texture_transform_rotate_combo, _state.TEXTURE_UV_ROTATION_OPTIONS)
    _state.texture_transform_rotate_combo.setToolTip(_state.texture_uv_control_text['rotate_tooltip'])
    _state.texture_transform_flip_u_checkbox = _state.QCheckBox(_state.texture_uv_control_text['flip_u_label'])
    _state.texture_transform_flip_u_checkbox.setToolTip(_state.texture_uv_control_text['flip_u_tooltip'])
    _state.texture_transform_flip_v_checkbox = _state.QCheckBox(_state.texture_uv_control_text['flip_v_label'])
    _state.texture_transform_flip_v_checkbox.setToolTip(_state.texture_uv_control_text['flip_v_tooltip'])
    _state.texture_transform_offset_u_spin = _state._make_double_spin_helper(0.0, -10.0, 10.0, 4, 0.01)
    _state.texture_transform_offset_v_spin = _state._make_double_spin_helper(0.0, -10.0, 10.0, 4, 0.01)
    _state.texture_transform_scale_u_spin = _state._make_double_spin_helper(1.0, 0.01, 100.0, 4, 0.01)
    _state.texture_transform_scale_v_spin = _state._make_double_spin_helper(1.0, 0.01, 100.0, 4, 0.01)
    for _state.texture_transform_spin in (_state.texture_transform_offset_u_spin, _state.texture_transform_offset_v_spin, _state.texture_transform_scale_u_spin, _state.texture_transform_scale_v_spin):
        _state.texture_transform_spin.setMinimumWidth(76)
        _state.texture_transform_spin.setSizePolicy(_state.QSizePolicy.Expanding, _state.QSizePolicy.Fixed)
    _state.texture_transform_offset_u_spin.setToolTip(_state.texture_uv_control_text['offset_u_tooltip'])
    _state.texture_transform_offset_v_spin.setToolTip(_state.texture_uv_control_text['offset_v_tooltip'])
    _state.texture_transform_scale_u_spin.setToolTip(_state.texture_uv_control_text['scale_u_tooltip'])
    _state.texture_transform_scale_v_spin.setToolTip(_state.texture_uv_control_text['scale_v_tooltip'])
    _state.texture_transform_reset_button = _state.QPushButton(_state.texture_uv_control_text['reset_button'])
    _state.texture_transform_reset_button.setMinimumWidth(0)
    _state.texture_transform_reset_button.setToolTip(_state.texture_uv_control_text['reset_tooltip'])
    _state.texture_transform_layout.addWidget(_state.QLabel(_state.texture_uv_control_text['material_label']), 1, 0)
    _state.texture_transform_layout.addWidget(_state.texture_transform_material_combo, 1, 1, 1, 4)
    _state.texture_transform_layout.addWidget(_state.texture_transform_reset_button, 1, 5)
    _state.texture_transform_layout.addWidget(_state.QLabel(_state.texture_uv_control_text['rotate_label']), 2, 0)
    _state.texture_transform_layout.addWidget(_state.texture_transform_rotate_combo, 2, 1, 1, 2)
    _state.texture_transform_layout.addWidget(_state.texture_transform_flip_u_checkbox, 2, 3)
    _state.texture_transform_layout.addWidget(_state.texture_transform_flip_v_checkbox, 2, 4, 1, 2)
    _state.texture_transform_layout.addWidget(_state.QLabel(_state.texture_uv_control_text['offset_u_label']), 3, 0)
    _state.texture_transform_layout.addWidget(_state.texture_transform_offset_u_spin, 3, 1)

def _texture_material_step_007(_state):
    _state.texture_transform_layout.addWidget(_state.QLabel(_state.texture_uv_control_text['offset_v_label']), 3, 2)
    _state.texture_transform_layout.addWidget(_state.texture_transform_offset_v_spin, 3, 3)
    _state.texture_transform_layout.addWidget(_state.QLabel(_state.texture_uv_control_text['scale_u_label']), 4, 0)
    _state.texture_transform_layout.addWidget(_state.texture_transform_scale_u_spin, 4, 1)
    _state.texture_transform_layout.addWidget(_state.QLabel(_state.texture_uv_control_text['scale_v_label']), 4, 2)
    _state.texture_transform_layout.addWidget(_state.texture_transform_scale_v_spin, 4, 3)
    _state.material_routing_tree.currentItemChanged.connect(lambda current, _previous: _state._highlight_texture_plan_item(current))
    _state.material_plan_tree.currentItemChanged.connect(lambda current, _previous: _state._highlight_texture_plan_item(current))
    _state.texture_transform_controls_loading = _state._texture_transform_controls_loading_initial_state_helper()
    _state.alignment_texture_detail_uv_callbacks = _state.create_alignment_texture_detail_uv_callbacks({**_state.context, **_state._factory_globals, **vars(_state)})
    _state._apply_dds_detail_thumbnail_state = _state.alignment_texture_detail_uv_callbacks._apply_dds_detail_thumbnail_state
    _state._resolve_dds_detail_preview_path = _state.alignment_texture_detail_uv_callbacks._resolve_dds_detail_preview_path
    _state._refresh_dds_detail_thumbnail = _state.alignment_texture_detail_uv_callbacks._refresh_dds_detail_thumbnail
    _state._set_texture_transform_controls_enabled = _state.alignment_texture_detail_uv_callbacks._set_texture_transform_controls_enabled
    _state._load_texture_transform_controls = _state.alignment_texture_detail_uv_callbacks._load_texture_transform_controls
    _state._save_texture_transform_controls = _state.alignment_texture_detail_uv_callbacks._save_texture_transform_controls
    _state._sync_texture_transform_materials = _state.alignment_texture_detail_uv_callbacks._sync_texture_transform_materials
    _state._handle_texture_transform_material_changed = _state.alignment_texture_detail_uv_callbacks._handle_texture_transform_material_changed
    _state._reset_selected_texture_transform = _state.alignment_texture_detail_uv_callbacks._reset_selected_texture_transform
    _state.texture_transform_material_combo.currentIndexChanged.connect(_state._handle_texture_transform_material_changed)
    _state.texture_transform_rotate_combo.currentIndexChanged.connect(_state._save_texture_transform_controls)
    _state.texture_transform_flip_u_checkbox.toggled.connect(_state._save_texture_transform_controls)
    _state.texture_transform_flip_v_checkbox.toggled.connect(_state._save_texture_transform_controls)
    _state.texture_transform_offset_u_spin.valueChanged.connect(_state._save_texture_transform_controls)
    _state.texture_transform_offset_v_spin.valueChanged.connect(_state._save_texture_transform_controls)
    _state.texture_transform_scale_u_spin.valueChanged.connect(_state._save_texture_transform_controls)
    _state.texture_transform_scale_v_spin.valueChanged.connect(_state._save_texture_transform_controls)
    for _state.texture_spin in (_state.texture_transform_offset_u_spin, _state.texture_transform_offset_v_spin, _state.texture_transform_scale_u_spin, _state.texture_transform_scale_v_spin):
        _state.texture_spin.editingFinished.connect(lambda spin=_state.texture_spin: (_state._commit_spinbox_text(spin), _state._save_texture_transform_controls()))
    _state.texture_transform_reset_button.clicked.connect(_state._reset_selected_texture_transform)
    _state.material_plan_layout.addWidget(_state.texture_transform_group)
    _state.texture_transform_group.setVisible(False)
    _state.material_plan_layout.addWidget(_state.material_plan_advanced_section)
    _state.alignment_material_plan_column_callbacks = _state.create_alignment_material_plan_column_callbacks({**_state.context, **_state._factory_globals, **vars(_state)})
    _state._fit_material_routing_tree_columns = _state.alignment_material_plan_column_callbacks._fit_material_routing_tree_columns
    _state._fit_material_plan_tree_columns = _state.alignment_material_plan_column_callbacks._fit_material_plan_tree_columns
    _state._schedule_material_plan_column_refit = _state.alignment_material_plan_column_callbacks._schedule_material_plan_column_refit
    _state.alignment_original_texture_material_callbacks = _state.create_alignment_original_texture_material_callbacks({**_state.context, **_state._factory_globals, **vars(_state)})
    _state._highlight_texture_plan_item = _state.alignment_original_texture_material_callbacks._highlight_texture_plan_item
    _state._source_material_names_for_mapping = _state.alignment_original_texture_material_callbacks._source_material_names_for_mapping
    _state._material_routing_conflict_messages = _state.alignment_original_texture_material_callbacks._material_routing_conflict_messages
    _state._refresh_donor_material_plan_tree = _state.alignment_original_texture_material_callbacks._refresh_donor_material_plan_tree
    _state._clear_selected_donor_material_source = _state.alignment_original_texture_material_callbacks._clear_selected_donor_material_source
    _state._open_original_material_source_picker = _state.alignment_original_texture_material_callbacks._open_original_material_source_picker
    _state.alignment_source_material_plan_refresh_callbacks = _state.create_alignment_source_material_plan_refresh_callbacks({**_state.context, **_state._factory_globals, **vars(_state)})
    _state._refresh_source_material_plan = _state.alignment_source_material_plan_refresh_callbacks._refresh_source_material_plan
    _state._source_indices_for_target_contract = lambda target_name, material_name='': _state._source_indices_for_target_contract_helper(target_name, material_name, target_index_for_name=_state._target_index_for_name, mappings=_state._current_dialog_mappings_for_preview(), source_indices_for_material_name=lambda name: _state._source_indices_for_material_name_helper(name, _state.replacement_mesh_for_mapping, texture_set_count=_state.len(_state.texture_sets), is_marker_source=_state._is_marker_source))
    _state.alignment_material_plan_final_preview_callbacks = _state.create_alignment_material_plan_final_preview_callbacks({**_state.context, **_state._factory_globals, **vars(_state)})
    _state._refresh_material_plan_from_final_preview = _state.alignment_material_plan_final_preview_callbacks._refresh_material_plan_from_final_preview
    _state._ensure_source_material_plan_loaded = _state.alignment_material_plan_final_preview_callbacks._ensure_source_material_plan_loaded
    _state._refresh_source_material_plan()
    _state.control_tabs.currentChanged.connect(lambda index: _state._ensure_source_material_plan_loaded() if _state.control_tabs.widget(index) is _state.textures_tab else None)
    _state.textures_layout.addWidget(_state.material_plan_group, 0)
    _state._schedule_material_plan_column_refit()
    _state.apply_texture_plan_button.setEnabled(_state.bool(_state.texture_sets and _state.sidecar_bindings_for_advanced))
    _state.texture_assignment_rows_skipped = False
    _state.deferred_sidecar_bindings_for_advanced = _state.tuple(_state.sidecar_bindings_for_advanced or ())
    _state.estimated_advanced_texture_work = _state.len(_state.deferred_sidecar_bindings_for_advanced) * _state.max(1, _state.len(_state.tuple(_state.suggested_mappings or ()))) * _state.max(1, _state.len(_state.texture_files_for_mapping))
    _state.initial_static_preview_refreshed = False
    _state._factory_advanced_material_branch = _state.sidecar_bindings_for_advanced

def _texture_material_step_008(_state):
    if _state._factory_advanced_material_branch:
        _state.advanced_dds_control_text = _state._advanced_dds_control_text_helper()
        _state.texture_group = _state.QGroupBox(_state.str(_state.advanced_dds_control_text['group_title']))
        _state.texture_group.setObjectName('AdvancedDDSOverrides')
        _state.texture_group.setToolTip(_state.str(_state.advanced_dds_control_text['group_tooltip']))
        _state.texture_group.setSizePolicy(_state.QSizePolicy.Expanding, _state.QSizePolicy.Expanding)
        _state.texture_layout = _state.QVBoxLayout(_state.texture_group)
        _state.texture_layout.setAlignment(_state.Qt.AlignTop)
        _state.texture_layout.setContentsMargins(0, 0, 0, 0)
        _state.texture_layout.setSpacing(3)
        _state.texture_hint = _state.QLabel(_state.str(_state.advanced_dds_control_text['hint_label']))
        _state.texture_hint.setWordWrap(True)
        _state.texture_hint.setTextFormat(_state.Qt.RichText)
        _state.texture_hint.setText(_state.str(_state.advanced_dds_control_text['hint_html']))
        _state.texture_hint.setToolTip(_state.str(_state.advanced_dds_control_text['hint_tooltip']))
        _state.texture_hint.setObjectName('HintLabel')
        _state.texture_layout.addWidget(_state.texture_hint)
        _state.texture_hint.setVisible(False)
        if not _state.texture_files_for_mapping:
            _state.no_sources_hint = _state.QLabel(_state.str(_state.advanced_dds_control_text['no_sources_hint']))
            _state.no_sources_hint.setWordWrap(True)
            _state.no_sources_hint.setObjectName('HintLabel')
            _state.texture_layout.addWidget(_state.no_sources_hint)
        _state.advanced_dds_lazy_placeholder = _state.QWidget(_state.texture_group)
        _state.advanced_dds_lazy_layout = _state.QHBoxLayout(_state.advanced_dds_lazy_placeholder)
        _state.advanced_dds_lazy_layout.setContentsMargins(5, 3, 5, 3)
        _state.advanced_dds_lazy_layout.setSpacing(6)
        _state.advanced_dds_lazy_label = _state.QLabel(_state.str(_state.advanced_dds_control_text['lazy_label']))
        _state.advanced_dds_lazy_label.setWordWrap(True)
        _state.advanced_dds_lazy_label.setObjectName('HintLabel')
        _state.advanced_dds_lazy_label.setToolTip(_state.str(_state.advanced_dds_control_text['lazy_tooltip']))
        _state.advanced_dds_load_button = _state.QPushButton(_state.str(_state.advanced_dds_control_text['load_button']))
        _state.advanced_dds_load_button.setToolTip(_state.str(_state.advanced_dds_control_text['load_tooltip']))
        _state.advanced_dds_lazy_layout.addWidget(_state.advanced_dds_lazy_label, 1)
        _state.advanced_dds_lazy_layout.addWidget(_state.advanced_dds_load_button, 0)
        _state.texture_layout.addWidget(_state.advanced_dds_lazy_placeholder)
        _state.texture_action_row = _state.QHBoxLayout()
        _state.texture_action_row.setContentsMargins(0, 0, 0, 0)
        _state.texture_action_row.setSpacing(3)
        _state.apply_all_suggested_overrides_button = _state.QPushButton(_state.str(_state.advanced_dds_control_text['apply_all_button']))
        _state.apply_all_suggested_overrides_button.setText(_state.str(_state.advanced_dds_control_text['apply_all_short']))
        _state.clear_target_textures_button = _state.QPushButton(_state.str(_state.advanced_dds_control_text['clear_target_button']))
        _state.keep_original_target_button = _state.QPushButton(_state.str(_state.advanced_dds_control_text['keep_original_button']))
        _state.do_not_emit_texture_button = _state.QPushButton(_state.str(_state.advanced_dds_control_text['do_not_emit_button']))
        _state.add_textures_button = _state.QPushButton(_state.str(_state.advanced_dds_control_text['add_textures_button']))
        _state.add_texture_folder_button = _state.QPushButton(_state.str(_state.advanced_dds_control_text['add_folder_button']))
        _state.apply_all_suggested_overrides_button.setToolTip(_state.str(_state.advanced_dds_control_text['apply_all_tooltip']))
        _state.clear_target_textures_button.setToolTip(_state.str(_state.advanced_dds_control_text['clear_target_tooltip']))
        _state.keep_original_target_button.setToolTip(_state.str(_state.advanced_dds_control_text['keep_original_tooltip']))
        _state.do_not_emit_texture_button.setToolTip(_state.str(_state.advanced_dds_control_text['do_not_emit_tooltip']))
        _state.add_textures_button.setToolTip(_state.str(_state.advanced_dds_control_text['add_textures_tooltip']))
        _state.add_texture_folder_button.setToolTip(_state.str(_state.advanced_dds_control_text['add_folder_tooltip']))
        for _state.texture_button in (_state.apply_all_suggested_overrides_button, _state.clear_target_textures_button, _state.keep_original_target_button, _state.do_not_emit_texture_button, _state.add_textures_button, _state.add_texture_folder_button):
            _state.texture_button.setMinimumWidth(0)
            _state.texture_action_row.addWidget(_state.texture_button)
        _state.texture_action_row.addStretch(1)
        _state.texture_layout.addLayout(_state.texture_action_row)
        _state.texture_filter_selected_checkbox = _state.QCheckBox(_state.str(_state.advanced_dds_control_text['filter_active_parts']))
        _state.texture_filter_selected_checkbox.setChecked(False)
        _state.texture_filter_selected_checkbox.setToolTip(_state.str(_state.advanced_dds_control_text['filter_active_parts_tooltip']))
        _state.texture_show_advanced_checkbox = _state.QCheckBox(_state.str(_state.advanced_dds_control_text['filter_advanced_slots']))
        _state.texture_show_advanced_checkbox.setToolTip(_state.str(_state.advanced_dds_control_text['filter_advanced_slots_tooltip']))
        _state.texture_filter_row = _state.QHBoxLayout()
        _state.texture_filter_row.setContentsMargins(0, 0, 0, 0)
        _state.texture_filter_row.setSpacing(4)
        _state.texture_filter_row.addWidget(_state.texture_filter_selected_checkbox)
        _state.texture_filter_row.addWidget(_state.texture_show_advanced_checkbox)
        _state.texture_filter_row.addStretch(1)
        _state.texture_layout.addLayout(_state.texture_filter_row)
        _state.texture_rows_by_target: _state.Dict[_state.str, _state.List[_state.Dict[_state.str, _state.Any]]] = {}
        _state.texture_target_source_indices: _state.Dict[_state.str, _state.Tuple[_state.int, ...]] = {}
        _state.seen_texture_rows: _state.set[_state.tuple[_state.str, _state.str, _state.str, _state.str]] = _state.set()
        _state.advanced_dds_overrides_state = _state._advanced_dds_overrides_initial_state_helper()
        _state.advanced_dds_controller = _state.StaticReplacementAdvancedDdsController(_state.self, _state.dialog)
        setattr(_state.dialog, '_advanced_dds_controller', _state.advanced_dds_controller)
        _state.dialog.finished.connect(lambda _result=0: _state.advanced_dds_controller.request_shutdown())

def _texture_material_step_009(_state):
    if _state._factory_advanced_material_branch:

        def _advanced_dds_rows_ready(scan_state: object) -> None:
            for target_name, rows in scan_state.rows_by_target.items():
                _state.texture_rows_by_target.setdefault(target_name, []).extend(rows)
            _state.texture_target_source_indices.update(scan_state.target_source_indices)
            _state.texture_override_rows.extend(scan_state.texture_override_rows)
            _state.seen_texture_rows.clear()
            _state.seen_texture_rows.update(scan_state.seen_texture_rows)
            _state._advanced_dds_overrides_mark_loaded_helper(_state.advanced_dds_overrides_state)
            _state.advanced_dds_lazy_placeholder.setVisible(False)
            _state._refresh_texture_row_guidance()
            _state._refresh_texture_table(_state.selected_texture_row.get('row'))
            _state._queue_texture_preview_refresh()
        _state._advanced_dds_rows_ready = _advanced_dds_rows_ready

def _texture_material_step_010(_state):
    if _state._factory_advanced_material_branch:

        def _advanced_dds_rows_failed(message: str) -> None:
            _state.self.set_status_message(f'Advanced DDS row loading failed: {message}', error=True)
        _state._advanced_dds_rows_failed = _advanced_dds_rows_failed

def _texture_material_step_011(_state):
    if _state._factory_advanced_material_branch:

        def _advanced_dds_rows_idle() -> None:
            _state._advanced_dds_overrides_clear_loading_helper(_state.advanced_dds_overrides_state)
            _state.texture_busy_bar.setVisible(False)
        _state._advanced_dds_rows_idle = _advanced_dds_rows_idle

STEPS = (
    _texture_material_step_001,
    _texture_material_step_002,
    _texture_material_step_003,
    _texture_material_step_004,
    _texture_material_step_005,
    _texture_material_step_006,
    _texture_material_step_007,
    _texture_material_step_008,
    _texture_material_step_009,
    _texture_material_step_010,
    _texture_material_step_011,
)
