from pathlib import Path
import unittest

from tests.hkx_editor_dialog_source_support import hkx_editor_dialog_source


ROOT = Path(__file__).resolve().parents[1]
MAIN_WINDOW = ROOT / "cdmw" / "ui" / "shell" / "app_window.py"
SIGNAL_WIRING = ROOT / "cdmw" / "ui" / "shell" / "signal_wiring.py"
ARCHIVE_BROWSER_ACTIONS = ROOT / "cdmw" / "ui" / "archive_browser" / "actions.py"
ARCHIVE_ATTACHMENT_BATCH = ROOT / "cdmw" / "ui" / "archive_browser" / "attachment_batch.py"
ARCHIVE_ATTACHMENT_DONOR_PICKER_DIALOG = ROOT / "cdmw" / "ui" / "archive_browser" / "attachment_donor_picker_dialog.py"
ARCHIVE_ATTACHMENT_PLACEMENT_DIFF_DIALOG = ROOT / "cdmw" / "ui" / "archive_browser" / "attachment_placement_diff_dialog.py"
ARCHIVE_ATTACHMENT_PACKAGE = ROOT / "cdmw" / "ui" / "archive_browser" / "attachment_package.py"
ARCHIVE_ATTACHMENT_PLAN = ROOT / "cdmw" / "ui" / "archive_browser" / "attachment_plan.py"
ARCHIVE_ATTACHMENT_VISUAL_DIALOG = ROOT / "cdmw" / "ui" / "archive_browser" / "attachment_visual_dialog.py"
ARCHIVE_ATTACHMENT_VISUAL_GEOMETRY = ROOT / "cdmw" / "ui" / "archive_browser" / "attachment_visual_geometry.py"
ARCHIVE_ATTACHMENT_VISUAL_PREVIEW = ROOT / "cdmw" / "ui" / "archive_browser" / "attachment_visual_preview.py"
ARCHIVE_ASSET_FAMILY_DIALOG = ROOT / "cdmw" / "ui" / "archive_browser" / "asset_family_dialog.py"
ARCHIVE_ASSET_FAMILY_LAYOUT = ROOT / "cdmw" / "ui" / "archive_browser" / "asset_family_layout.py"
ARCHIVE_BINARY_SIDECAR_ACTIONS = ROOT / "cdmw" / "ui" / "archive_browser" / "binary_sidecar_actions.py"
ARCHIVE_HKX_DOCUMENT_ACTIONS = ROOT / "cdmw" / "ui" / "archive_browser" / "hkx_document_actions.py"
ARCHIVE_HKX_EDITOR_DIALOG = ROOT / "cdmw" / "ui" / "archive_browser" / "hkx_editor_dialog.py"
ARCHIVE_HKX_EDITOR_DIALOG_HELPERS = ROOT / "cdmw" / "ui" / "archive_browser" / "hkx_editor_dialog_helpers.py"
ARCHIVE_HKX_XML_HIGHLIGHTER = ROOT / "cdmw" / "ui" / "archive_browser" / "hkx_xml_highlighter.py"
ARCHIVE_REFERENCE_PREVIEW = ROOT / "cdmw" / "ui" / "archive_browser" / "reference_preview.py"
ARCHIVE_STATIC_PREVIEW_THUMBNAIL = ROOT / "cdmw" / "ui" / "archive_browser" / "static_preview_thumbnail.py"
ARCHIVE_PREVIEW_LAYOUT = ROOT / "cdmw" / "ui" / "archive_browser" / "preview_layout.py"
WIDGETS = ROOT / "cdmw" / "ui" / "widgets.py"
ARCHIVE_CORE = ROOT / "cdmw" / "core" / "archive.py"
ARCHIVE_HKX_CORE = ROOT / "cdmw" / "core" / "archive_hkx.py"
ARCHIVE_PREVIEW_RESULT_BUILDER = ROOT / "cdmw" / "core" / "archive_preview_result_builder.py"


def _hkx_action_sources() -> str:
    return "\n".join(
        (
            ARCHIVE_BINARY_SIDECAR_ACTIONS.read_text(encoding="utf-8"),
            ARCHIVE_HKX_DOCUMENT_ACTIONS.read_text(encoding="utf-8"),
        )
    )


def _hkx_editor_sources() -> str:
    return "\n".join(
        (
            hkx_editor_dialog_source(ROOT),
            ARCHIVE_HKX_EDITOR_DIALOG_HELPERS.read_text(encoding="utf-8"),
        )
    )


class HkxUiSourceGuardTests(unittest.TestCase):
    def test_hkx_xml_highlighter_scans_comments_without_html_tag_regex(self) -> None:
        highlighter_body = ARCHIVE_HKX_XML_HIGHLIGHTER.read_text(encoding="utf-8")

        self.assertIn("def _highlight_xml_comments", highlighter_body)
        self.assertIn('text.find("<!--")', highlighter_body)
        self.assertIn('text.find("-->", start_index + 4)', highlighter_body)
        self.assertIn("self.previousBlockState() == 1", highlighter_body)
        self.assertIn("self.setCurrentBlockState(0)", highlighter_body)
        self.assertIn("self.setCurrentBlockState(1)", highlighter_body)
        self.assertNotIn("<!--" + ".*?" + "-->", highlighter_body)

    def test_archive_browser_exposes_hkx_json_export_import_actions(self) -> None:
        source = "\n".join(
            (
                MAIN_WINDOW.read_text(encoding="utf-8"),
                SIGNAL_WIRING.read_text(encoding="utf-8"),
                ARCHIVE_PREVIEW_LAYOUT.read_text(encoding="utf-8"),
                _hkx_action_sources(),
                _hkx_editor_sources(),
                ARCHIVE_BROWSER_ACTIONS.read_text(encoding="utf-8"),
                ARCHIVE_ATTACHMENT_BATCH.read_text(encoding="utf-8"),
                ARCHIVE_ATTACHMENT_DONOR_PICKER_DIALOG.read_text(encoding="utf-8"),
                ARCHIVE_ATTACHMENT_PLACEMENT_DIFF_DIALOG.read_text(encoding="utf-8"),
                ARCHIVE_ASSET_FAMILY_DIALOG.read_text(encoding="utf-8"),
                ARCHIVE_ASSET_FAMILY_LAYOUT.read_text(encoding="utf-8"),
                ARCHIVE_REFERENCE_PREVIEW.read_text(encoding="utf-8"),
                ARCHIVE_STATIC_PREVIEW_THUMBNAIL.read_text(encoding="utf-8"),
                ARCHIVE_ATTACHMENT_VISUAL_DIALOG.read_text(encoding="utf-8"),
                ARCHIVE_ATTACHMENT_VISUAL_GEOMETRY.read_text(encoding="utf-8"),
                ARCHIVE_ATTACHMENT_VISUAL_PREVIEW.read_text(encoding="utf-8"),
                ARCHIVE_CORE.read_text(encoding="utf-8"),
                ARCHIVE_HKX_CORE.read_text(encoding="utf-8"),
            )
        )

        self.assertIn('QPushButton("Export HKX JSON...")', source)
        self.assertIn('QPushButton("Import HKX JSON...")', source)
        self.assertIn('QPushButton("Export HKX XML...")', source)
        self.assertIn('QPushButton("Export Havok XML View...")', source)
        self.assertIn('QPushButton("Import HKX XML...")', source)
        self.assertIn('QPushButton("Edit HKX...")', source)
        self.assertIn('self.archive_hkx_placement_button = QPushButton("Edit HKX...")', source)
        self.assertIn('QPushButton("Scan HKX Corpus...")', source)
        self.assertIn("archive_hkx_export_json_button.clicked.connect(self._export_current_archive_hkx_json)", source)
        self.assertIn("archive_hkx_import_json_button.clicked.connect(self._import_current_archive_hkx_json)", source)
        self.assertIn("archive_hkx_export_xml_button.clicked.connect(self._export_current_archive_hkx_xml)", source)
        self.assertIn("archive_hkx_export_havok_xml_view_button.clicked.connect(self._export_current_archive_hkx_havok_xml_view)", source)
        self.assertIn("archive_hkx_import_xml_button.clicked.connect(self._import_current_archive_hkx_xml)", source)
        self.assertIn("archive_hkx_edit_button.clicked.connect(self._edit_current_archive_hkx)", source)
        self.assertIn("archive_hkx_placement_button.clicked.connect(self._open_current_archive_hkx_placement)", source)
        self.assertIn("archive_hkx_corpus_button.clicked.connect(self._export_hkx_converter_corpus_report)", source)
        self.assertNotIn('self.archive_texture_edit_hkx_button = QPushButton("Edit Row HKX...")', source)
        self.assertNotIn("archive_texture_edit_hkx_button.clicked.connect(self._edit_selected_archive_hkx_reference)", source)
        self.assertIn("archive_texture_refs_tree.customContextMenuRequested.connect", source)
        self.assertIn("def _show_archive_texture_reference_context_menu", source)
        self.assertIn('_add_section("physics", "Physics / HKX")', source)
        self.assertIn('"Edit HKX..."', source)
        self.assertIn("def _edit_selected_archive_hkx_reference", source)
        self.assertIn('def _edit_archive_hkx_entry(self, entry: ArchiveEntry, *, initial_section: str = "")', source)
        self.assertIn("def _edit_archive_hkx_entry_when_idle", source)
        self.assertIn("def _archive_hkx_placement_candidates_for_entry", source)
        placement_candidates_start = source.index("def _archive_hkx_placement_candidates_for_entry")
        placement_candidates_body = source[
            placement_candidates_start : source.index("def _current_archive_hkx_placement_candidates", placement_candidates_start)
        ]
        self.assertIn("if not isinstance(entry, ArchiveEntry):", placement_candidates_body)
        self.assertNotIn("archive_preview_showing_loose", placement_candidates_body)
        self.assertIn("def _choose_archive_hkx_placement_candidate", source)
        self.assertIn("def _open_archive_hkx_placement_for_entry", source)
        self.assertIn("def _open_current_archive_hkx_placement", source)
        self.assertIn('str(current_entry.extension or "").lower() not in {".hkx", ".hkt"}', source)
        self.assertIn('str(single_selected_entry.extension or "").lower() in {".hkx", ".hkt"}', source)
        self.assertIn("edit_hkx_button = QPushButton(\"Edit HKX...\")", source)
        self.assertIn("_open_hkx_editor_from_reference_preview", source)
        self.assertIn("pending_hkx_editor_entry", source)
        self.assertIn("self._edit_archive_hkx_entry_when_idle(current_entry)", source)
        self.assertIn("build_hkx_editable_geometry_xml(", source)
        self.assertIn("read_file_bytes_cancellable(source_path, stop_event=stop_event)", source)
        self.assertIn("task_accepts_cancel=True", source)
        self.assertIn("build_hkx_havok_xml_view_xml", source)
        self.assertIn('QPushButton("Write Loose Mod...")', source)
        self.assertIn("_make_archive_action_menu_button", source)
        self.assertIn("_make_sectioned_archive_action_menu_button", source)
        self.assertIn('self.archive_export_menu_button = _make_archive_action_menu_button', source)
        self.assertIn('self.archive_import_menu_button = _make_archive_action_menu_button', source)
        self.assertNotIn('self.archive_hkx_menu_button = _make_archive_action_menu_button', source)
        self.assertIn('self.archive_tools_menu_button = _make_sectioned_archive_action_menu_button', source)
        self.assertIn('QPushButton("Preview Settings")', source)
        self.assertIn("archive_context_menu_icons", source)
        self.assertIn('"View + Inspect"', source)
        self.assertIn('"Physics / HKX"', source)
        self.assertIn('"Maintenance"', source)
        self.assertIn("archive_view_controls_layout = QHBoxLayout()", source)
        self.assertIn("self.archive_preview_zoom_value.setFrameShape(QFrame.StyledPanel)", source)
        self.assertIn("archive_model_actions_layout = QHBoxLayout()", source)
        self.assertIn('"Export Havok XML View"', source)
        self.assertIn('"Edit Selected HKX"', source)
        self.assertIn('("Edit HKX", self.archive_hkx_placement_button)', source)
        self.assertNotIn('("Placement", self.archive_hkx_placement_button)', source)
        self.assertIn('"Scan HKX Corpus"', source)
        self.assertIn("def _archive_action_menu_text(", source)
        self.assertIn('(unavailable)', source)
        self.assertIn("_sync_archive_model_action_menu_buttons", source)
        self.assertIn('tab_widget.addTab(_state.overview_page, "Modding Workspace")', source)
        self.assertIn('section_nav_list = _state.QListWidget()', source)
        self.assertIn('section_nav_list.currentRowChanged.connect(_state._set_hkx_editor_section)', source)
        self.assertIn('browser_advanced_toggle = _state.QCheckBox("Show decoded row browser")', source)
        self.assertIn("browser_advanced_panel.setVisible(False)", source)
        self.assertIn('browser_advanced_toggle.toggled.connect(_state._set_browser_advanced_visible)', source)
        self.assertIn('workflow_guide_tree = _state.QTreeWidget()', source)
        self.assertIn('modding_workspace_tree = _state.QTreeWidget()', source)
        self.assertIn("workspace_task_combo.addItem(\"Collision Size\"", source)
        self.assertIn("workspace_task_combo.addItem(\"Body Transform\"", source)
        self.assertIn("workspace_task_combo.addItem(\"Joint Strength\"", source)
        self.assertIn("workspace_task_combo.addItem(\"Damping / Motion\"", source)
        self.assertIn("workspace_task_combo.addItem(\"Material / Friction\"", source)
        self.assertIn("workspace_task_combo.addItem(\"Mesh Winding\"", source)
        self.assertIn("workspace_task_combo.addItem(\"Inspect Only\"", source)
        self.assertIn('"Meaning",', source)
        self.assertIn('"Import safety",', source)
        self.assertIn('"Linked by",', source)
        self.assertIn("Import-safe", source)
        self.assertIn("Read-only candidate", source)
        self.assertIn("Structural blocked", source)
        self.assertIn("Fixed numeric", source)
        self.assertIn("Fixup-backed", source)
        self.assertIn("Owner-array", source)
        self.assertIn("Context only", source)
        self.assertIn('modding_readiness_label = _state.QLabel', source)
        self.assertIn("hkxModdingReadiness", source)
        self.assertIn("externalToolReferences", source)
        self.assertIn('"Area", "Useful Values", "Safe", "Context", "Risk", "Meaning"', source)
        self.assertIn('workflow_detail_text = _state.QPlainTextEdit()', source)
        self.assertIn("WORKFLOW_GUIDES", source)
        self.assertIn('"Collision Size"', source)
        self.assertIn('"Joint Strength"', source)
        self.assertIn('"Material / Friction"', source)
        self.assertIn("_populate_workflow_guide", source)
        self.assertIn("_update_workflow_detail", source)
        self.assertIn("_show_selected_workflow_values", source)
        self.assertIn("_show_selected_workflow_connections", source)
        self.assertIn("_show_selected_workflow_safe_catalog", source)
        self.assertIn('QPushButton("Filter Values")', source)
        self.assertIn('QPushButton("Show Relationships")', source)
        self.assertIn('QPushButton("Safe Rows Only")', source)
        self.assertIn("Safe rows are importable fixed-size CDMW patch targets", source)
        self.assertIn("Counts are evidence, not certainty.", source)
        self.assertIn("workflow_guide_tree.currentItemChanged.connect", source)
        self.assertIn("workflow_guide_tree.itemDoubleClicked.connect", source)
        self.assertIn('tab_widget.addTab(_state.tuning_page, "Patchable Values")', source)
        self.assertIn('tab_widget.addTab(_state.collision_page, "Collision Shapes")', source)
        self.assertIn('tab_widget.addTab(_state.object_layout_page, "Object Layout")', source)
        self.assertIn('tab_widget.addTab(_state.context_page, "Context Hints")', source)
        self.assertIn('tab_widget.addTab(_state.body_summary_page, "Body Summary")', source)
        self.assertIn('tab_widget.addTab(_state.constraint_summary_page, "Constraint Summary")', source)
        self.assertIn('tab_widget.addTab(_state.editable_catalog_page, "Patchable Catalog")', source)
        self.assertIn('tab_widget.addTab(_state.byte_map_page, "Byte Map")', source)
        self.assertIn('tab_widget.addTab(_state.connected_page, "Connected Physics")', source)
        self.assertIn('tab_widget.addTab(_state.decoder_page, "Decoder Evidence")', source)
        self.assertIn('placement_tab_index = _state.tab_widget.addTab(_state.placement_page, "Placement (Disabled - WIP)")', source)
        self.assertIn('tab_widget.setTabToolTip(_state.placement_tab_index, "Disabled - WIP. Placement swap/package flow is paused.")', source)
        self.assertIn('tab_widget.setTabEnabled(_state.placement_tab_index, False)', source)
        self.assertIn("placement_page.setEnabled(False)", source)
        self.assertIn('self._edit_archive_hkx_entry(selected, initial_section="Placement")', source)
        self.assertIn('requested_initial_section = str(_state.initial_section', source)
        self.assertIn('tab_widget.tabText(_state.section_index).strip().casefold() == _state.requested_initial_section', source)
        self.assertIn('tab_widget.addTab(_state.xml_page, "XML / Raw")', source)
        self.assertIn('workspace_splitter.addWidget(_state.hkx_preview_panel)', source)
        self.assertIn("hkx_preview_panel.setVisible(False)", source)
        self.assertIn('QPushButton("Edit Selected Value...")', source)
        self.assertIn('QCheckBox("Patchable only")', source)
        self.assertIn('tuning_tree.setEditTriggers(_state.QAbstractItemView.NoEditTriggers)', source)
        self.assertIn('tuning_filter_edit.setPlaceholderText("Filter tuning rows")', source)
        self.assertIn("_apply_tuning_filter", source)
        self.assertIn('tuning_filter_edit.textChanged.connect(_state._apply_tuning_filter)', source)
        self.assertIn("_edit_selected_tuning_value", source)
        self.assertIn("_edit_tuning_value_from_cell", source)
        self.assertIn('tuning_tree.itemDoubleClicked.connect(_state._edit_tuning_value_from_cell)', source)
        self.assertIn("_edit_selected_tuning_value()", source)
        self.assertIn('tuning_editable_only_checkbox.toggled.connect(_state._populate_tuning_tree)', source)
        self.assertIn("Read-only descriptor context", source)
        self.assertIn("Patchable value", source)
        self.assertIn('tuning_guidance_text = _state.QPlainTextEdit()', source)
        self.assertIn("_update_tuning_guidance", source)
        self.assertIn("_update_comparison_text_from_item", source)
        self.assertIn("tuning_tree.currentItemChanged.connect(", source)
        self.assertIn("plain_language_effect", source)
        self.assertIn("safe_edit_hint", source)
        self.assertIn("edit_risk", source)
        self.assertIn("Plain-language effect", source)
        self.assertIn("If increased", source)
        self.assertIn("If decreased", source)
        self.assertIn("Safe edit", source)
        self.assertIn("Edit risk", source)
        self.assertIn("Value constraints", source)
        self.assertIn("Edit note", source)
        self.assertIn("math.isfinite(parsed_value)", source)
        self.assertIn("HKX Views", source)
        self.assertIn('hkx_browser_tree = _state.QTreeWidget()', source)
        self.assertIn('browser_filter_edit.setPlaceholderText("Filter decoded rows")', source)
        self.assertIn('browser_follow_selection_checkbox = _state.QCheckBox("Follow selection")', source)
        self.assertIn('browser_follow_preview_checkbox = _state.QCheckBox("Follow 3D")', source)
        self.assertIn('browser_editable_only_checkbox = _state.QCheckBox("Patchable only")', source)
        self.assertIn('browser_preview_linked_checkbox = _state.QCheckBox("3D-linked rows")', source)
        self.assertIn('browser_decoded_only_checkbox = _state.QCheckBox("Decoded/context only")', source)
        self.assertIn('browser_raw_preserved_checkbox = _state.QCheckBox("Raw/unknown only")', source)
        self.assertIn("_style_hkx_tree_values", source)
        self.assertIn("_hkx_status_display", source)
        self.assertIn("Partially decoded", source)
        self.assertIn("Edit only rows marked Patchable", source)
        self.assertIn('browser_summary_label = _state.QLabel', source)
        self.assertIn("Focused views first. Advanced decoded rows are hidden below.", source)
        self.assertIn("hkClass metadata", source)
        self.assertIn("_browser_item_matches_filters", source)
        self.assertIn("_apply_hkx_browser_filter", source)
        self.assertIn('browser_filter_edit.textChanged.connect(_state._apply_hkx_browser_filter)', source)
        self.assertIn('browser_preview_linked_checkbox.toggled.connect(_state._apply_hkx_browser_filter)', source)
        self.assertIn("CDMW HKX compatibility", source)
        self.assertIn("Editing guide:", source)
        self.assertIn("safeFirstEdits", source)
        self.assertIn("avoidUntilDecoded", source)
        self.assertIn("Record status counts:", source)
        self.assertIn("Decode gaps:", source)
        self.assertIn("Blue values are patchable. Grey/context and yellow/red rows are evidence only.", source)
        self.assertIn('overview_report_toggle = _state.QCheckBox("Show technical details")', source)
        self.assertIn("workflow_guide_label.setMaximumHeight(36)", source)
        self.assertIn('overview_workspace_tabs = _state.QTabWidget()', source)
        self.assertIn('overview_workspace_tabs.addTab(_state.workspace_values_page, "Values")', source)
        self.assertIn('overview_workspace_tabs.addTab(_state.workflow_summary_page, "Readable Areas")', source)
        self.assertIn('overview_workspace_tabs.addTab(_state.overview_report_page, "Technical Details")', source)
        self.assertIn('workflow_guide_tree.setSizePolicy(_state.QSizePolicy.Policy.Expanding, _state.QSizePolicy.Policy.Expanding)', source)
        self.assertIn('overview_filler.setSizePolicy(_state.QSizePolicy.Policy.Expanding, _state.QSizePolicy.Policy.Expanding)', source)
        self.assertIn("def _set_browser_advanced_visible(visible: bool) -> None:", source)
        self.assertIn("section_nav_list.setVisible(not bool(visible))", source)
        self.assertIn("def _set_overview_report_visible(visible: bool) -> None:", source)
        self.assertIn('overview_report_toggle.toggled.connect(_state._set_overview_report_visible)', source)
        self.assertIn('workflow_show_guide_button = _state.QPushButton("Technical Details")', source)
        self.assertIn('browser_follow_preview_checkbox.setChecked(False)', source)
        self.assertIn("Schema target coverage", source)
        self.assertIn("Top unknown schema areas", source)
        self.assertIn("record reference edges", source)
        self.assertIn("HKX XML parity and PTCH proof", source)
        self.assertIn("Decoder readiness", source)
        self.assertIn("representative corpus needed: object_hkx", source)
        self.assertIn('section_combo = _state.QComboBox()', source)
        self.assertIn("section_combo.setVisible(False)", source)
        self.assertIn('section_current_label = _state.QLabel("Modding Workspace")', source)
        self.assertIn("section_combo.setMinimumContentsLength(24)", source)
        self.assertIn("section_combo.setMinimumWidth(280)", source)
        self.assertIn('section_advanced_views_toggle = _state.QCheckBox("Show advanced views")', source)
        self.assertIn("PRIMARY_HKX_SECTION_TITLES", source)
        self.assertIn("_refresh_section_nav_visibility", source)
        self.assertIn("_ensure_section_nav_visible", source)
        self.assertIn("tab_widget.tabBar().hide()", source)
        self.assertIn('preview_toggle_button = _state.QPushButton("Show 3D")', source)
        self.assertIn('preview_toggle_button.setText("Hide 3D" if visible else "Show 3D")', source)
        self.assertIn('hkx_preview_title = _state.QLabel("Embedded 3D Preview")', source)
        self.assertIn('hkx_preview_refresh_button = _state.QPushButton("Use Existing Preview")', source)
        self.assertIn("hkx_preview_refresh_button.setVisible(False)", source)
        self.assertIn('hkx_preview_skeleton_checkbox = _state.QCheckBox("Show skeleton context")', source)
        self.assertIn("hkx_preview_skeleton_checkbox.setVisible(False)", source)
        self.assertIn("hkx_preview_skeleton_checkbox.setVisible(bone_count > 0 and skeleton_link_count > 0)", source)
        self.assertNotIn('hkx_preview_placement_button = QPushButton("Placement")', source)
        self.assertIn("Disabled - WIP. Prefab/socket placement workflow is paused here", source)
        self.assertIn('placement_swap_title = _state.QLabel("Placement Swap (Disabled - WIP)")', source)
        self.assertIn('placement_swap_steps = _state.QTreeWidget()', source)
        self.assertIn("Disabled - WIP. Placement swap/package flow is paused", source)
        self.assertIn('placement_swap_copy_button = _state.QPushButton("Choose Placement Source (Disabled - WIP)")', source)
        self.assertIn("placement_swap_copy_button.setEnabled(False)", source)
        self.assertNotIn('self.archive_bulk_placement_swap_button = QPushButton("Bulk Placement Swap...")', source)
        self.assertIn("def _selected_archive_bulk_placement_targets", source)
        self.assertIn("def _open_archive_bulk_attachment_placement_from_selection", source)
        self.assertIn("def _open_archive_bulk_attachment_placement_dialog", source)
        self.assertNotIn("Bulk Placement Swap From Selection", source)
        self.assertNotIn("Each selected row is a target that changes", source)
        self.assertNotIn("Select two or more placement-capable rows first", source)
        self.assertIn("Unavailable rows are greyed out; hover a menu row for the reason.", source)
        self.assertIn("Build One Mod Folder", source)
        self.assertIn("Weapon Placement Batch pair", source)
        self.assertIn("Build writes one combined loose mod folder using the same package rows as each single placement swap", source)
        self.assertIn('placement_context_tabs = _state.QTabWidget()', source)
        self.assertIn('placement_socket_tree = _state.QTreeWidget()', source)
        self.assertIn('placement_related_tree = _state.QTreeWidget()', source)
        self.assertIn('placement_context_tabs.addTab(_state.placement_socket_page, "Socket Details")', source)
        self.assertIn('placement_context_tabs.addTab(_state.placement_related_tree, "Related Files")', source)
        self.assertNotIn('placement_copy_button = QPushButton("Copy Placement From Weapon...")', source)
        self.assertIn('placement_edit_socket_button = _state.QPushButton("Edit Socket Values...")', source)
        self.assertIn("This opened asset is the target that changes.", source)
        self.assertIn("Use Choose Placement Source to compare actual socket/prefab values", source)
        self.assertIn("def _open_archive_attachment_donor_picker_dialog", source)
        self.assertIn("Search uses the already-built Archive Browser indexes", source)
        self.assertIn("donor_search_progress = QProgressBar()", source)
        self.assertIn("search_step_timer = QTimer(picker)", source)
        self.assertIn("def _continue_index_search() -> None:", source)
        self.assertIn('search_button.setText("Searching..." if active else "Search Index")', source)
        self.assertIn('item_finder_button = QPushButton("Pick From Item Finder...")', source)
        self.assertIn("def _open_item_finder_donor_picker() -> None:", source)
        self.assertIn('finder.setWindowTitle("Item Finder - Choose Placement Source")', source)
        self.assertIn('"Item Finder visual pick"', source)
        self.assertIn("placement_source_preview_widget = QLabel", source)
        self.assertIn("Source Model Preview", source)
        self.assertIn("Static geometry thumbnail only in this picker", source)
        self.assertIn("def render_static_model_preview_pixmap", source)
        self.assertIn('"static_preview": True', source)
        self.assertIn("live texture uploads are skipped here", source)
        self.assertIn("attach_preview_images=False", source)
        self.assertIn('"placement_source_preview_start"', source)
        self.assertIn('"placement_source_preview_applied"', source)
        self.assertIn("def _placement_source_preview_entry", source)
        self.assertIn("_attachment_visual_model_entry(candidate, graph)", source)
        self.assertIn("update_source_preview, close_source_preview = _make_placement_source_preview_controller", source)
        self.assertIn("tree.currentItemChanged.connect(_handle_source_picker_selection_changed)", source)
        self.assertIn("close_source_preview()", source)
        self.assertNotIn("close_source_preview(wait=True)", source)
        self.assertIn("finder_source_detail = QLabel", source)
        self.assertIn("Candidate Source", source)
        self.assertIn("3D preview is skipped in this nested picker", source)
        self.assertIn('"placement_item_finder_open"', source)
        self.assertIn('"placement_item_finder_candidates_resolved"', source)
        self.assertNotIn("finder_source_preview_widget = NativePreviewPanel", source)
        self.assertNotIn("update_finder_source_preview, close_finder_source_preview", source)
        self.assertNotIn("close_finder_source_preview(wait=True)", source)
        self.assertIn('use_recommended_button = QPushButton("Use Recommended Source")', source)
        self.assertIn("finder_icon_timer = QTimer(finder)", source)
        self.assertIn("def _queue_item_finder_donor_icons_for_visible_rows() -> None:", source)
        self.assertIn("QTimer.singleShot(140, _queue_item_finder_donor_icons_for_visible_rows)", source)
        self.assertNotIn("def _first_item_finder_donor_icon_rows(", source)
        self.assertNotIn("self._warm_item_finder_icon_rows_before_exec(", source)
        self.assertIn(
            "self._cached_archive_asset_catalog_inventory_icon_pixmap(\n"
            "                        row,\n"
            "                        78,\n"
            "                        allow_sync_prepare=False,\n"
            "                    )",
            source,
        )
        self.assertIn('item.setData(Qt.UserRole + 1, "thumb_loaded")', source)
        self.assertIn('loose_folder_button = QPushButton("Add Loose Donor Folder...")', source)
        self.assertIn("def _collect_indexed_candidates", source)
        self.assertIn("Item Finder cache", source)
        self.assertIn("Basename index", source)
        self.assertIn("Current Archive Browser results", source)
        self.assertIn("def _map_loose_file_to_archive_entries", source)
        self.assertNotIn("scan_timer = QTimer(picker)", source)
        self.assertIn("max_results = 600", source)
        self.assertIn('placement_related_button = _state.QPushButton("Related Files")', source)
        self.assertIn("def _refresh_inline_socket_details() -> None:", source)
        self.assertIn("def _refresh_inline_swap_summary() -> None:", source)
        self.assertIn("_refresh_inline_socket_details()", source)
        self.assertIn("_refresh_inline_swap_summary()", source)
        self.assertIn("def _attachment_family_skeleton_paths(", source)
        self.assertIn('"Family skeleton" if skeleton_paths else "Skeleton"', source)
        self.assertIn("resolved from the asset family skeleton/rig companions", source)
        self.assertIn('placement_context_tabs.setCurrentWidget(_state.placement_related_tree)', source)
        self.assertIn('compare_group = QGroupBox("Socket Value Compare")', source)
        self.assertIn('target_socket_button = QPushButton("Open Target Socket XML")', source)
        self.assertIn('donor_socket_button = QPushButton("Open Source Socket XML")', source)
        self.assertIn("manual socket XML mix", source)
        self.assertNotIn("placement_visual_preview = NativePreviewPanel", source)
        self.assertNotIn("placement_candidate_socket_combo", source)
        self.assertNotIn("target_proxy_model", source)
        self.assertNotIn("def _current_inline_placement_proxy_model() -> Optional[ModelPreviewData]:", source)
        self.assertNotIn("Preview model: embedded 3D preview proxy", source)
        self.assertNotIn("QTimer.singleShot(0, _refresh_inline_placement_preview)", source)
        self.assertIn("def _build_attachment_socket_only_preview_model", source)
        self.assertIn("def _attachment_visual_segment_mesh", source)
        self.assertIn("skeleton bone {child_key}", source)
        self.assertIn("Socket-only placement preview", source)
        self.assertIn("Held/sheathed placement comes from prefab/socket evidence.", source)
        self.assertIn("showing them would imply held/sheathed placement that HKX alone does not provide", source)
        self.assertIn("def hkx_preview_skeleton_link_count(preview_model: object) -> int:", source)
        self.assertIn("hkx_preview_counts as _hkx_preview_counts", source)
        self.assertIn("Placement workspace has", source)
        self.assertIn("No skeleton context recovered.", source)
        self.assertIn('picker_filter_timer = _state.QTimer(picker)', source)
        self.assertIn("picker_filter_timer.setInterval(320)", source)
        self.assertIn("picker_filter.textChanged.connect(lambda _text: _schedule_picker_filter())", source)
        self.assertIn("picker_filter.returnPressed.connect(lambda: _populate_picker(force=True))", source)
        self.assertIn('picker_filter_apply_button = _state.QPushButton("Apply")', source)
        self.assertIn('picker_candidate_cache = tuple(_state._hkx_related_model_entries())', source)
        self.assertIn("Type at least 2 characters", source)
        self.assertIn("hkx_preview_panel.setVisible(False)", source)
        self.assertIn("_set_hkx_preview_panel_visible", source)
        self.assertIn("preview_toggle_button.toggled.connect", source)
        self.assertIn("_set_hkx_editor_section_title", source)
        self.assertIn("_set_hkx_editor_section", source)
        self.assertIn("_sync_browser_action_buttons", source)
        self.assertIn("_show_preview_overlay_target_in_hkx_editor", source)
        self.assertIn('physics_overlay_target_selected.connect(_state._show_preview_overlay_target_in_hkx_editor)', source)
        self.assertIn('archive_preview_original_settings = _state.self.archive_model_preview.render_settings()', source)
        self.assertIn('if preview is _state.self.archive_model_preview:', source)
        self.assertIn('self.archive_model_preview.set_render_settings(_state.archive_preview_original_settings)', source)
        self.assertIn('hkx_link_preview_widget = _state.NativePreviewPanel', source)
        self.assertIn("_refresh_hkx_link_preview_model", source)
        self.assertIn("_highlight_browser_data_in_preview", source)
        self.assertIn("browser_follow_preview_checkbox.toggled.connect", source)
        self.assertIn("_best_hkx_browser_item_for_overlay", source)
        self.assertIn("_make_hkx_browser_item_visible", source)
        self.assertIn("read_only: bool = False", source)
        self.assertIn("read-only preview-linked context", source)
        self.assertIn("Read-only decoded HKX row with a 3D preview target.", source)
        self.assertIn("Patchable fixed-size HKX value.", source)
        self.assertIn('QPushButton("Open Owning Editor")', source)
        self.assertIn('QPushButton("Open XML")', source)
        self.assertIn('QPushButton("Show in 3D")', source)
        self.assertIn('connected_tree = _state.QTreeWidget()', source)
        self.assertIn('connected_target_filter_edit.setPlaceholderText("Filter connected physics")', source)
        self.assertIn('QPushButton("Open Linked Value")', source)
        self.assertIn('QPushButton("Highlight 3D")', source)
        self.assertIn('connected_workflow_combo.addItem("Capsule size"', source)
        self.assertIn('connected_workflow_combo.addItem("Joint stiffness"', source)
        self.assertIn('connected_workflow_combo.addItem("Damping"', source)
        self.assertIn('connected_workflow_combo.addItem("Ragdoll body inspection"', source)
        self.assertIn('connected_workflow_combo.addItem("Hair / cloth labels"', source)
        self.assertIn('connected_workflow_combo.addItem("Body part labels"', source)
        self.assertIn('connected_risk_combo.addItem("Safe / Patchable"', source)
        self.assertIn('connected_detail_text = _state.QPlainTextEdit()', source)
        self.assertIn("Value / Before -> After", source)
        self.assertIn("_resolve_preview_viewer_id_for_data", source)
        self.assertIn("_previewable_viewer_id", source)
        self.assertIn("_available_hkx_preview_target_ids", source)
        self.assertIn("autoload_preview=False", source)
        self.assertIn("It does not open the embedded 3D Preview pane by itself.", source)
        self.assertIn("no matching 3D physics overlay is loaded", source)
        self.assertIn("resolved {viewer_id", source)
        self.assertIn("Context Only", source)
        self.assertIn("Fixup-backed / Exact Links", source)
        self.assertIn("Owner-array Links", source)
        self.assertIn("Likely Links", source)
        self.assertIn("Raw Decoder Evidence", source)
        self.assertIn("_state.self._ui_evidence_label(_frame.link_evidence)", source)
        self.assertIn('decoder_tree = _state.QTreeWidget()', source)
        self.assertIn("Reference Semantics", source)
        self.assertIn("Class Decode Status", source)
        self.assertIn("Fixup-backed Fields", source)
        self.assertIn("Fixup / PTCH Semantics V2", source)
        self.assertIn("Semantic Model V1", source)
        self.assertIn("Native Edit Candidate Map", source)
        self.assertIn("Semantic Writer Gate", source)
        self.assertIn("Real hkClass Metadata V2", source)
        self.assertIn("fixupSemanticsV2", source)
        self.assertIn("semanticModelV1", source)
        self.assertIn("editCandidateMapV1", source)
        self.assertIn("semanticWriterGateV1", source)
        self.assertIn("realHkclassMetadataV2", source)
        self.assertIn("_populate_decoder_evidence_tree", source)
        self.assertIn("_update_decoder_evidence_detail", source)
        self.assertIn("decoderEvidence", source)
        self.assertIn("Patchable Values", source)
        self.assertIn("link_evidence", source)
        self.assertIn("No exact visual link", source)
        self.assertIn("3D link recovered, no model loaded", source)
        self.assertIn("Loaded model lacks this target", source)
        self.assertIn("Exact 3D target selected", source)
        self.assertIn("Nearest spatial fallback only", source)
        self.assertIn("connected_hkx_char_string", source)
        self.assertIn("No exact visual link for this row", source)
        self.assertIn("_select_best_connected_row_for_target", source)
        self.assertIn("_update_connected_detail_text", source)
        self.assertIn("Identity path", source)
        self.assertIn("_frame.row_element.get('display_label')", source)
        self.assertIn("_frame.row_element.get('context_label')", source)
        self.assertIn('("Body", "body_name")', source)
        self.assertIn('("Socket", "socket_name")', source)
        self.assertIn('("Material", "physics_material_name")', source)
        self.assertIn('("Identity path", "identity_path")', source)
        self.assertIn("hex_absolute_data_offset", source)
        self.assertIn("_value_with_dirty_preview", source)
        self.assertIn("_populate_connected_physics_tree", source)
        self.assertIn("_apply_connected_physics_filter", source)
        self.assertIn("_focus_selected_connected_physics", source)
        self.assertIn("_highlight_selected_connected_physics", source)
        self.assertIn("_set_connected_target_filter", source)
        self.assertIn('connected_target_filter_edit.textChanged.connect(_state._apply_connected_physics_filter)', source)
        self.assertIn("connected_tree.itemDoubleClicked.connect", source)
        self.assertIn("select_physics_overlay_target", (ROOT / "cdmw" / "ui" / "native_preview_panel.py").read_text(encoding="utf-8"))
        self.assertIn("_populate_hkx_browser_tree", source)
        self.assertIn("editorModel", source)
        self.assertIn("relationshipGraph", source)
        self.assertIn('comparison_text = _state.QPlainTextEdit()', source)
        self.assertIn("QDoubleSpinBox()", source)
        self.assertIn("_prompt_hkx_numeric_value", source)
        self.assertIn("_confirm_hkx_edit_risk", source)
        self.assertIn("_edit_selected_collision_value", source)
        self.assertIn('collision_tree.setEditTriggers(_state.QAbstractItemView.NoEditTriggers)', source)
        self.assertIn('QPushButton("Reset Selected Value")', source)
        self.assertIn('QPushButton("Reset All Changes")', source)
        self.assertIn('QPushButton("Preview HKX Mod...")', source)
        self.assertIn("def _hkx_mod_package_preview_text() -> str:", source)
        self.assertIn("def _hkx_mod_package_change_rows()", source)
        self.assertIn("def _byte_patch_entry_for_dirty_key", source)
        self.assertIn("HKX Mod Package Preview", source)
        self.assertIn('"task": str(entry_element.get("task_label")', source)
        self.assertIn("f\"{row['label']} | task={row['task']", source)
        self.assertIn("import_safety", source)
        self.assertIn("gate_status", source)
        self.assertIn("structural_kind", source)
        self.assertIn("absolute_offset_hex", source)
        self.assertIn("no approved byte patch map entry", source)
        self.assertIn("Blocked edited rows", source)
        self.assertIn("dirty_values_by_key", source)
        self.assertIn("_record_dirty_value", source)
        self.assertIn("_sync_hkx_edited_overlay_targets", source)
        self.assertIn("_dirty_overlay_viewer_ids_from_root", source)
        self.assertIn("set_physics_overlay_edited_targets", (ROOT / "cdmw" / "ui" / "native_preview_panel.py").read_text(encoding="utf-8"))
        self.assertIn("Patch target", source)
        self.assertIn('"Record", "Type", "Kind", "Offset", "Size", "Name", "Value", "Confidence", "Description"', source)
        self.assertIn('"Shape", "Field", "Row", "Component", "Value", "Confidence", "Description"', source)
        self.assertIn('collision_filter_edit.setPlaceholderText("Filter collision rows")', source)
        self.assertIn("_apply_collision_filter", source)
        self.assertIn('collision_filter_edit.textChanged.connect(_state._apply_collision_filter)', source)
        self.assertIn("_add_collision_read_only_item", source)
        self.assertIn("_frame.box_summary = _frame.shape_element.find('box_summary')", source)
        self.assertIn("read-only collision row(s)", source)
        self.assertIn("Refresh Collision Shapes From XML", source)
        self.assertIn("_populate_collision_tree", source)
        self.assertIn("_handle_collision_item_changed", source)
        self.assertIn("shape_payload", source)
        self.assertIn("mass_properties", source)
        self.assertIn("capsule_radius", source)
        self.assertIn("capsule_endpoints", source)
        self.assertIn("Mesh primitive tuple rows only allow winding/order changes", source)
        self.assertIn("_add_collision_tuple_item", source)
        self.assertIn("'mesh_primitive_tuple'", source)
        self.assertIn("Only winding/order edits are supported", source)
        self.assertIn("supportedSafeOperation", source)
        self.assertIn("hull_face_records", source)
        self.assertIn("hull_face_indices", source)
        self.assertIn("hull_edge_pairs", source)
        self.assertIn("_frame.integer_kinds = {'hull_face_record', 'hull_face_index', 'hull_edge_pair'}", source)
        self.assertIn("Refresh Object Layout From XML", source)
        self.assertIn("_populate_object_layout_tree", source)
        self.assertIn("Refresh Context Hints From XML", source)
        self.assertIn("_populate_context_hints_tree", source)
        self.assertIn("build_hkx_descriptor_hint_from_xml_text", source)
        self.assertIn("descriptorContextHints", source)
        self.assertIn("physicsMaterialContext", source)
        self.assertIn("physicsNames", source)
        self.assertIn("physicsBodySummary", source)
        self.assertIn("physicsConstraintSummary", source)
        self.assertIn("editableFieldCatalog", source)
        self.assertIn("physics_body_summary", source)
        self.assertIn("_populate_constraint_summary_tree", source)
        self.assertIn("Refresh Constraint Summary From XML", source)
        self.assertIn("Show in Patchable Values", source)
        self.assertIn("_focus_selected_constraint_slot_in_tuning", source)
        self.assertIn('constraint_summary_tree.itemDoubleClicked.connect(_state._focus_constraint_slot_from_cell)', source)
        self.assertIn("_populate_editable_catalog_tree", source)
        self.assertIn("max_catalog_rows = 2500", source)
        self.assertIn("editable_catalog_tree.setSortingEnabled(False)", source)
        self.assertIn("Use XML / Raw for the full document", source)
        self.assertIn("Refresh Patchable Catalog From XML", source)
        self.assertIn('editable_catalog_filter_edit.setPlaceholderText("Filter editable catalog")', source)
        self.assertIn("_apply_editable_catalog_filter", source)
        self.assertIn('editable_catalog_filter_edit.textChanged.connect(_state._apply_editable_catalog_filter)', source)
        self.assertIn("Show Selected Editor", source)
        self.assertIn("_focus_selected_catalog_field", source)
        self.assertIn('editable_catalog_tree.itemDoubleClicked.connect(_state._focus_catalog_field_from_cell)', source)
        self.assertIn('"Category", "Subject", "Editor", "Record", "Item", "Offset", "Name", "Value", "Effect", "Confidence", "Guidance", "Rules", "Description"', source)
        self.assertIn("effectCounts", source)
        self.assertIn("edit_guidance", source)
        self.assertIn("value_constraints", source)
        self.assertIn("suggested_edit_step", source)
        self.assertIn("bytePatchMap", source)
        self.assertIn("_populate_byte_map_tree", source)
        self.assertIn("Refresh Byte Map From XML", source)
        self.assertIn('byte_map_filter_edit.setPlaceholderText("Filter byte map")', source)
        self.assertIn('byte_map_filter_edit.textChanged.connect(_state._apply_byte_map_filter)', source)
        self.assertIn('"Category", "Subject", "Path", "Record", "Item", "Row", "Component", "Relative", "Absolute", "Type", "Description"', source)
        self.assertIn("_populate_body_summary_tree", source)
        self.assertIn("Refresh Body Summary From XML", source)
        self.assertIn("name_hint", source)
        self.assertIn("HavokShapeNameProperty", source)
        self.assertIn("_frame.body_context = _frame.root.find('./physicsBodyContext')", source)
        self.assertIn("physics_body_context", source)
        self.assertIn("shapeMatches", source)
        self.assertIn("_collision_context_by_shape_index", source)
        self.assertIn("'body_context'", source)
        self.assertIn("./body_contexts/body_context", source)
        self.assertIn("Descriptor body/socket/material context correlated with this decoded HKX shape.", source)
        self.assertIn("_frame.policy = _frame.root.find('reimportPolicy')", source)
        self.assertIn("rejected structural changes", source)
        self.assertIn('"Confidence"', source)
        self.assertIn('search_edit.setPlaceholderText("Search XML")', source)
        self.assertIn('wrap_checkbox = _state.QCheckBox("Wrap")', source)
        self.assertIn("HkxXmlHighlighter", source + "\n" + ARCHIVE_HKX_XML_HIGHLIGHTER.read_text(encoding="utf-8"))
        self.assertIn('line_numbers = _state.QPlainTextEdit()', source)
        self.assertIn("build_hkx_editable_geometry_json", source)
        self.assertIn("build_hkx_converter_corpus_json", source)
        self.assertIn("build_hkx_converter_corpus_csv", source)
        self.assertIn("Native Rust preflight", source)
        self.assertIn("native_fast_scan", source)
        self.assertIn("representative_real_hkx_corpus_plan", source)
        self.assertIn("Representative real HKX corpus", source)
        self.assertIn("PTCH/fixup proof", source)
        self.assertIn("Hard decoder corpus proof", source)
        self.assertIn("Corpus evidence", source)
        self.assertIn("CDMW_HKX_CORPUS_DETAIL_LIMIT", source)
        self.assertIn("detail_scan_truncated", source)
        self.assertIn("apply_hkx_editable_geometry_json", source)
        self.assertIn("build_hkx_editable_geometry_xml", source)
        self.assertIn("apply_hkx_editable_geometry_xml", source)
        self.assertIn("export_archive_payloads_to_mod_ready_loose", source)
        self.assertIn("HKX Loose Mod Metadata", source)
        self.assertIn("The installed game archives were not modified.", source)

    def test_hkx_placement_swap_non_sword_safety_and_experimental_full_swap_are_present(self) -> None:
        source = "\n".join(
            (
                MAIN_WINDOW.read_text(encoding="utf-8"),
                _hkx_action_sources(),
                ARCHIVE_ATTACHMENT_BATCH.read_text(encoding="utf-8"),
                ARCHIVE_ATTACHMENT_PLACEMENT_DIFF_DIALOG.read_text(encoding="utf-8"),
                ARCHIVE_ATTACHMENT_PACKAGE.read_text(encoding="utf-8"),
                ARCHIVE_ATTACHMENT_PLAN.read_text(encoding="utf-8"),
            )
        )

        self.assertIn("def _attachment_package_weapon_subclass_tokens", source)
        self.assertIn("def _attachment_package_placement_compatibility", source)
        self.assertIn("Known compatible", source)
        self.assertIn("Cross-category risky", source)
        self.assertIn("Unknown placement compatibility", source)
        self.assertIn("warhammer", source)
        self.assertIn("mace", source)
        self.assertIn("axe", source)
        self.assertIn("legacy_raw_prefab_copy: bool = False", source)
        self.assertIn("experimental_copy_source_hkx: bool = False", source)
        self.assertIn('QCheckBox("Legacy raw prefab copy (risky)")', source)
        self.assertIn('QCheckBox("Replacement-only: copy source HKX/physics")', source)
        self.assertIn('QCheckBox("Legacy raw prefab copy for batch (risky)")', source)
        self.assertIn("Copy source PAC/model bytes (experimental)", source)
        self.assertIn("Copy source material sidecar bytes (experimental)", source)
        self.assertIn("Replacement-only: copy source HKX/HKT physics bytes", source)
        self.assertIn("Preserve target HKX/HKT physics bytes", source)
        self.assertIn("Source HKX/physics not copied by default.", source)
        self.assertIn("Replacement-only source HKX/physics copied", source)
        self.assertIn("Target-only mode: source model/material/textures/icon/prefab bytes are not copied.", source)
        self.assertIn("Placement diagnostics:", source)
        self.assertIn("_placement_swap_package_info_with_diagnostics", source)
        self.assertIn("_bulk_pair_compatibility_status", source)
        self.assertIn("_bulk_pair_ready_note", source)
        self.assertIn("_rebuild_all_assigned_pairs", source)
        self.assertIn("experimental_copy_source_model=False", source)
        self.assertIn("experimental_copy_source_hkx=experimental_hkx_checkbox.isChecked()", source)

    def test_hkx_archive_preview_body_context_strings_are_present(self) -> None:
        archive_source = "\n".join(
            (
                ARCHIVE_CORE.read_text(encoding="utf-8"),
                ARCHIVE_HKX_CORE.read_text(encoding="utf-8"),
                (ROOT / "cdmw" / "core" / "archive_model_preview.py").read_text(encoding="utf-8"),
                ARCHIVE_PREVIEW_RESULT_BUILDER.read_text(encoding="utf-8"),
            )
        )
        ui_source = "\n".join(
            (
                MAIN_WINDOW.read_text(encoding="utf-8"),
                _hkx_editor_sources(),
                (ROOT / "cdmw" / "ui" / "archive_browser" / "preview_result.py").read_text(encoding="utf-8"),
            )
        )

        self.assertIn("def resolve_hkx_preview_context_model_entry", archive_source)
        self.assertIn("HKX Body + Physics preview", archive_source)
        self.assertIn("HKX is physics/collision; body mesh loaded from", archive_source)
        self.assertIn("Body + Physics", archive_source)
        self.assertIn('_state.hkx_preview_skeleton_checkbox = _state.QCheckBox("Show skeleton context")', ui_source)
        self.assertIn("hkx_link_preview_widget.set_physics_overlay_bones_visible(False)", ui_source)


if __name__ == "__main__":
    unittest.main()
