from __future__ import annotations

import unittest
from pathlib import Path


TARGET_ARCHITECTURE_PATHS = (
    "cdmw/app/bootstrap.py",
    "cdmw/app/args.py",
    "cdmw/app/cli.py",
    "cdmw/app/gui.py",
    "cdmw/app/single_instance.py",
    "cdmw/app/startup_smoke.py",
    "cdmw/app/activation.py",
    "cdmw/app/startup_splash.py",
    "cdmw/app/startup_maintenance.py",
    "cdmw/app/pyinstaller_runtime.py",
    "cdmw/app/bootstrap_reports.py",
    "cdmw/app/events.py",
    "cdmw/domain/archives/safety.py",
    "cdmw/domain/archives/filters.py",
    "cdmw/domain/textures/profiles.py",
    "cdmw/domain/textures/rules.py",
    "cdmw/domain/textures/semantics.py",
    "cdmw/domain/textures/policy.py",
    "cdmw/domain/textures/plan.py",
    "cdmw/domain/mesh/session.py",
    "cdmw/domain/mesh/validation.py",
    "cdmw/domain/library/item_icons.py",
    "cdmw/domain/library/models.py",
    "cdmw/services/service_container.py",
    "cdmw/services/archive_service.py",
    "cdmw/services/archive_mutation_service.py",
    "cdmw/services/texture_workflow_service.py",
    "cdmw/services/mesh_service.py",
    "cdmw/services/item_icon_service.py",
    "cdmw/services/model_library_service.py",
    "cdmw/services/package_service.py",
    "cdmw/services/settings_service.py",
    "cdmw/services/diagnostics_service.py",
    "cdmw/services/cache_service.py",
    "cdmw/services/filesystem_service.py",
    "cdmw/workers/results.py",
    "cdmw/workers/cancellation.py",
    "cdmw/workers/qt_worker_runner.py",
    "cdmw/workers/archive_workers.py",
    "cdmw/workers/texture_workers.py",
    "cdmw/workers/preview_workers.py",
    "cdmw/ui/shell/app_window.py",
    "cdmw/ui/shell/main_window_proxy.py",
    "cdmw/ui/shell/app_context.py",
    "cdmw/ui/shell/app_state.py",
    "cdmw/ui/shell/tab_registry.py",
    "cdmw/ui/shell/menus.py",
    "cdmw/ui/shell/settings_bridge.py",
    "cdmw/ui/shell/settings_autosave.py",
    "cdmw/ui/shell/settings_persistence.py",
    "cdmw/ui/shell/signal_wiring.py",
    "cdmw/ui/shell/startup_controller.py",
    "cdmw/ui/shell/startup_restore.py",
    "cdmw/ui/shell/support_dialog.py",
    "cdmw/ui/shell/tool_tabs.py",
    "cdmw/ui/shell/lazy_tool_tab.py",
    "cdmw/ui/shell/close_controller.py",
    "cdmw/ui/shell/about_controller.py",
    "cdmw/ui/shell/about_documentation.py",
    "cdmw/ui/shell/about_documentation_de.py",
    "cdmw/ui/shell/about_documentation_en.py",
    "cdmw/ui/shell/about_documentation_es.py",
    "cdmw/ui/shell/diagnostics_controller.py",
    "cdmw/ui/shell/responsiveness_controller.py",
    "cdmw/ui/shell/log_controller.py",
    "cdmw/ui/shell/theme_controller.py",
    "cdmw/ui/shell/icon_controller.py",
    "cdmw/ui/shell/activation_controller.py",
    "cdmw/ui/shell/window_bootstrap_state.py",
    "cdmw/ui/shell/window_runtime_state.py",
    "cdmw/ui/shell/root_layout.py",
    "cdmw/ui/archive_browser/controller.py",
    "cdmw/ui/archive_browser/model.py",
    "cdmw/ui/archive_browser/appearance_common.py",
    "cdmw/ui/archive_browser/appearance_composite.py",
    "cdmw/ui/archive_browser/appearance_swap.py",
    "cdmw/ui/archive_browser/filters.py",
    "cdmw/ui/archive_browser/files_panel.py",
    "cdmw/ui/archive_browser/filter_workers.py",
    "cdmw/ui/archive_browser/index_workers.py",
    "cdmw/ui/archive_browser/render_lifecycle.py",
    "cdmw/ui/archive_browser/scan_lifecycle.py",
    "cdmw/ui/archive_browser/sidecar_index.py",
    "cdmw/ui/archive_browser/ui_formatting.py",
    "cdmw/ui/archive_browser/preview_panel.py",
    "cdmw/ui/archive_browser/reference_export.py",
    "cdmw/ui/archive_browser/reference_preview.py",
    "cdmw/ui/archive_browser/source_picker_dialog.py",
    "cdmw/ui/archive_browser/source_mix_actions.py",
    "cdmw/ui/archive_browser/source_mix_overlay.py",
    "cdmw/ui/archive_browser/static_preview_thumbnail.py",
    "cdmw/ui/archive_browser/static_replacement_dialog.py",
    "cdmw/ui/archive_browser/static_replacement_dialog_helpers.py",
    "cdmw/ui/archive_browser/preview_details.py",
    "cdmw/ui/archive_browser/preview_layout.py",
    "cdmw/ui/archive_browser/preview_loading.py",
    "cdmw/ui/archive_browser/preview_result.py",
    "cdmw/ui/archive_browser/preview_zoom.py",
    "cdmw/ui/archive_browser/attachment_batch.py",
    "cdmw/ui/archive_browser/attachment_donor_picker_dialog.py",
    "cdmw/ui/archive_browser/attachment_donor_picker_helpers.py",
    "cdmw/ui/archive_browser/attachment_placement_diff_dialog.py",
    "cdmw/ui/archive_browser/attachment_safe_placement_dialog.py",
    "cdmw/ui/archive_browser/attachment_socket_editor.py",
    "cdmw/ui/archive_browser/attachment_visual_dialog.py",
    "cdmw/ui/archive_browser/asset_catalog.py",
    "cdmw/ui/archive_browser/asset_catalog_dialog.py",
    "cdmw/ui/archive_browser/asset_catalog_scope.py",
    "cdmw/ui/archive_browser/asset_family_layout.py",
    "cdmw/ui/archive_browser/asset_family_panel.py",
    "cdmw/ui/archive_browser/asset_family_references.py",
    "cdmw/ui/archive_browser/binary_sidecar_actions.py",
    "cdmw/ui/archive_browser/character_dependency_export.py",
    "cdmw/ui/archive_browser/controls_panel.py",
    "cdmw/ui/archive_browser/icon_pipeline.py",
    "cdmw/ui/archive_browser/hkx_document_actions.py",
    "cdmw/ui/archive_browser/hkx_editor_dialog.py",
    "cdmw/ui/archive_browser/hkx_editor_dialog_helpers.py",
    "cdmw/ui/archive_browser/hkx_xml_highlighter.py",
    "cdmw/ui/archive_browser/import_actions.py",
    "cdmw/ui/archive_browser/material_sidecar_actions.py",
    "cdmw/ui/archive_browser/material_sidecar_editor_dialog.py",
    "cdmw/ui/archive_browser/material_sidecar_editor_helpers.py",
    "cdmw/ui/archive_browser/mod_ready_export.py",
    "cdmw/ui/archive_browser/mod_package_retrofit_dialog.py",
    "cdmw/ui/archive_browser/mod_package_retrofit_view.py",
    "cdmw/ui/archive_browser/mesh_dds_preview.py",
    "cdmw/ui/archive_browser/mesh_builder_lifecycle.py",
    "cdmw/ui/archive_browser/mesh_direct_patch.py",
    "cdmw/ui/archive_browser/mesh_import_export.py",
    "cdmw/ui/archive_browser/mesh_launch_flow.py",
    "cdmw/ui/archive_browser/mesh_patch_flow.py",
    "cdmw/ui/archive_browser/mesh_swap_support.py",
    "cdmw/ui/archive_browser/mesh_swap_scope_dialog.py",
    "cdmw/ui/archive_browser/mesh_modify_original.py",
    "cdmw/ui/archive_browser/mesh_setup_helpers.py",
    "cdmw/ui/archive_browser/patch_actions.py",
    "cdmw/ui/archive_browser/actions.py",
    "cdmw/ui/archive_browser/extraction.py",
    "cdmw/ui/archive_browser/workers.py",
    "cdmw/ui/texture_workflow/setup_panel.py",
    "cdmw/ui/texture_workflow/compare_preview.py",
    "cdmw/ui/texture_workflow/dds_output_panel.py",
    "cdmw/ui/texture_workflow/editor_bridge.py",
    "cdmw/ui/texture_workflow/editor_handoff.py",
    "cdmw/ui/texture_workflow/config_collection.py",
    "cdmw/ui/texture_workflow/shell_controls.py",
    "cdmw/ui/texture_workflow/setup_overview_panel.py",
    "cdmw/ui/texture_workflow/paths_panel.py",
    "cdmw/ui/texture_workflow/settings_panel.py",
    "cdmw/ui/texture_workflow/upscale_backend_panel.py",
    "cdmw/ui/texture_workflow/workflow_profiles_panel.py",
    "cdmw/ui/texture_workflow/workflow_profiles_ui.py",
    "cdmw/ui/texture_workflow/progress_panel.py",
    "cdmw/ui/texture_workflow/compare_panel.py",
    "cdmw/ui/texture_workflow/workers.py",
    "cdmw/ui/texture_workflow/unavailable_editor.py",
    "cdmw/ui/mesh_editor/tab.py",
    "cdmw/ui/mesh_editor/session.py",
    "cdmw/ui/mesh_editor/controller.py",
    "cdmw/ui/mesh_editor/builder_host.py",
    "cdmw/ui/mesh_editor/actions.py",
    "cdmw/ui/mesh_editor/shell_bridge.py",
    "cdmw/ui/model_library/tab.py",
    "cdmw/ui/model_library/controller.py",
    "cdmw/ui/model_library/state.py",
    "cdmw/ui/model_library/workers.py",
    "cdmw/ui/item_icons/tab.py",
    "cdmw/ui/item_icons/controller.py",
    "cdmw/ui/item_icons/state.py",
    "cdmw/ui/item_icons/workers.py",
    "cdmw/ui/research/tab.py",
    "cdmw/ui/research/state.py",
    "cdmw/ui/research/analysis_state.py",
    "cdmw/ui/research/classification_review_state.py",
    "cdmw/ui/research/display_preferences_state.py",
    "cdmw/ui/research/layout_state.py",
    "cdmw/ui/research/notes_state.py",
    "cdmw/ui/research/reference_payload_state.py",
    "cdmw/ui/research/refresh_population_state.py",
    "cdmw/ui/research/texture_group_state.py",
    "cdmw/ui/research/tree_column_specs.py",
    "cdmw/ui/research/workers.py",
    "cdmw/ui/research/models.py",
    "cdmw/ui/research/archive_picker_state.py",
    "cdmw/ui/research/help_widgets.py",
    "cdmw/ui/research/preview_controls.py",
    "cdmw/ui/research/preview_state.py",
    "cdmw/ui/research/progress_helpers.py",
    "cdmw/ui/research/tree_helpers.py",
    "cdmw/ui/research/tree_population.py",
    "cdmw/ui/text_search/tab.py",
    "cdmw/ui/text_search/controller.py",
    "cdmw/ui/text_search/workers.py",
    "cdmw/ui/tools/mod_package_retrofit.py",
    "cdmw/ui/tools/mod_package_retrofit_view.py",
)

FEATURE_PACKAGE_READMES = (
    Path("cdmw/ui/archive_browser/README.md"),
    Path("cdmw/ui/texture_workflow/README.md"),
    Path("cdmw/ui/mesh_editor/README.md"),
    Path("cdmw/ui/item_icons/README.md"),
    Path("cdmw/ui/model_library/README.md"),
    Path("cdmw/ui/research/README.md"),
    Path("cdmw/ui/text_search/README.md"),
    Path("cdmw/ui/tools/README.md"),
)


class ArchitecturePublicFacadeTests(unittest.TestCase):
    def test_target_architecture_module_map_exists(self) -> None:
        missing = [path for path in TARGET_ARCHITECTURE_PATHS if not Path(path).exists()]
        self.assertEqual([], missing)

    def test_main_window_facade_exports_public_api(self) -> None:
        from cdmw.ui.main_window import MainWindow, mesh_import_mode_availability, run_gui

        self.assertTrue(callable(MainWindow))
        self.assertTrue(callable(mesh_import_mode_availability))
        self.assertTrue(callable(run_gui))

    def test_main_window_facade_does_not_import_app_window_directly(self) -> None:
        source = Path("cdmw/ui/main_window.py").read_text(encoding="utf-8")

        self.assertNotIn("cdmw.ui.shell.app_window", source)

    def test_legacy_feature_imports_still_resolve(self) -> None:
        from cdmw.ui.archive_browser_model import ArchiveBrowserModel
        from cdmw.ui.item_icons_tab import ItemIconLibraryTab
        from cdmw.ui.mesh_editor_tab import MeshEditorSessionRequest, MeshEditorTab
        from cdmw.ui.model_library_tab import ModelLibraryTab
        from cdmw.ui.research_tab import ResearchTab
        from cdmw.ui.text_search_tab import TextSearchTab

        for value in (
            ArchiveBrowserModel,
            ItemIconLibraryTab,
            MeshEditorSessionRequest,
            MeshEditorTab,
            ModelLibraryTab,
            ResearchTab,
            TextSearchTab,
        ):
            self.assertTrue(callable(value))

    def test_feature_packages_have_ownership_readmes(self) -> None:
        for path in FEATURE_PACKAGE_READMES:
            self.assertTrue(path.exists(), path)
            text = path.read_text(encoding="utf-8").strip()
            self.assertIn("Owns", text, path)


if __name__ == "__main__":
    unittest.main()
