from __future__ import annotations

import base64
import json
import zlib


# Generated by scripts/generate_window_feature_provider_members.py.
PROVIDER_PAYLOAD_SHA256 = '5c160d4c532c213bd61440aa31ba9cfbd325f43c02b1dcf43d1e5077e9537361'
PROVIDER_SOURCE_HASHES = {
    'cdmw/ui/archive_browser/action_controls.py': 'a8fd078efff1e6721a686418ccadd6e1d66a3b623be8eba87c71fc4c8f593461',
    'cdmw/ui/archive_browser/actions.py': '53e6b63e13d7e4db8fab08138137999d3e77f497dd27ef7c764e1fd9c786a09b',
    'cdmw/ui/archive_browser/appearance_common.py': '0f49be42ae614f31e074e40f8226b9434d11e06c30a44ed47f1f324ec791e934',
    'cdmw/ui/archive_browser/appearance_composite.py': '57142ee3fcb1fb7473d6453c109c06461c0d51be4e15eb6adae9c7a46a98456a',
    'cdmw/ui/archive_browser/appearance_swap.py': 'c2901b4d273a34f28e4236cf2183137d5ab7d838a7c7f3e648ad25dce156d694',
    'cdmw/ui/archive_browser/asset_catalog.py': 'ef3d8f02fd399f153c0b58354ab0c7714e0bdc9f72b8e83262af794cb5d2347b',
    'cdmw/ui/archive_browser/asset_catalog_dialog.py': '16d4a904a3fd05f1777385498861297791f79dfd24643dde7188eea89a7cf091',
    'cdmw/ui/archive_browser/asset_catalog_scope.py': 'fdec1328c4994d607a00f233c5148603e5cd09462a715a599a04574bda580646',
    'cdmw/ui/archive_browser/asset_family_dialog.py': '0e404b910cb7d6ff150bb6b28d111f4c055b10180a5fde8ec40fe34781ff90d0',
    'cdmw/ui/archive_browser/asset_family_layout.py': '048896d81b5ecac4c1f9c7b89376838da8b7bc994a3b23cacd66fe501e95b244',
    'cdmw/ui/archive_browser/asset_family_panel.py': 'd2ff0c897c7bd9350e8ae80a7e7b52f84fecabf68143e9f9f2dd86dbbcabf926',
    'cdmw/ui/archive_browser/asset_family_references.py': 'b32576b99624fba57fb9305dae1bf2717bc7e06500140fa5459e781690571535',
    'cdmw/ui/archive_browser/attachment_batch.py': '61ca538148c3c37926efc6f2bc5420e1884a1d44a177d307d2bcca7cc777ab5e',
    'cdmw/ui/archive_browser/attachment_donor_picker_dialog.py': '4a7fe842d29b93a3b107fe015b28ba65a9abad393a4b6a8cfe9fd6207bc940f2',
    'cdmw/ui/archive_browser/attachment_icons.py': 'd54502e08e0d2fd8405c172bbd5ea7b0f0eeb084ebddb4866d538da65c1a573f',
    'cdmw/ui/archive_browser/attachment_loose_files.py': 'e4bf117ecbb9e7a18ccde85f12adb540309746bc9d8d97c99964cde9ccab7b33',
    'cdmw/ui/archive_browser/attachment_package.py': '644936511446da9a1896cd8df14cac6f91f286d61298fce65e99e17a626456fd',
    'cdmw/ui/archive_browser/attachment_placement_diff_dialog.py': '84a3d3be27975e9a79ce3afe57986907bfe3d2fa70d92fabe3a799c53289e135',
    'cdmw/ui/archive_browser/attachment_plan.py': '36c0c0a2cf0963960840a91666293830acf7514c2b735371d97e7514de95acc0',
    'cdmw/ui/archive_browser/attachment_safe_placement_dialog.py': 'f90973ee4b41248475c267cd230f1423fdd5bc0468bfc2a968bf223eb2725a12',
    'cdmw/ui/archive_browser/attachment_socket_editor.py': 'fb3f13994507b6f3db09fbf575ad122131a8822f2d903bc7ed4bb03f895bdf9e',
    'cdmw/ui/archive_browser/attachment_visual_context.py': 'c95d2435a8374d4886c7ab7b09abf6d21909a864ea29697885ddd8afc75fecb2',
    'cdmw/ui/archive_browser/attachment_visual_core.py': '41789ae65b6c691b8c1399ede797f4844b2480fb1addb84a4b0ba88673b6d58b',
    'cdmw/ui/archive_browser/attachment_visual_dialog.py': 'c45c6101df63433fa73c8068ac4666fb10e7523a1c8aae80effe318e0c7c308b',
    'cdmw/ui/archive_browser/attachment_visual_geometry.py': '9d545223625fb1207889c1a93ce3d22d67007c7faba9be82a0254c4f8f8682c0',
    'cdmw/ui/archive_browser/attachment_visual_payload.py': '37b5b660ba5016dae57ae8dd2522c0f1184ed6dc8afcc180bff5fa4a12b4b1c9',
    'cdmw/ui/archive_browser/attachment_visual_preview.py': '309387a3ccdf8d8377eeaebb646f922d5199c8048096170e307623c6463af4c2',
    'cdmw/ui/archive_browser/binary_sidecar_actions.py': 'b76f8b2c0ab3f8d6c91a9fce803cde248ecc85dce3739d3d804872405e9f1640',
    'cdmw/ui/archive_browser/character_dependency_export.py': '919aefbea2f83a3cd519c6e88e9c3a9c1aa9cc4ebbe3a550816b4d8cb12406cd',
    'cdmw/ui/archive_browser/controller.py': 'b9b50a9175da811214c770170af6c00a402892a4c3bef440933c5c340aa0e580',
    'cdmw/ui/archive_browser/controls_panel.py': '84ea6c11e446153c337b23e5b62c8090e963913e3ebefb22f19f883b3a2f6ce5',
    'cdmw/ui/archive_browser/extraction.py': '11835868d94e2ff4f0599d7a466f9838b787ef83bf3042392da87a758e83aa52',
    'cdmw/ui/archive_browser/files_panel.py': '8f2f510edc3fa48bc31c37d5b1fa8918d4f1e3c52f6b4fcbe38b49e9e4aa26c6',
    'cdmw/ui/archive_browser/filter_controls.py': '6d0acfa75d48dc1560a4aa954e69a59ff89db0912505b9088dc6ff02bba4282f',
    'cdmw/ui/archive_browser/filter_workers.py': 'a69590c7b83f10d92414f5a4ef67a64a3a5cd2c89cba4a88f6aaf31fc21d46d9',
    'cdmw/ui/archive_browser/filters.py': '243653cce0b57a313431091438e3f825cd9e734a6bdc1e11dac6ba5e5817bd08',
    'cdmw/ui/archive_browser/header.py': '7cb9a660e783d3f8c75dc4de01280d084e306d29b9428e78e168f69f3bc35bf1',
    'cdmw/ui/archive_browser/hkx_document_actions.py': '5f17d3083cbf028a4cfb5fbfe251b419ed689cd74c7ecfbb57dbbe089578b21d',
    'cdmw/ui/archive_browser/hkx_editor_dialog.py': 'b1ffb23b954b846d94c49db15bbbc18cba29af21023126ba343366a24082be99',
    'cdmw/ui/archive_browser/icon_pipeline.py': 'b3b4ba939a828dc5aad1b4e7203a4637b3e4302e2405e08d36e6718947bd5fb9',
    'cdmw/ui/archive_browser/import_actions.py': '3906dae06ce72b744b72c77e4ca03b5e70e7f6d567981cdef129b729cf4f8e9f',
    'cdmw/ui/archive_browser/index_workers.py': '72359158ce8c7d3dbe23a771e0d1d92ed3a4a0cae7416a9c1d07180b7842ad38',
    'cdmw/ui/archive_browser/material_sidecar_actions.py': '9a2503a45633b3c1f24e605fd20da9d285d29b4c0cc8b9aff9b9ddf14df3a09f',
    'cdmw/ui/archive_browser/material_sidecar_document_controller.py': 'dc6117e9161284b4f852e15d19b6645cbe735c505f3c0761ecd0b5658a109667',
    'cdmw/ui/archive_browser/material_sidecar_editor_dialog.py': 'e895fee117f20a641317f02449bb8d3fc6a1b37d8758a9880c8df52ebc5c04a3',
    'cdmw/ui/archive_browser/mesh_builder_lifecycle.py': '861eb05ed1759e739c1a23b69221a9ce0c5698ba310ffb232217e77d6410fcc9',
    'cdmw/ui/archive_browser/mesh_dds_preview.py': 'b0d168f6ec76c1a9d4f297755b141b6003e708b93640c10b1686516f8e0d6409',
    'cdmw/ui/archive_browser/mesh_direct_patch.py': 'ba356e65c4bac04829d9c5222df45d7430e1838ca6b968af5ecaa1649cb8a78e',
    'cdmw/ui/archive_browser/mesh_import_export.py': 'fcc89414efc297ccd4ee016dccc744c854b801900ff441287afd5e58f14397b9',
    'cdmw/ui/archive_browser/mesh_launch_flow.py': '3c89986b062422a345c9e1ef69a22cd237e2e6b340b614f7c67aafef940c273e',
    'cdmw/ui/archive_browser/mesh_modify_original.py': 'e5aa7d6b8144a7c24a60b09be803424c8ceb8417eff784fc7f790d59b3417e51',
    'cdmw/ui/archive_browser/mesh_patch_flow.py': '4381c3da1280dc4defb21e38e4e1007738097be545439e97ecbd28fe86050f3d',
    'cdmw/ui/archive_browser/mesh_setup_helpers.py': 'ee5732d95edba276254ed4bc62c818e0164d320cc8c565436fd6bcea7e2f6a05',
    'cdmw/ui/archive_browser/mesh_swap_scope_dialog.py': 'ccfaaa16a285078817c74ba0d7183dc6df9bcad69279d68419f91a349453e06a',
    'cdmw/ui/archive_browser/mesh_swap_support.py': '373d1c5d3d40cd9b27837b7bb9b91b58dd5418ce8d60aa7d3f459932b01044e1',
    'cdmw/ui/archive_browser/mod_ready_export.py': 'e20bef23616e7fc3ee94f00324ef5f7a38264992c79d24b5f73d8dd88e6a3824',
    'cdmw/ui/archive_browser/patch_actions.py': '8cea853e1692afbd0d3df62ae36e414a71248667191c7535bb978d213323a113',
    'cdmw/ui/archive_browser/prefab_json_actions.py': 'cc4e8ca3e07af354b81535ebb40dbc9a0fc1e6a5b38a7e56a7887653cca03dce',
    'cdmw/ui/archive_browser/preview_cache.py': '321988850039c5c4aec9a1572e2a88efb631518aa6fe9e0b586c7c354639cdf0',
    'cdmw/ui/archive_browser/preview_d3d11_parts.py': '9ddc2198249239286e4e010d5a3ae0a422d437e6ba37e4e97264b32d312d2cd8',
    'cdmw/ui/archive_browser/preview_details.py': '9b2b1176c71faf9c9a6c1b0c256390a75c7bb9a29d2a7d378ecb7ac2f2804d70',
    'cdmw/ui/archive_browser/preview_dotnet_lifecycle.py': 'e5e79d2bc28a2d22a803fd5064a8d2c3a37a8e13eac4aab1c4a275e244298eac',
    'cdmw/ui/archive_browser/preview_layout.py': '78b91912af6c0d15bbaac4ad26754646a344f71a6f57ec28b642fb6cbaa7d5be',
    'cdmw/ui/archive_browser/preview_loading.py': 'c4dca8f369b896e11fa53bf63046ce23296ac5bd74246f4423ab712f07d1fd72',
    'cdmw/ui/archive_browser/preview_memory.py': 'ecfc8bbed02b4204953b586f923c1accef82f773d65bc7a94a938de6a90cf131',
    'cdmw/ui/archive_browser/preview_native_core.py': '459f7495f9a3640117d508b0879cb9416dc0d53998825122ffc83f5e54911a91',
    'cdmw/ui/archive_browser/preview_panel.py': '37ccb35ce68b805400d3a389a823ee46e679eac08c000d54efafe593fdebeb30',
    'cdmw/ui/archive_browser/preview_renderer_controls.py': '1bbb1adb8366cb82e014ba13f70de86234125e511268b232baf84b18a6863374',
    'cdmw/ui/archive_browser/preview_result.py': '84cbab0cfb80dc5456af05b9c77163200d66608b569a7e9e889266da4fc50d9d',
    'cdmw/ui/archive_browser/preview_settings.py': 'abf24c5857cc8d7b03fd4a8375a58c6854ef40bbb95efc427fe6a422cc9211e7',
    'cdmw/ui/archive_browser/preview_state.py': '69bf9b96f7a7e98f0728f9485c4cf9c21c7c45e6de3a36ba571d46a5b89e70fa',
    'cdmw/ui/archive_browser/preview_timing.py': 'c084bdbc6fffdebe8229895ce9d23787b7e3ee7d7f6c4c63b4ae9142cb0c9911',
    'cdmw/ui/archive_browser/preview_zoom.py': '0b463e20b2702585bcde0bd968ff15d416be21b5e044d8a92de169dd1f27d63f',
    'cdmw/ui/archive_browser/progress.py': 'e2c04fc4c3f3a9264bceb11909b58bc149899677949f6ce4bfe9f760752388c4',
    'cdmw/ui/archive_browser/reference_export.py': 'cb5a92a9afc002466217fc1febfc3bfe051651674ded13a6adce4c169c825bcd',
    'cdmw/ui/archive_browser/reference_preview.py': '9125c504e909f33d04444a82758520314d22a3b5e8a76264c2df9f2f04925f65',
    'cdmw/ui/archive_browser/remote_related_export.py': '2b749620410f8e28949aecc08d18e8261003ef19378fc9c1fb8838d98699284f',
    'cdmw/ui/archive_browser/render_lifecycle.py': '0ef28d51eebe320142130ca0d0c5e78884f056f37d8fd94a780ea1ce9f6e107d',
    'cdmw/ui/archive_browser/scan_lifecycle.py': 'b8b934422baac6444a4513e61b2ce6703e19a84317836c3d21e12e3fa1e9939a',
    'cdmw/ui/archive_browser/sidecar_index.py': 'c0b19c1e4ffcef6b0449b069e59078318f70c2c1eb1a3a77446da240eed9a442',
    'cdmw/ui/archive_browser/source_mix_actions.py': 'cca919f195e3bc023f644f8eede068f54ae5ad28b8adfb6d76de8b21ea171f1a',
    'cdmw/ui/archive_browser/source_mix_overlay.py': 'cc756398590af735bacc12708f7549cca297a6156ed9ede13462a9445d276f21',
    'cdmw/ui/archive_browser/source_picker_dialog.py': '13e702936c56c36d23c30b01e36a3491c5765f216e57e4fcce7cc4410252f0cd',
    'cdmw/ui/archive_browser/static_replacement_dialog.py': 'bda707116b8d203e502697eca79fd2161252083e5f6a416326a9a7271d750c90',
    'cdmw/ui/archive_browser/ui_formatting.py': '1e3e3f4c24c42400b845f24d1cb3c5ee32c80492acf20c85c3ee3d6aeda05b72',
    'cdmw/ui/archive_browser/virtual_path_lookup.py': 'f8566b0aeb2e13b2adc6071edc0b4c14d42eb2b3f560b0b03c676ac4a0fefc6d',
    'cdmw/ui/archive_browser/weapon_placement_studio.py': '245076bdbd2c72d44aa4334696a5545c886c0179ff80410bbfb868ba51b537a1',
    'cdmw/ui/archive_browser/workers.py': '23fc8314f479613c5fcd6c6ffffec29bd8b128d7cecc68c5c5ebcd47ac2ded7d',
    'cdmw/ui/mesh_editor/shell_bridge.py': 'addca52247b56c0b854c15aaa28e03d4e320a6dee20e2a914e4edf04d73645d8',
    'cdmw/ui/shell/about_controller.py': '3f0c94ce36b3031dcd2fd952f39316206f933393fd0a08deec99aab614775d65',
    'cdmw/ui/shell/about_documentation.py': '2e0085e052855c808dbd0c842f18b7bdec7af578fc31af5587f633bf66f94716',
    'cdmw/ui/shell/about_documentation_de.py': '5248ba836011e47001d8ca16595d6b63efdfa90af3dcffb45fb92e1913295a76',
    'cdmw/ui/shell/about_documentation_en.py': 'e2661d2d48b9313c8d1541ec03846b973e8e5a9aae8f868610c0dc0ab76ed924',
    'cdmw/ui/shell/about_documentation_es.py': 'c66a32b16a36b70dcebb4193e6632dfa21c22d7f2a5b2d0aeab03063b2551abc',
    'cdmw/ui/shell/close_controller.py': 'b8fdbe20ef060686f9a4f79f5bc3002b7938720bd9ed1d995581626b285f6404',
    'cdmw/ui/shell/dashboard_controller.py': '29414e557d54146c1eb2272143b6069b24190337c35f3151b3971a485a7353e4',
    'cdmw/ui/shell/language_controller.py': 'af56fa6c8b532394f00ede24ba06f9ace190b98dd88cdb9ed7fd1df9aceb9ea9',
    'cdmw/ui/shell/log_controller.py': 'e4c119c9e319a14eabc17efa7ef6afd7e58333d82956ae38853f5d683bbf6191',
    'cdmw/ui/shell/menus.py': '1dcf44d1cbe442b2934b0b017f6041f1f5ecac6b01221aa92fe1145183cdf44f',
    'cdmw/ui/shell/model_library_bridge.py': '34f9e9726ac5ddcf13e0f80e6ca8e642f94b44eaffa53d71ba96817c9e10dcb7',
    'cdmw/ui/shell/navigation_controller.py': '077ed6e190eaaeef0ef55576d8818665a2e6ba0bc49b4dc85d5c6e42ce7ec7d6',
    'cdmw/ui/shell/path_controller.py': '3b63b582a43e75c7175bafc62b893597f622f1b6e822e05f022b678c6f26ee10',
    'cdmw/ui/shell/profile_controller.py': '55856e46ce2092354f6ad72835a9c707271635ef6782c5295d62cd7134ea54db',
    'cdmw/ui/shell/responsiveness_controller.py': '9f6fd06fd5dd1c17c40c52456f39e51c2404b2a5868639a706acdb2fc1027723',
    'cdmw/ui/shell/root_layout.py': 'dd642108d502746743e16e87a6036f5630096af8849c933e26682523f9e07db7',
    'cdmw/ui/shell/settings_autosave.py': '7c7acd2dfeef5dc45723eb904c5c34876a18ec7cd08e00bc9f5701953b916b27',
    'cdmw/ui/shell/settings_persistence.py': '8e1002bb560c30c6b782fe642c1e89f051d27f50b588b9f034482adf8e4d6c5a',
    'cdmw/ui/shell/signal_wiring.py': '4946ecf8b9c7ac6c69e8febb2d83ac039b2c06172fa1f1d355f7c99f9a13a7f0',
    'cdmw/ui/shell/startup_controller.py': '5193236d4b375b61a6a0fd76b8b1bdadf76de3e2615f0cfe00c3fd0b2a09f8ae',
    'cdmw/ui/shell/startup_restore.py': '2b019a08a8d94b1cd605d1c19d4f4dba5305c5df0db9a9476e39b80c5fa1b6a2',
    'cdmw/ui/shell/support_dialog.py': 'eacea9de7dc92ea3aea880df58215684e83f78268a7ce8bea87bc2f46486601a',
    'cdmw/ui/shell/texture_workspace_layout.py': 'b3649d197ae934560486bb571d47841570b1dca433d76fd8e7af92aec723c1a1',
    'cdmw/ui/shell/theme_controller.py': 'ebd7b71169743dc9dc8f20beb07917d90e8002f3aab9963945c3e1dd69ee1969',
    'cdmw/ui/shell/tool_tabs.py': 'a636b454747398dab0a7c64d9cd6a11280fe6ac39234d05ef37978cc45a50224',
    'cdmw/ui/shell/utility_controller.py': '3df6133672338a890d1bfb1730a0db8d48e5ef0698732d78967c6a36ff14e6d6',
    'cdmw/ui/shell/window_bootstrap_state.py': '7d3c498ad75d7e905b3d67ce17fdcd8c965b97f13f6b41fa8e1ff403dfd142f4',
    'cdmw/ui/shell/window_feature_providers.py': '6982295d3c86f2ac9ac2cfeb21d2964e6465397461203e4e3c88df6ac87ace56',
    'cdmw/ui/shell/window_runtime_state.py': 'ab28a1bc55eb27aede5ff548c692ae45d6c57ae8f951021c76bd72275260886c',
    'cdmw/ui/shell/workspace_controller.py': '1939a8b5ba35b6df8f9c53ceda0a43522afddb180e99ee6f01959859936a35c8',
    'cdmw/ui/shell/workspace_layout.py': '5914c0d72df658aa8e9744fac59617e541d5be7a6f7ba15299b9f78cf914b684',
    'cdmw/ui/texture_workflow/asset_authoring_panel.py': '1883d70965aeb62f0511c0a630336cfc3fd6e09029832e69706ef8bd1dd30f65',
    'cdmw/ui/texture_workflow/compare_panel.py': '40a02252e2f9e8af28b02795a525b635d24161239943ab7440ff5ee7bbf46265',
    'cdmw/ui/texture_workflow/compare_preview.py': '031b7bbc369d3450e1b15e994a602d612d55340d24745d267464edea5f533307',
    'cdmw/ui/texture_workflow/config_collection.py': 'ecd80aa9172c9ca648029ea41d2b96f6d7dc993209e304b7746463721885093a',
    'cdmw/ui/texture_workflow/dds_output_panel.py': '806c0e2e4cb2315a59c4bb41d2a70afc84cfed065266cb36514bdcf51212f38f',
    'cdmw/ui/texture_workflow/editor_bridge.py': '27e84da9099881dc660aefe2faa576c006d7524179e44c1477cbee662e9c7e82',
    'cdmw/ui/texture_workflow/editor_handoff.py': 'a5ea0b7edc63c8cd19b34fa6a278764d576d3d506582d8e4521668f6378b7afb',
    'cdmw/ui/texture_workflow/paths_panel.py': 'cfead75e031d45390e95dd696b41b0b0917d215e54033f8022764de72a8f0c7f',
    'cdmw/ui/texture_workflow/progress_panel.py': 'e073b635cc5725e90d3bbbc16e88fb7ff62d07364da8c37659c7eadf94330466',
    'cdmw/ui/texture_workflow/settings_panel.py': '1d30484518a4d03b5b934c96ec44c7a0f1177bec12be1dc921744f6cc6ed95b9',
    'cdmw/ui/texture_workflow/setup_overview_panel.py': 'ebcada18c07ba68ec0c13e3364c60ac6b9728c79c81ad6e07956d8b289f30a14',
    'cdmw/ui/texture_workflow/setup_panel.py': '455f9624f16fb5378e6b04b60eafdca64312f8f822aa40a870b0d170ab995d6d',
    'cdmw/ui/texture_workflow/shell_controls.py': '3c11ef00f5497f16e652bb3332c7601b1f5fbfb071075d21c65f234698cddb9d',
    'cdmw/ui/texture_workflow/upscale_backend_panel.py': 'eee85df9dd0870a82c06531b20ff08a0eb69e6990c51d0412fbbe08d15c5d933',
    'cdmw/ui/texture_workflow/workers.py': 'a35f47fa07b748ee38aa61be5a1603fe2a172fa09ed24dc21a0f70678133a670',
    'cdmw/ui/texture_workflow/workflow_profiles_panel.py': '77b52dfc59f4751223ddba3118238b55db8f0af33f8883929d941e9855052058',
    'cdmw/ui/texture_workflow/workflow_profiles_ui.py': '19d286d200a02e56d35afe0898b8378888324371a5b3fa51a5d6629ace42a2e8',
    'cdmw/ui/tools/mod_package_retrofit.py': '820894bd8462cf8bb950aedcad4762b62e80cc588859fd197a99a1f348b7785a',
    'scripts/generate_window_feature_provider_members.py': '08cb18f85f0168a3147f7e2cd9314a1092d56048a7ed1e785a09a7aaec037853',
}
_PROVIDER_MEMBERS_B85 = (
    'c-p0X+j1ngvEaYVb4xMg$orr-S+c|4knIVLd=#;}Cm6-'
    '<B3YhhSG%j4GxQ1n`{oTOToOQnc7*L=BMX;AW+IWu%m2LFAD+K_d!4==F8inHWxTt;%wLxA^6ju+r}=cZpHJ&$J}&?7`X2uC0|Wh@VSXTx9|hts)'
    '7R<r?)(3F_dKpo^I^e%-d)d!VIA*W=g;$DJl-W;zx)2?-'
    '@A9G;dz9A{$Jxa{|%qir(T(|I@RHD*v5njT&Cej<BeZe8UEe(A9n9NkWA@$JYDY)C~h5LqOW(udbeK2@$Nh?6ZdeF!A#5D)90^R%W^%R=gYc4H|w'
    'x}f|1s{^KsaZ^sg`T<@3XF{!;z&VR)X7ugN-'
    '=_>%+%{yUx)274cX!6bvx_rvKh;YPt2^M!}yZuj#UI=fyj2<FF_jw5a{cbT@{Pp1KAJsrmV;5*YGaT1MYZH_uLP~214+xQicmVph+GOmK9D&YQUx'
    'B!O7%iUo-kEg?U+P~hNhyCZ_ajbrb*l_?Wc2R+Nm@dnDcRdX+!*m?(kK^4s&&PE-Gxlc~IQ#m18DFOH%iWjhbU=c6Ujkg_>tzp!nZCyJh7QidW!y'
    'N#5ns6RZj`js0K*Fq$7n$CG9E`j<Tl>@_4qm1*>$))j_cxp9bp65y2Af0D{T6^@4v&wCzzz`g?Q1?IWjI!e0e?Xb$LU~&7I<4k(?^Zfy$Js`)8kt'
    'iFvz)!dvB!fj;WYSLO4PyzG-qJ+i_opgQQZeK727Cs3QBn~Z1_5=}|o5N9o6W|Ia+soWvY-YCAS3di|8!l$P_ZpHKSe2P?$AAIYN)TnD8Q5QrNj#'
    'NI6B3~;o%k}wra6(pv^OP#Yl6AR!8P0$i+%NbQ32^`P?)zH>Nbl+a$Y%R~n*f0@E0RDHkxPASn;CrJ7!d}K<!yWUyCx#d=rPXGf*u2&d+=wcL|$8'
    '&7`fd}kMyq-vdn2FrK(7k^UHX-'
    'fUraszl=;q_v7PqQn8ur0_n;4#S@_UIMzS8zfQ-)-DO;^$2HJ^s^2(Cmng2P1gUl4bR+nEZDA}}+D+plk39c1qXSfk%WA-eiE)x0>YviiNF;B-'
    '(3|$+jXU2<m_7UO77{jcH%gHLV}F9C7EhB90yX7yCkWZ(co7@)jU)Uzdvf=Da+-'
    'LPKG4{)K99Qts7Ui8Pp3sP_+5!(sZUnc+$mM%xM+bY)0t*t$B1=fjH}xjsG)BQI<eJFK2^RTRd7G7IFpzwu;oW?(0L-#CZ!Af|M79YOk-'
    'jKiJ=}Z^Ysi`<2>!h#H6ADE~s;oGIv{qT<Jmxh(+adyo3AUc&v6EsB-ZoX&s;MkQ$vLmxJ*2@_txGoE5{3nKjPzO>_9p1=p9mGi;l6FN~XOraobZ'
    'A`$*H6-'
    'hC=*J+)m28i|t_G!~qtT^jW*jhSMz>=U(g8KAIVgPoSE~r?C?P>?p=>^DXMtTB0`0hM?eMS*pW*>LFw;=%ucQ3>7il{^=kTUb}Wi0hOtWS|O@uv9'
    '+-'
    '))f_rZQ6%=hQu;&iPm|*ts?Jo!(i<rA@M8y(%%<AE~**XPN;4CINyhxN2)KkC);6lxiuV+?&wk1gEd^Sq%I%EHMn4%N98C#M~O#+XP_w3>qlf5pm'
    ';%W&@~Y-hYPPSoqQulB?AI2#0HB>0(=+FCeeOj=_L)TJUGjExBr@F2u_$y6p@XI5Dc-'
    ';v~=W`Ff<cpM0aq(v^Z~X2}fv0>3}skC)1(!qbh)pOt;G;B?m{HskcH6xl(KCUjd!v5y?Ow$D!ECK|I5xLE)lhu8VKmITnx)T#;~zVCSpE~qru3+'
    'lNK;{}zV1(tHc8wfpF9f#+0W}@YJJfpGce4JJ=Su%8@QhPfv8j%o#0t{;0%Lq4?Z;&^q6X@;7BU_T6KzsTZK!f4=%hL#|-'
    's5$+9GHoDz2$ksFvsgNzLR{z$K%5VP5dfd&<dqT_cHV}9<ImH1RpW05uL`R_AIn(m3?dM+4}B{H<LI`sYKx)vC(kC;#^sqChb0cCf|^Hm|&K}>m9'
    '!m-'
    '>5L~^gp^@LWq2eiUa1L_%e50f}2z<*Ygh$wQ@0hI9`Lz&q3Ljp?SE<Dd`1chCe>dKBz#N6lHj|)5{2d;)|kopcWT$oEB$=Oo_O>>Ra_tt#8(@MLs'
    'RUFz<Dn3ft&wY-'
    '`_s8AzaGv&@9twWoHPHw&3fQkNvnFAkzAZKS*V;qaIUkk6<2%jxdAz?;l{I9^H2kaB@0j1)k&9>nTHXs{5mp*~P9qOwdSCzK3<k*A1yQY2T9>H{h'
    'KH#U0av*XXBNy=UFpde?v()t%%JX6c(Z|M19SxyXD9k{V%9f%dk`E-nYQnHu);zCS-'
    's^p6()I?YoBDNyeOjIT!Z7_}zQ8rRD5JlHMS_#)eLMFyH5NrpBT3Eg+eYX?n9<8&n*!7LS$2L{sM)y7Pc&S|F6pKOmlhkzaK7Ui`?qt_HVI%Gi^9'
    'fkyJi)E>qFSRo=uZgwkpL@psrVLM9Y=j^GJa}Y9h&u)!g~I^FL|*@e`NkA!yt(^;Kl`h$<0>ojc0@RLcRbg4m||xAEj~j?Cr;Q!TohvMG!G0I<g&'
    'UkKwkroX34;khRQd*Ir=H6nYnE+_>XBFYIDf+P<F=;*S8J?_oYC?~LaB-vVcz4=p@aJ~pmMdMd2uBez=D;_PByCNQ9TZ%Mf$>foUZRt~{7xE9@#y'
    '?)tLN(EwbMTBDj^nv>cF72;O*BYUa^TzezVftF^GccJ=;tmO>frsI~%wGU`HuWv<$=qKw1WBFZyyZLbEo~z1%Q&1-'
    'GdjZA=Co}K=sJHMPt9(Z>wOLmkA8D(N_1a|JQWmvsKUxRMX~*kRe*~Dw8>GiH(QO?+LU9Z0t@Z$dKk`(4?B|WTlY4K?&UE%m3GmnnNRxUOc%FWC3'
    'm1&Jv`Kvq>m2vCjfnenxu|pRh0CP?W;VM7j-hc0cejpq{N<vGraPza_N<iGW~Ab*%M2eJ-X2x>kAc^{U8{m3SM~F^X-'
    'w(&UAX1nc)HW@iZ^%w095f*OPHxy*sD9HT9yoXM&x0?!}gIzl}7y3=d;=(<u<`Cx8vOv6~asvEF_EzfAk7e{5Z)$l}8Ut_h{p5zHS5q@^@Ue_x-E'
    'cc&{p(t@HNcwDJ~TYI#`0D`Bt@lol#PdnY&=4Kw*h}4&9xq|v$C7J&sm^aXhbe>bo?@ZKE`n+#x=i&7@4~Od7J~B*;Vx-'
    '6W5n{ZYS6fCc4ro4XL0IfrCo14=86J#8UtcMBN>Q3U;Ax92Vi5<ounPpiz~&$4{ctQ#=_~b}Y45I`B$D?4@BtwDJiLEW=DzYlhkqKTQ~D~Vf=Qf?'
    'kap~X*@i#N`|C5g)$6O=9}$7PBM#Gru4VU7>r00zVnx0|=aS0^KfodKgcqjz5SydI0vlK)Dxf%gkUCEP0(rnoIM36mI2#lRXue>~2qzSQ;f?5W_s'
    '{FFmbTD)a_Sf{d{nrg3MfU%#Aew0SHAJUx9FJ4@5hy|*+AmQ#BWQ;BzQp$p3;?m(UG4Kb5jF(0i)!6`B3Tz=Jpw0I&lpL;aL+XcUuBA$QA~P*feu'
    '^EPVx5Dxgpx)a$9ZeDumaA)##&Mh84kFS9?~dWZ;-Pi~3e22|>tV4klSZF?-Df`BeFhY;%^&ehV(KYdEe_(*^9dVi<GWU{o-'
    '7h{BFMUYS6wg&A49iIU;N_U!*<BH4dZyiNoK8lP}0qq=4ju!AH<me2mll2BnXPT39Hx1w_m|UadQ&zou1<E|Uo&&E=d+&E6w$b<6cY+UmJWAnjHF'
    '(Dt31~@atcvxwt)qt?`&MjTuSs1n?Ry6$^_{O)0cq7Z>iU^c$hO6jQPVUti}|cFpMM>KqC)_6NWnf;;y+PaI%WA=PVzoQ{jJxFp38&nSnSm7O~-'
    'cM?V|qz@J0pa4T^PB?d!XM?%H=+vm$TNhMP)tTjMk6drfVxb?50&hHTe~uKQuv?XYG5Ns^hU>9Ppq6GL#)ti@o*PI~^w0t~!ewo#2b08PMtRKM8t'
    ')D#+1wmc0l^JlVVaiCHa*w7#LltU!*f|siE6}N+4K}e<|iSuLq5`T)F=I|DnyiZi)HbdTex$e<N>5xn>fX&>Wa3tNeu(rf%wkl=MB6wchiL@TIU-'
    '4EC*5ecF;2Q8<3WUGhzQAe!JnmbwP@XZ8X-YqV;q`X&xhhO0)wAm))*`SDf^L&jA2IcC-kZ5#*Ch`6=*vjoy)<B_FFP}~sj7noY+Pkz>e`{8CO_g'
    '%qm$uB2ltZ)`vXC#$AjD9N@k_h{Z}wk{e)jSW8Ul=s%M}o+BhL4s0doR$zSF#)prBe8H|P@4xk<2BPLAcI6Y5moO?h<q$uGaTJ^R75?gW=0LePHX'
    'sH2Q6vP6zT&;ae9>Z3$7K9eF!*HdD9{Sx)BTsU0oq%s)&ro-'
    'f6nrmZjIWpJvXas@f*UJ4y2^SqC<+Nf6*#im#1}TXrNPLD@oQuiir~DDOAC+$XaEz3Yrqm|S>yxu-X)02BfP+e<1~qvqOg#+P$&aBh#-'
    'I@8woo9GJq<nk&W9Ei5kAqB3Mgwm}Q)ECkR~3M*J~#_^mFajaA!58n@B91D0jh8Lq}8RTgRSsf|mUGRL~*Ey2@}TvaZ$FnSjy*O;Qpn@y>-'
    'YYY0fpD@1yMt<}V)l(+)P}|aTa*D=SC=!|<=Hme-n59IZM)GU^4D3*9qhM;KkrJ<j;(Cu0->-VyI>%t$YB3g^6*WvdT+TWRd>cy<n#u(a`%9#Bq-'
    '5eP(5NMx9>;?U&Edr3fauyE(b@h`h`p?YWrif~#A>2V%cMvg$v(P8FaB<oe#KkDhs^stsUbCo!B?q%9fgIdtx5LDrH~PHB@dOTyCl>1Mj$ZX3DSb'
    '#(~llWmC=%|H}mw~f_@ue^blKpJIg#-'
    ';m8V?SBaxZvMn|%vV%zm)F`t}mph{nEJ~4<05Zt$MG2;Nsq@Q`^zr7$U8SC5RoL1LW%*N*xAqVIXLV}g`v{sqcx>`5Ow2*2g#+po2=I5jOs7XLpC'
    '<?@u5=YcxR@J$EsAVP`e65*1MNc#j@NWd<h&010O`B0F1KkF608A_p!zKaP?sw)pJ}}2@`@6;>WUKB%8C-'
    'm+KLj;a79Ugqe~AxpQR|lZ5f9B&?ArxgXP`|psrIsZNXM@C{dVPbJQIh4s!B^p2J?Rx{-'
    'zgao_m7iOI+g(9Hl=<EHITE1zZSfWZMlL5TMi;P3=?K<S|5CheXXmuT>cf)Gk0W6y1(Xp%%@XRJhErYoaht8TklV%P**ON1Jwj#c8>rRc74Oca>L'
    'Ky3yB?_d}s6Pm?hOP<)Id+XdYie9VOw;v@nWr6}v6<r78P0fl<(1~V`!z(>Z2(1@zfv@X93GA*mRAXIicUS5m{gK+Lg^>2cnX(IH>e;f#t2^nVJc'
    'P^pmFJdA@@nQ_+`*zX`G*Dp0x@;iDyU>-6H;io&WCA?GEgvt-Opi&W^&I-A)_lb=;@!+bzt^LXOc|sLD>w0YEqn3Vx24K9v<+U5aCp@rPMi?3-'
    '7%SmE1E0B(6LY-&!k++jWsf@5=0CU?&1AuB@cewYhexvTan6g-'
    'k4HkQZ#`)5OJZ)M7}gn~H_g^_;FrjEV3Lx@_q_L%0m18)$ZG_c(X2@QTUH0;B9=4>VY&T~I`vSUg&@29OiEfF|jaO&|5F%e*S{4($rW&_IffQrg>'
    'UA&)i_Xw?4++0RV;+B+k>;((_znZlsH&$58hO`<Y13KUIjakJzNe|5>r*}_+V;SqytUk0%ydcV<{X%hZKc^?_4o>0d+D68`CW7!*y>o<8_^{-'
    'dtb(}0_YmM?GMnwT-'
    'n+M7{b%!r9I5D&&0zJSB+M>cQ)8lDiGR9k;%kKMLfutuVxCnq@bXqA7+&{07E_&fX+=6dPU!KMhw0Ne1@S0u$riZvDtY1O}=F2ciO`g_d3y={)*a'
    'j=sR)sE>0rO)?hrE>Hu+&RVVz7_%39R7pW2z^E_?&g0#Cl20ifS20_qs+V-'
    'w=@+bhMs$ADiIOPFA3kDV)YD+z5|vgxVG!`50|j<U~ul!kXjS2Q5aYQr|{d8PKx!*2*nd?jed6iM9E2S3NE44D?pvRFk(&Y1<^D9wM^Ky$*5O!-'
    'QS@Z9m1k4o9o-?Gx&KXJS?9sEX;vfzZ?>TDnSEaj5DrZ8fQ;0P^Ff=D6@DYB6Yl;Ug+s!B*JxMR8Z)oZP-*&ifqK%Y>z71Wtlg-'
    '*1WImCmNqy4e%PRfBO4<HO5nm@#z{=9~;Vax=`$5#f|P(5+et)IB!GC2q@4=rPtzIBR2UXWBv&)(n`a?~WNu*4?R6JGkijFfA>t;!mHy{v_?Spo-'
    'A9d2=s2j9}uK&a3#aPN@ct(Edr=`?5|+0Bfu3r;X@cGOc>OTqecHH##WNeN$}1touMP2bao#{hsq0z12{J5aUh2*wMZTp2an2K+s$C{*1p(&jju%'
    'fzJs@fRi5iF-9%bD5Eb#Qji^>h8USpC%7vfP;$X3liRL?f_n+mPL@_=+fZ#JK?6m#>8Xo~-?XJ&WMd-'
    'k8UvTbgGD&B1a6emD3!LH=E<6uDC@48ge-'
    '@yO;yTdoyX&Jic^_lHr<cX&{3n1IxGYNWHr6GID7g@czRHqJeI+UdBuvP*Hf%WZP{$)Nib5yOR%T$aUg$K^sh|@^+0}(TuJP1c!5{R;ocn%S{}C$'
    '5n}bmr5*Z<$)&c^a9R@t)vvD=)A|N1*o#3g&Fyo3uqRM?u44@xki@?9n#IG{%Y>M9|5EoD=taS*7{`GNe_{vTK&R9B3YQ}PR`*R6+U+7IJNf5ztg'
    'pu*jM6vXG`{d#p?{irq~`=!s9#b;bpE)Y&<4+?UY1B9*`1NIyZO3B9GwhkU}_`&%`|D}owsqlU8c1qWG6}W^2M9EqJwff#g9n>m?dS0{Ou4_)uWh'
    'I80~`gXKJe5&73Axy)aaO{Dt96fhs8oW>I0w?R@_aAC1L<Mj9x3GKK1W6*#&FU<OhZiZYQxVx31yq!tUc*6Q19H_owR-9}v6*IcC?k`CId{-'
    '3d>@~EE@d1(18YZqXrn9z33(w*UM6u87Xx^<Wa8w8_P-'
    '{V8T;3>WWwK)ZU$N`i2RfkSs%cCcN@dRSw7f#f>17uJR+cHVQ`4^BsI&?C;#mhjMh7qa8t+Z_9&OnUD#oG78P7+3fFfu{U9^3e@CLXe47uq577Xd'
    'P)S7AG9)~geZE`F1|S%V~UVj{`DQ^MsaES3E{OW^M*Bg7sflQNL|*EPyjl1bO(12L$nsT{J-le{HGG;r#o#3GqN`-(tOVoSB-trip{jJnb{pt79U'
    'kRL@@2Uv5n37jd!qg+`SW1O5%<>~{5W_0wEY+4K-'
    'L{Zi^iR@WP<YV%#Y~Js;3}(i6lQ_+U^cFH|5^{Yb%sbjctiAMSqQ2c*L`RokE1TUC@m9&SE@D3GJF}eMIwNgi8gfy`hn_M-'
    'd@R>sTchplQ?KF_HBT}VP$2ljxPOJ?C&nd!{GK6xb^!W8fnl)th)r7w2QI!yKc2EWYzO3pEQf)sVvLL}6B2NUkw<2QJKc)Q+&cAOBx^?sQrOJvZd'
    'GBVcX4KHjQl`y=MhSmj+fdhxTHITcIM@d+4tGcj6#f0raohL?dn7g%k9FmbvZlJCfkr`+F2|1nk0^QHCa<e+&>+bkKAN%1&~}BTX%ullUs?Cdt$H'
    '&TSOv%!AW1ketlw$EoDl2AUTO26dF%n@LXrh5fVO%R`5Q3kgiNHH$E1YlnOUxVDnmc9Z2s*xqa>CmG^E;n^?iiYrnEZA*WVq{8%iEsaP^dBZz$XI'
    'f>&2%Q=K){nIm;X`>hWY*yrp22mi+Vt_ScgA^y>*l?$!JW?TC*k6#L#`%$A)=AKIrUM#H?kHD@F9zmQ4d!#g9BOyda`!l%Apgng!+LZ;pA<-'
    'kafP^i@M$_1u95hRz_7bPV*4aiR0Q>=nuWDRZ&GqhnJPII3~O$$*s`r{oS3$=u{;~;80obS^}9Bw7%0(37EOki!Ie~Z$nk6tHe|R<uPa*ycrl5qO'
    '9mS|8XK0^)4oi=A*{S%<+9NQl;5T&foW{Z$klOo4NNq*;W%6&&Fvj}lVqFlGqwE@nkuoQV!h>Ak)@Zye~JCXB$z#NWZ$T^OQq)^VNPsZVn%e7$f>'
    'xg-|zDGn0)ZU-qufh%ku3LwJ+Z^SHr4p8`C5pSi|)2iaGEfF=QztqQ6l4-'
    '=w*Ie8*h{mF2j&OlW|I)gALMz!iAmEEIC{iCW>=aGjpVAniK4M%*f}+t^VB;lOglSJmV*M%*SbQtmE};?rla(aF_+T&XUEG;%UKSwvXiG$x1A7`e'
    'LIIk%m8t9lV?-&p&$cHyxDi-xUlG7ak%s?a4Zw<vQJ&UZ>=<@qCkYfg=ir>F6FPG8z^cAv2IPt>Th^5GEO(D^wVD2-'
    'JSm$2+MyTZs0g;i1|9sBw$)^!PM7Rc>B%w_nPb4oBTRD0YTtBSNqKKljxM9-(~={6?YiJ+Yo_3iz~lZN7~RU;$P06=^~fQo-'
    '#B3tsaOp+<w)+AEtE8`ltcCJ2sZmXU~TY_S^n8ziTIr@cEhbYuk`NEl$JH7-'
    '59DGh|eBxTca~`vVZj~uQ>}J6ySSMmd$BxVqQQDVq2Admj0al$iKlg91Lh6?o*LCJ{IHUxX7fImxdzK0&HKgnF=J|PFX9^CB;h2b6M^j>S!{%i_o'
    '}yxQ(RIyT#OhlqYGCjl(}d;0ZNx?EjRO-'
    'D`AcMzbQ=}Y#Cvpt0$RIho{{xzcplSdF&t7(<A7F@WcEQ*^o7(8PNDrK^8LXb_U_3gf%c?xt2)*z45BZkirOj_wQ0zVXA_gy+1tiUU5xxzdC@21Y'
    '}{>UOgme4i|<|M+49ztrCVC`2?IN$^>Ta%zgJa&`5?-eW?Y&NzhGO%w3MbrP5blt3*W03yaH_F>ZN|Qvrndm5Wa0_E-'
    '`f3Xgk702F^&*r)iNG0`qNShBJK2zfPJD*Kj>dvyzQ5Zdb21l_}MSsSaXYOBK&7Fsa^(ifwBD-_Tq`dFDgTy+%$!aY-'
    '2mfo>T|<)wmgF#V$HKC1w$E-'
    'vbX&C~6eY{yg^+r^Hq=wp^{6t?_`4b9x{uVC_6IZhjW)yip1=nnUM<_y+b42Xk}Ufir)=s*xR^dW$bCZ9(l#qW9ywT1N*pnNPs;9Zu2%B{*D3;5O'
    '<6|60F9=@=}K?c!MT)r)=b(jJKPtH1k43!`_6`|f`hy0<W;x6&khr`WHwgG&G`uo!3xTc{G+5<9aanWnd-Sm)#S0!7%N9iLTk3O2HN*4FmgFlI?f'
    'LrpVD%dvc0_W_CxlkA>y!Vu@K`LsXsC1Is&%2BhHnHP#Q3?Ts`SR)>>R2n`7mmQi2tItS(F?s-'
    ';pFr!lo!p!Gp|B~X2P#>qzT(?GBE9}ky4E8urrFd9`V%@hSqH~Fshk;8=}S{Q0>CVAQh}q)GWhI0?Ww5Z{^@R|5{FH*>BL@7VVt=>BCPqHy^RJdR'
    'TKWlDEaF3V5Y}-8*@=hw#wzbe2Qr2DAv6xyHl9vSwQjr?;4nXmH@9A@B2tzyN%mA0Lm-Gc&8}Q0rHGnM2!xzPcq(gkncr{?*fTfNLY~ojCXMI#nA'
    '?3*l{a?>hJUElcg$&>p08?x~4V?AvZ)M0ik}jye-^Q{hJaOiqun4-0oDRp!{el-)E_K_R0C_2@#BIw&kJ7WYYzkV-'
    '5JLZRk+@W%U`DFijpon;Z$C0G|=+L3uZL0`HXv)h_^{p+|k9GQdqDnZ~fIs=KulVo?Az(rpC{V>7Yh%WB)9z9jzW%ZQhCGfUMj1+~W-'
    '>}g8>!YhlK!YV04w*qFXWh!jhli0T>r&kLoKI0j!*L;-u2@k64Lr}*ov#TB4m=Edr!<hGSX3Fs=PdG(0|KLj&H0(QrJ*Hba?-'
    'p7jOpSL_CuOr#ZNlYio6dL5X;M0!bT9|mzHc3!iu_+)n!`|Q%Dw;9e3qNg4cQP&GU3!5A&B(Whb8IWz{T6sosh1r>jf#32M#R2np_3*=|a)AvL+U'
    'oewO;Xx^*#PId3V8`+>^+l(aJ#pFAi%(75z2dml{wIIscqQgXtW;U=gL8qv;98FO7VZN@~f%G%A7z$EsS3E9BQOWcXgPP_CS`m<vIzeu#MNj3|XZ'
    'nQvmyRy23S<;5IPgZ#rJ=j9(%(92Ch`<8DBgFI?s^4QDF|4Dj&{JXK-=;<7S}V~opHD9=(5liBxHfaCmLD(g<5`qXNR>B$AED3KCz}w`_%G0-'
    'ACoKv=3ADHu!Yc7^=~+1qsez1ZD*d6Mv=VAEC9bmTIOk$)z90xKRmN4K^;Y?9W9FbfUuWa-t<_3AJe-;fX!%Gv%N?ZPTRtrrb4Q%O2*{gk<-'
    'Ag(K<Lxm0sUF%KQrC%KbpZy4mp1{L2QuXsxOWXrnRUjPn+z;f>v`UndkFXj8AOcS<n@t2W;q}jR)F6Ee{OVtoHJlN*&rsa1axQ3_R)msS4YlUh#C'
    'n2t11gKiq$(4Fmj~*_rliWWe2w%M?e9EtNwrC)JIrv6Ao(@$QJm{`Vkc{sz`nXd46Sky6TKafK?hV-'
    '62{?<6A87MwPtLx?Z~?`UsOqh^Dc&?cnHIdP_@@v^>9urx{%{1_@k_@CoL|^S%)9(e*JZTq6?#dSHZ0F%P^6|vF;5Las3gbbun1gvqYe@hkXG%7P'
    '~}Hq?#3lH3EPZ;osI2`d-'
    'R`hfQ`%ATw<0FU0dJD2mcY*^|DYuQFhA_+d+Vr16}%Ki^UfyIx@xkL4^pfTFFuz8YrI~=ddeetK71x@GBypjrm(iZUG_cD61X(3g`(gDtV{goWkW'
    'W&ck|{%NU;%$r+w3Bg>jq8F1Iwf!1_d`_qRX+g^6;q;VhHD7DbPvtnr+@JZSVFDVc@{D|ft{g4VXCZv+!lov(-'
    '@k)^^{Ai(nNO2^K`Z5VoKorA5UcAzATwgLXmc^%&3S4o_a7Hp$Udg3{i6&f~2@6EjUhmHL2YkARQ(?nV)O(>@K4XH4L;#2JUpjP{1;#<w;JoT$*u'
    'K(hlR8!VE_;@#fV%D!y-24DuNZmw(yo~yJ<3#f#5(?(+uMO&+m6{5V?|CM(rvWYL(jeJ+RcF-'
    '!eiHzi@ii`WtTn?Y8F_XlGb$M;Mt@eH|2_us=g;`X!tB#bm>&I7^$%o0Tk>El6ox^2yF+xcZ~r%hTGXuVA%nPHZHt2{7Nk*TN-'
    'x~2htW`WIYUnS+ojp;DCm;!tl`hu4=zZ#%_;n9oK@rf6eo=hP(d*zgsLsVL!2f=<tuL@;HcaVt`bYR&FnPYX$y>k^Nr1N(I1PWw|Y=!w=IMIP+={'
    'v_g2T^)EpMdM7xS9xLAXHtIUo-LY!ZWb0efLYo0;4Wg)1E2rH}D3yOSTxu7raTn)P-sZr+;!&`7rF7W7Q38BIhoTUSBIJ+PK&43rROnfmQe5{-'
    'd|JaUD$O5~W=Tnp77BPThW7YAT83=Q!-NncdaEni)%UQ0@fN;o#O4#NX>o49xW-DL+oo8>9r?6rN;NV{*&Lb8<r}3li8F+}b$kd%AxS#?Ym~q@hY'
    '9kC>BiF1TG|8mEyXs;2L5cjtL1R?+gr=xSTgbjp6M#~9U8)#eBMdLCHIRqKQka_@Ja#SY=v1FHfy($!k2d&rZA1G5~kgy6&&*eDgQ+La*A4N|0bA'
    'M^p@#$;-'
    'F(Itoz$VHfD0H^U|rD>zCgf8{V;zgr6|91jFoUT9hpo^7$?3KQX!Tfcym}20&dm%akuAZ6hPfRuo|W`H|A=NiAHh>b<LS8vvt&0f)+`h0K#$&=82'
    'P^yp7ONlU};^-(=^T<=z`H%|MXfbu)c=7$Y0&SAyrydVQR0J)hb;A$0w_=~jsf-IRg##K}eHV7&dxoD&G8)V+N&TM#%NegSQ!=q1qfB9Sj3lLrdq'
    'wH4>?Dd|qs*b3&&{{EXAd%a~V!qeZSmio~YnD)<^BB_Mw(EEef|r}v=nNmYxQ6%xQnA8>&GBSZP*nPeDLmZ<)!#E?e}xQaADmK>eV9<(aD}5^+-'
    '3`3w4{RikrNO_!JvNyPPLK+AmRV~o#_a9q`e(j$()EtrFgNlqh{fi7$+V)EN@ceffSN_lY({(=V1}*Aj4Yn*&%C}F1@m)mo~bPW)S)Xnc9-'
    'u6(Xo(-@1!k0?M$V=40j!thehtz&lQdxA1hgc3?QkTY}wkhINYmPQh<GqRfXw&(UByb4}-WhXVG-)2LJ2+vRzmid564$wHy)(x0HIu1UMx*UNQ*-'
    'I-'
    '<(Xi?pF>|E6tH&;hjWy&8G515G&W4$9A%2w;_JFPkwKOw!`QoIJG>$oi#W1^yI^oulS5rpkQc18@O16lFWT0$FJ)t#4wPc&k@@!Uei_)KN^f+9hS'
    'tHcY*or1gszMfHdmAK90XJR<j%<e$8oxCjrNlaV?VzXv`r%1JA-jHbQyo`t3Fq+OgFP;~n+f?UH{lbXb`t<AzZSIf(v4$;dZQ!m!b5%N*^xV@|HI'
    'LILY6dc|rE!W(Awh>O7%cP)p?Xs>*p|$gZG}#GFGH}`9_{?7K*LD@It9gshiTL|2$!ZwdJ~gp1}5ctA(oBRGiQp~a!v)nSt+oCdlqu};cw#);=v('
    '_1)NKuEn=Z9?ms4e^M^gCvu;QW!6x)}Ah#2>J2MR$SwUW2bXNEqH?~=UodPk9o%FYHLbSKGj|@|1B~VLd%#;5}?Uh`{i3LB*+^J8!{Xuowoai}B<'
    '*dz}pnlna?8%sw0etrP+iIS|%9phjT_?GluBijW-'
    '={zNhUycQFP0<^##k#biSwV2(eKOp8k`OJ_i%l4XKo1Sx?$VjH}nE9`SVkby5n?m0YZ~cj2UJMhMzCf@;RIj{KO+kAAXED8*O1Qb*OBh$}l>n>dW'
    '6X@NdL&jWj|bEz&O{kpJR#$W!_BGqqN!BrGKlhrn_IjpS+GGBzBNtX7TV#qh<hJ$P;TU&i5#2@pLyEi2}vj8O0!!F+Tep9rEYXA50hq;2EV>VlLC'
    '-SR})QKLJk+b1dlzoEOEv6iAL$jwoR`7JB<TQ78{RMT-hW3=WL@v)_R_L(_4KMMvE8-'
    'wmWr^ZFQ%RuZdQRt@we{WgBo3PbdS!<J8+q`Q~RWA`U_10}0Q4D#x^7&jUb6o^;x?brDSRc00n`urVx`Nzp-'
    '!4!n1d=3O&?}7bg(Via_UtEY`#m*vmGJWK9#Wesu6xDxZ<CUbVUs*~2fq9o1fnV|SXyombGfCENt(B?DJ!s8oQ_ZIz6snKv=qgl9NiVTtV&K9)Lj'
    'QIBQAOMzR>=I+w=p!DB}k)pwvf7rvb*wbxe^z1XTk=U?~XXle?&U5IZ{X#Vf@FqbViAsH#ukyP^@R&s4evgp?`ORfdb`&1n!s@7^RZt`U@)$WqXd'
    '9_KaIs!!5@=Kk3gxu(vTR<^XE)hbXdTW#jG9#*#s5Cd;@@@uC&ut}sYUhEJBEpcyU>hMUTW9-}E9)@)fT*vVu3IP84qyMp%wTQl-'
    '5K_ukz2C)cctPTr$#(OdbMh`jI4`^q;!N%+p&IOe#;fFK?_l{4Oae@fUX+g4+qZlTI<O=iAyvp}83SJ+`Z@dBsj<+uK24Vc<)D1UAnOV10Q=9G2x'
    'vlq{gZxm72F5fPQ3zGb=Kv{sjF$uw~WE+rnWY$wdLA&?uryvL!O52646H;1a$vX_<NJ|T`wd}A4iN=$_X?Aa!E;|LgG2tf@MG4K^#IY>}b0ba)VU'
    '{EOlg=#;(2W9MKTywv3r{`4N9@NSE|I(P#PD-'
    'm?fVP&59tJpl7~I3>ByNImMKPhuLEl@~F)ByXw&ALYDEMu69Q8G!B)XZO~{fpK)TfVpC=9eA<4p!k&piJPRMR8!pB_%fb+Z4uTvR>)K9mb}D?D52'
    '6Spyc2u0KPRipa60HMH$^?W%TbFA&5BrtWP8o+8~SbQVNHU+GsU@ki{gI^lZ81u9|Z!&#;MsB8m+NHW8AM2zC|<?;$@6FXSX1?OD#ghhcfTp9kEz'
    'goS@{Ee$q?>vWJUkFVD*dj%x~@*~6%N@3`XcrJy{_mY!e%)L+3Id+`%z2+~_@f2>=)~H_x!a-'
    'mzTa{#zz($Pxqm1@xAIGfLqiH3T@tU)(Ep}JkjmARSTcx5uCn=wiE2XHPrJ;2$kQW(P{I^pyh{^E1vw{|Agxk1bf&{s5q@O9Zm%<S%y_Tj@8cRXY'
    '{Fvirer%(Kyl%$JefSLLU)zHpT&6X2q!W12L^kiKb%6JkFxen!RZ8zH_+|8TRQcKc8OJWON0nrM;HIPh7=GgG_9h8XXC6_|E^I(vM*mv0rLPM&F6'
    'py4etG553aUtGV^~GfuDWsR8Urk3ILe6$!&$_pOP0yM;NKOMmQ9=Vm9AZe0LpL_<a(U$F9W_Cg%(n5`I#G9Hd3hu5_guT-KO}@>tj%c(ZQ-'
    'UIzLcqti$y@raf<^93bt~9xo?pe@Zp<+km6zy-ythx<YaT_odcL9WK|0hw1CMg!xw-pf9{5?$KPgiHod<$*UYZTkhgR$1-'
    '#sH@0bY;je4&%&4y8WoIR=oUl*B%k(&eL1kVx|J66OM6}EMMrlB{6#voBVNN4g73X-Qpj;|bBl$eP3ECYJ=zCCVB`Ap-qYuLi=NEV`0cl1bAv-'
    '&#FY!wRb$T7+ula5CDTr!yBL~<CvkdUph51QijEi_Y$e1uaU%_b<^d*Vo#>Z*bPlPKukEzXJ)SdAQ|LmN7u{IG;$y=vIWA;5ua2H+3hG`i!G+sd4'
    'Ue@s<ZIrH#TR#MK71`l`Ly#*p_L3s^ah!ozwkuc}<kjh<RM9F#1Qib!gtFovU`T={W#4JbT{^Vgy9c<<FTvrnA2wp(HcorZ&zFG#LhLPJYmn55+J'
    'X`lp<JqTTb@sOxDs_#$y7ySZTD*X-exTeV->crMyC~4t4Ilj2kRVI5-L?m)u7}iFBCX%r-'
    '{>&Fs;jgqVPz`x5h*Hi9yai=~;m;J*`vXaA3zEc$a_o{qK;d=!HJ?fyc7QLD|9tz`taq06?r0)Hb;AKg9b-YX@H*rFD5B-'
    '8O4D94IN+BN|<@F%J`%et?%;hHCzmuUX%1KV%htvyM*t(@CEgweX1!qeV^r@dM|WbqQw7^Hmw@tS!WsgqG)`2nO9PVR9fB5DCGW$(iN)_=sjDw8D'
    'Tfbw5hcBbh4(#{qFi)d`~=OcHE|^r7K7!E$AGH9RTUXyc+n6FSxl)Kw$NIysl<rARF;5^S(ngFV~3Tc;02tXyV(14<<e|86p#fF}&hiEN`>lrpX%'
    '#bJ8eIFMsbYY~kcR(o1PhlLnwOB*PzfvC2-'
    '^4NX{;S7H~LBJPy@x=a%u5PF6&gYfV8ndySE(_);e14|%WnM%CW8PmSNncRMDrk1OA>wZ3(8#+{18x$mxz`hSm*d9u2`)*l=1h=4%X#K|d=0>>ug'
    'l~g23T9E-~p{K^ZE4-'
    'qY@Xw7@UI7TS_(PMyNhpPuM6U&`<uUe*1}C2qJX5BskFOgG*z^&2ooi+f|_h6BX>5gl|G(eWT2jZ(*eBp0^mM#KYMxW_#Es*9w_bS*pQMCU&aPSD'
    'n1ew3iE5z&rQ>FCeH-_`;LQ*<Ye&leo>YgyQPS3C49r`t=g#P+>1}3Y>qKqU<Uzq=pJN;x$CR-'
    '9)bo^bYzLg;l<dMhc*0txoGNfsr3R^aX#p8Z#LT76`*f4oWHayj57u0GX3W+uxU9K#j+2sWZ4TOk)|SxJ16i#R$W9jwtQ;mKH#gZllNOJ=lxy(JY'
    '*l!XO(~a3P}^3J7mm9Nrq`RdHEjGrUKY9N@<jinWkR;PQxBiLes&(LY(Q>8zlD4cW%RF%c}DNt_-'
    '!86tWk;qWR2hf>cSgIVI(+63y>UtTGW<DQHpYQp(o1vKMi6<a!6g*`&-'
    'kaj9HuQ#&A`fL2!K+F4se|2YS)gG?HmiRkmO;ubONX$U{ZGN;6n2Gt@+-lkUCexT`xQ|wL-IBK@UCpAzBAI#wwNbX($=|~DCh1dQM@`<eBxC91Qx'
    '0gjHbrF?={e~a__bMKksq(91F(QqU${1)d<I^#!$~4V$UNldALQ3kDhNU>yO%--'
    'PjL4>J#yJGPLzY+#%Dm`XS`&~ZMyooyRPE}^8pfd<j^+(^z{rcqoiV2y4<>AMR75Ld(^4mE>SpM=h3{W)iPiMA-'
    'vU|6Oi~4kzuX}A3OU#buH4icZR*_+KCEcn`o^NKje&E&=3yCUrhfWw}y&V><m7x?ELl?k!O!o^1!<kb;BVm4-u4yDt}2}n<hek0vd-'
    'k_<M5qb23pE($|CV$65Gf7sE?3ltiKV+n}R%FFli{q@bQ{Y%A7G2+EdGoUFdOY-1vPhuDoVzpK-RLW^`3!J&EaG1hb#e4^ifqo1o%m}UK@P^&T|2'
    '2y4rxxLb>;wS$7BZZS!IKh2?4;=GE>6nu0Z$TtF0s7=;oO>zo(qaED3QTZ0QcnjhuNSF^PVV#lI!l2@R%Q-{=QmC9Ma<`0%+FZ-!sV=zG-RB4S@{'
    'AqExheB9EmT{kb<O^g-'
    '^(%5?^VyuWIo3<HO9AG=^gh?&P{55+_uHm3e<%=^+rl0bl4d5T3ioal$y1#`J*?%Q(4?UD0|<I`9yL@Pu|^WcB9>0*g+*S`InX=9rD$qZ2S0CGt0'
    'pGuiPf-N);6DbPij$%TYP9TQPT#|Amb8(rZe*#?(wr$iXO1_vkl0;k}+$16tZ2bCYZUt9P+_o$(RUjxfb5_Y`>F_#vrr-bx$0%kVK60Cy-iTmQ!R'
    'A#5aZIkl0kV5lTb2VVr;zn+vGs(7j(G_Or$B?!<vQo+jioB&e1%gUmqth1EBVFZ;QWwQh+Y7adaWhF)1(Z$7*$C_HOxP{X`-'
    'FK}dYQzoNraoETmQjp;`}O~Ho4En#yg7=VmfZx0`Cn+z*~evuiDY8*t8E8n;^CwuvP`F?|kZ0ILa!oJeq~7H@E!44SEWMIHzM!tc!Vgy9l}fX9KA'
    'B*kWZp2DnKADlNV4j1z5)t>8{d+J^b9KJjmrbXH=Ul5Zhq1O9i~i$5XneAI8c=;HVK*ZH*B^qbyse#KvHuVC=M6T9)<QEn`+7mDR|SO*vLk~O-'
    'd!7>S{SsT3YK;zN-qww1zCTS8U@et-'
    '|dVGSYttUQGbr>m~?B@~|+T|&PtC3z(5INa+lWu|pk>Kz@T<FH_MDKV`$`EZJyw)x2|4judF_Z<kI%H2Z*$9!tfoGAzTyd@NuzM{)gaEX!h{Sxg3'
    '_!^CyHbJ@l8KvdINT4U+Sj!-6K|C94v>Twu}y@fR5FzK`b;-z;Yt63!_?v1qZobPUjd-'
    '<EzL2tN2vR1+|~9XE!0<~y*jft>AyiyZK7<`LX(H9)V8ZivO0xSq+Ek^%G6OLsXD<|q*Q}vn^Mxk(rt0v7V663Bu>p?sMD|T+pq9b(aZKY{OeWDZ'
    '1&s#ZWq4+`Ci3P#;)5`Y8&yjY{3lD6m3%4HXni<BkP5p!W5t|$|h+=B^*)^-n|T$X*jKm0zjVR_-'
    'FwJ_~EoF5blnUG%$M0ZGpR|Zx)8m@JJ`f_5K*9Lk509#o{{p>^k&d3mVq5kJ9&^^%?p_!;2H$yHxI+KwPWruI+Mp-sOF)ZBQA7{a7%rvap>kI%p7'
    '5b-'
    '#<`Zy@j@SJk#W=ke=0!K?dgrh@*Re{aR1OI|$57r;pt18r&RoiAGlwKa(CRNK8t$E#f*HXs>VGBP^d#eIr#r#|^Y^y}T1CwO<CoGT`^(@#OvDz_#'
    'UuC({sxAk%Bm@wd>hUfx@cKW8}gds=RJq96y6XiK9`%EXnZv^mr*Iq9E9E9iVou&e&{XucMfNiJ=JQgPV3%8o4nw1KVx^{)Xa_}mYHp}+vWAI(iG'
    '%b@<km-HqQ?c-yYiTB^n0-'
    'nQFxFy>gaqo{?vhq<hUKi*i}#wK!WIz(oA6u+9ea~Y&;^kC;{1@7__F0+@`DHo&WKL>cT^;lL)o`p#jY!Ww?R}vF>Hvt@PkTdF*b-'
    'iXX}r6*e;>Z_ZCATKL>>1&>lF1duL@xZo+kBUD^g}hvC3&;qnOK_|$O<7SUV*kw(mPV7q{z!eWb9tK-'
    '0g0TY!qXmwX1bah)>6jWoy%sI>RV$(w_)p|rNK#g+?UC#V>5-6VmC-BIT0F@-'
    '2OzJ$N%emInOnp}8Wm#H?@f7S^N}qlaM<FrIG0blQ@*_ihM1aZ$WD{^clX4GI5L5reHtn$5Z(-t<n!i%H-'
    '1Wv~>Td&=!f2EzBZLk?4whVT{+pW&iu=C_6qI}fSKx>JW1LAO8z-pj48VAk4hQk}>rF*Ud&u*9=W|K(dpig}y0@s_`aGZlg8pK%X>rUEv@T-'
    '}Z|}Dh-wBi}*GN%2u5EsJSX`v~5}?7?u+Lh;>h*l$(JN6pC6_+>cO=m;9)z-AIVi}+bMo~t(VXIuvqz-?%aBb$UIYaM9Jra3<l)b?2GQn$ij@G-'
    'BDNX|&SbN(GrZo2Bk$%l;L<EPC@gfCvSxvlsx#0D-LTmPJ}PZ%Wm9)LV;5=1umu+KF7I-aL<(DD;Jgk=VWE;Lt(O_I#Y8P3(-'
    'KoHiQJN?jk5%!+*~-'
    'I&*+(*CJ6PT2hz?H7g6Y9Un6ZGX{=5ub@Ekb^wVMa8^N@W=AgIx`S2QQL_w2Rbu=ADf!me3udYl?Lt%!eWLcaJzmnxik0ob?HOzUM0NhW^Ae7gXG'
    '}^5Qmps@;DtpkZls0kM5g8n+xvlQeJbf|Cv>XLGDk$Q(G>|b_&h&UP3gk^iVr9K0W<8g1TKVLIuW-*5niP=RAO=-'
    'gQgk4Bz$lLZg~uumr<_+iwNN_27gcRmAvs7tg-gg}3w7Pn$HnQmeI-zwriS-0E<YouiXL1i)OyENB5rP4HzD-'
    'k#7eVvJ}^>Pn+0|aX<{Q0D{0yYvqyMz%cc&Nvxsp#v_Xlg$nifhM8&@&t?TS(?#u>><8AU*9B)nVG3`<Et(Y?WQ^b}$PEL=|GFR#vAHKg_rsRGVK'
    'k#fLJVLzpWmuDvM=80Dlz=LDBe6hdgk<?B-Aeb((%uNt6zAC|PFt+I5Pt|kBUlk^yY-'
    '9a=1X@5ZtbOxNw$T_LmKeh_a^jPYu(cS+Ljo&gZP_@c05qpUvHvel{sDhjaF2!v9K<(?L%)L9^Ob8Z|7_4hISMA?hOK}y}Jhbe*@q5bA68}>Jf4V'
    'A!}ij>fuAVMJpF0OqRBE+bg-(>Mf}8O?}etWwSDG0qLK5)VFo+@kiCk$APKp<b4olaq?+I?1HsC{FO~|X#o*kFtq)7pa)%-Gv-'
    'o*k{Tv)iZ<Zd=^0)@ra3Zq6oLG8y8`2C<ZduJYSWdbx9;W#o(gMk7j93u_ge#`@Aftf?bR^8M<24|G4W<7!1}<kCTN_VUqC|)lly=^cn%hgn+(WS'
    'mg{9axHQf0bD)j9f<4uVD*%W|OB*JH@aglogWIGzBRgjZ%%;KSEQVi#7^w^~Gzb?hQ<ocL*3zItZsGydZi4m%A)sfJTA|R?L!k*I#enXEM(LH&w3'
    'Si%nXr@3cV$UuAk!9oHHDx>mbRr^TSgj0ZG)NG{8(kB3M17CyGngEnl4gwnH4SK%OnZwyl9rYW?61OAnY>BB9&Td2<XYa2v}7axt{+faNX)uGEAR'
    'JSoqkmuEugIiWPf^2PXRM*>G!fSyh$18B(Z3a)$V_LK^_DHOPR9nPG8<eHj&(o_d>vTqMQ7Anh3OM&9+JsfNkmlkt6BET9)j-'
    'yf!6rRZ2!@0x+ASv+Mo0B;HR#gwj>==bO|wxDegzB0|Wu%|6X-'
    '?e6#k>`Ir1`?EPHVBUk6r=JIjjx2tK0t`*(}>RQ(OWQ$dgf9dPcEy$wj`d9EG+Pv0&mSNeP^7wqOcRDnKkIBMMXs#QL$C0xB})4?650xQ;ilXTcR'
    'Lcr^f~v8(5)5&t=-EQgU5#k(ZH+S<!_Tf`~8WQjuR-8s$ttZ4h8W0h+mF-'
    'd7$}b1CwP{JyE(#Q1gn{<^MMC)M$5`l^g2fGCL<`%Q9P3eEtx8PO<)CCzF0KK5G9CK<)uaa2t9Y%h}lyHk|d!21xy`K_nZ!<?o;%pu&@Sso!XqRc'
    'oj?NSrzJ?Jswyn#b226qjTHWPG}^-?igRv-S(kiTcZmOA8Dwsrg%sR8N0sr@07|G6<E2RV*=|9%?7Pzp;Qy|HLB5fI1U8vT|gRbN$m!n-'
    '=!nyYE7rAh%(ol)KM->6OBW~%lm6-TxRk(*u8G;tjYpT(V1RX|PfBO0C`CO9-'
    'XZ=85a(`S*%MlhqAbEHkP9XW>P^x#1Q9=u?hK8u@E_Tl+ySVlF3hFhvpHk)ngciWFt>&>}+M#%)JA{B<gguWJn8Hw=}IrK1J!ct+IUy`JNm1k+6-'
    'pAFAjOR>IhBS&(X*M%XQin=tC@{3h*7(0SL<T?NTIEkDK<YjTc`1M^4yp_h&!R$RyAp9)5o|!OnUEtqsHoS;L?@CGkv2)Rz!nPK>SR;oxH?;vnYb'
    'yEl%$fS=MDm?Tx<_C-'
    '}@Qgl<28|Jg*Oj%vavITZc`T>oIo2W}!XiU(>78(tyS86u|JkZ<WWasP@Hz2>`bO0JG9HsP#aTu3ug;BmlaOQT%W=Yq>+;lHx^)UJ7VQTLa8M={|'
    '}{FMpc@1fM_8FM0z-(`PfD4zZ@1V8HPqJ9~d~qd~f^!fOm7tkAKiLkxp0z|hWaH4mt>n-'
    'XBylh+30b%d(4cRJR{PO8PdSAl3&5yUE_asTS5!<QINdxj!tD-)t54Cf2dH{M%)d&HJ!-'
    'vGcBt4cfNi{_SXUInIUtB_fLu#QQN&wMPrqB|>v3ITHacnDnJbBJ0Sk&iwAtzc`)0>dMTl<=#*Pc?op5J-'
    'zW%D63KrG@h*&Waf8Vp=0R_K|s=#@kY&!TNR%F|vn2k{D&C`KYs<bEU(!er{BbBlU=`95SV|OFwx!Pg~0o-V!{`)45Yyx=vM9>F-'
    'nJ;+`&$vvP;`<$S!<Ga-'
    'jCbh3n@XbBMWjq60Yn3ub2O}jbi`fPR$yhS^QB`Lqv5>@ba{lKnaP^<bQxBnu|&BSba@(Z60g>zSGFuqu7ob<Z|ziSWt-~ayi{|9~AD+&'
)
_RAW_PROVIDER_MEMBERS = json.loads(
    zlib.decompress(base64.b85decode("".join(_PROVIDER_MEMBERS_B85))).decode("utf-8")
)
PROVIDER_MEMBERS: dict[tuple[str, str], tuple[str, ...]] = {
    tuple(key.split("\0", 1)): tuple(value["names"])
    for key, value in _RAW_PROVIDER_MEMBERS.items()
}
PROVIDER_METHOD_ARITIES: dict[tuple[str, str], dict[str, int]] = {
    tuple(key.split("\0", 1)): dict(value["methods"])
    for key, value in _RAW_PROVIDER_MEMBERS.items()
}
del _PROVIDER_MEMBERS_B85, _RAW_PROVIDER_MEMBERS


__all__ = ["PROVIDER_MEMBERS", "PROVIDER_METHOD_ARITIES"]
