from __future__ import annotations

import base64
import json
import zlib


# Generated by scripts/generate_window_feature_provider_members.py.
PROVIDER_PAYLOAD_SHA256 = '5ff15fd3f133a2cdae0771438e0de46ebeab103fe522a57ad21ab721857fdc60'
PROVIDER_SOURCE_HASHES = {
    'cdmw/ui/archive_browser/action_controls.py': '933f119c793f1f8d563d20a4c1be02c879ef8855f940e37ca59f15810d1d1e46',
    'cdmw/ui/archive_browser/actions.py': 'd68f80c4893f8f9598d57a5194c19c9cb097f96d740f5631299c8bdb41546809',
    'cdmw/ui/archive_browser/appearance_common.py': 'a274145205da93bf9948b5e3fff10303806ff60f480081167243fefd8a24ce8c',
    'cdmw/ui/archive_browser/appearance_composite.py': '706e5142a62cfabc5ea2247d9366eb1db43859afcd78ba3479303e413d23fd66',
    'cdmw/ui/archive_browser/appearance_swap.py': '110b969e688826fb44ab8a87570c18a73eace9568f9c56290e05fc5d3033eb71',
    'cdmw/ui/archive_browser/asset_catalog.py': 'f6b2e8693b9e8a168f088a140e7b7bd7fc49880d801d84656c8abc55c13d98b4',
    'cdmw/ui/archive_browser/asset_catalog_dialog.py': 'c86a7bd0d8b06170e7ef4648e27ebed551835c0bca18b03bfec7ff116016d312',
    'cdmw/ui/archive_browser/asset_catalog_scope.py': 'abe6ed668e68dc10214d59f220aea5ec63f1beda12ac83958e54859d545ca57f',
    'cdmw/ui/archive_browser/asset_family_dialog.py': '2370d922db74b833950cf39661879cd79a2784612176bbd3f71094661cf30b30',
    'cdmw/ui/archive_browser/asset_family_layout.py': '048896d81b5ecac4c1f9c7b89376838da8b7bc994a3b23cacd66fe501e95b244',
    'cdmw/ui/archive_browser/asset_family_panel.py': 'c4eb2fdd387de60969a1ac273a657a2a7348181d685325277eb7d63fbfdc7585',
    'cdmw/ui/archive_browser/asset_family_references.py': '810485688af08cad5ada34473b344484aa323a20482959a628f61e7a4f526d2f',
    'cdmw/ui/archive_browser/attachment_batch.py': 'b4be23d7636a8dc8191b0d3c8bc9c2dba701397c4d3eaa1ed9a3c639085cd5b2',
    'cdmw/ui/archive_browser/attachment_donor_picker_dialog.py': '4a7fe842d29b93a3b107fe015b28ba65a9abad393a4b6a8cfe9fd6207bc940f2',
    'cdmw/ui/archive_browser/attachment_icons.py': 'd54502e08e0d2fd8405c172bbd5ea7b0f0eeb084ebddb4866d538da65c1a573f',
    'cdmw/ui/archive_browser/attachment_loose_files.py': 'e4bf117ecbb9e7a18ccde85f12adb540309746bc9d8d97c99964cde9ccab7b33',
    'cdmw/ui/archive_browser/attachment_package.py': '644936511446da9a1896cd8df14cac6f91f286d61298fce65e99e17a626456fd',
    'cdmw/ui/archive_browser/attachment_placement_diff_dialog.py': '1b3ea89263d2cf7839e877d725c8ae80250789c673596de584d2cea5d9131a7f',
    'cdmw/ui/archive_browser/attachment_plan.py': '44058f819e9914fc373bca27ba21e3b920815e75493383ae56b01c9e8c0f4d3b',
    'cdmw/ui/archive_browser/attachment_safe_placement_dialog.py': '7b8f3ce94a09be94ea8184363ee90133bc9957d44f56b4bf1e02773825c9e7ed',
    'cdmw/ui/archive_browser/attachment_socket_editor.py': 'fbda37f9d945474296b88a3b3418c5a48856b870cddcd7dbac66fc536150ae38',
    'cdmw/ui/archive_browser/attachment_visual_context.py': 'c95d2435a8374d4886c7ab7b09abf6d21909a864ea29697885ddd8afc75fecb2',
    'cdmw/ui/archive_browser/attachment_visual_core.py': '41789ae65b6c691b8c1399ede797f4844b2480fb1addb84a4b0ba88673b6d58b',
    'cdmw/ui/archive_browser/attachment_visual_dialog.py': 'c45c6101df63433fa73c8068ac4666fb10e7523a1c8aae80effe318e0c7c308b',
    'cdmw/ui/archive_browser/attachment_visual_geometry.py': '9d545223625fb1207889c1a93ce3d22d67007c7faba9be82a0254c4f8f8682c0',
    'cdmw/ui/archive_browser/attachment_visual_payload.py': '37b5b660ba5016dae57ae8dd2522c0f1184ed6dc8afcc180bff5fa4a12b4b1c9',
    'cdmw/ui/archive_browser/attachment_visual_preview.py': '309387a3ccdf8d8377eeaebb646f922d5199c8048096170e307623c6463af4c2',
    'cdmw/ui/archive_browser/binary_sidecar_actions.py': '2eaac56d99c65e16faa64718ed5212a23276691a005d5f8c2cdbf39a5a2154b3',
    'cdmw/ui/archive_browser/character_dependency_export.py': 'c238ed9bdd77d4926e6a0ec9379099af6566034539fb85b4723e4ef1a4dbf872',
    'cdmw/ui/archive_browser/controller.py': 'b617add6b1209ba4847a74d9d53458ff202ad0bd8b9b7e67aca4e6d258826349',
    'cdmw/ui/archive_browser/controls_panel.py': 'e18a28c6c33986056d37b97a8df1241c92c773368bf757950ff1fa9db9d5f959',
    'cdmw/ui/archive_browser/extraction.py': '1084d6f8011a0233ffd6437474838f8ed2984aeb05c7eb31221f493a6523c419',
    'cdmw/ui/archive_browser/files_panel.py': '8c515621f70071c84b59764e332dd07056eb8f192912c7b616abde642c3a82f4',
    'cdmw/ui/archive_browser/filter_controls.py': '068121e472235c1f2dd62e0b067cef26732bd575caaac20c614dbc7927e6e5bc',
    'cdmw/ui/archive_browser/filter_workers.py': 'a69590c7b83f10d92414f5a4ef67a64a3a5cd2c89cba4a88f6aaf31fc21d46d9',
    'cdmw/ui/archive_browser/filters.py': '243653cce0b57a313431091438e3f825cd9e734a6bdc1e11dac6ba5e5817bd08',
    'cdmw/ui/archive_browser/header.py': 'ffa9b6932a7b4dfed0639e0372cd95568a693e509bacf9bbf1d501e93108cbfa',
    'cdmw/ui/archive_browser/hkx_document_actions.py': '0fb1a4e992dc42fa55eaa7ab5542d8fe34d9460a7cde1333217191de5a264724',
    'cdmw/ui/archive_browser/hkx_editor_dialog.py': 'b1ffb23b954b846d94c49db15bbbc18cba29af21023126ba343366a24082be99',
    'cdmw/ui/archive_browser/icon_pipeline.py': 'b3b4ba939a828dc5aad1b4e7203a4637b3e4302e2405e08d36e6718947bd5fb9',
    'cdmw/ui/archive_browser/import_actions.py': 'f4a52598ec6d2c11cb16382e2d4231327cd07a8e171224db11d36631a8edf211',
    'cdmw/ui/archive_browser/index_workers.py': '31b5ae1638df2b626d11307953a5f1f08c2e224b5112d5a436ad256638c012e8',
    'cdmw/ui/archive_browser/material_sidecar_actions.py': '55f896e2551bbb70cdeda47814e406dc13dcc741e6132378638431c9de5831b5',
    'cdmw/ui/archive_browser/material_sidecar_document_controller.py': 'dc6117e9161284b4f852e15d19b6645cbe735c505f3c0761ecd0b5658a109667',
    'cdmw/ui/archive_browser/material_sidecar_editor_dialog.py': '8c8a4dead5db6d8c07fad326213b5404725fb19be78530a8cd436db4e7a56e11',
    'cdmw/ui/archive_browser/mesh_builder_lifecycle.py': '8a02bf3aabaed60205dea9b8cb20c9122e59c59261c7f0510e118948a5dfb26d',
    'cdmw/ui/archive_browser/mesh_dds_preview.py': '9dd99ac9e939c65e87e3eca409854d154f0033116559128c20048d4f8953d8bb',
    'cdmw/ui/archive_browser/mesh_direct_patch.py': 'bfef1a51d14921bd2cf6255e31b9fd4c89b2b97b882ca65fa4a30e3673b11ccb',
    'cdmw/ui/archive_browser/mesh_import_export.py': '29045dde0edbe8a99d4bd7dccbaef7e62ed59847b7e1a7d059892ef8efa1a76e',
    'cdmw/ui/archive_browser/mesh_launch_flow.py': '65eccb6a134c9580952ab88e3428c9b15ac9c9b2627b3494684b03ee7fffd766',
    'cdmw/ui/archive_browser/mesh_modify_original.py': '6cef0220af6d3def90b73940d09d974c834fd7d93b4ab8124a03482f3d570162',
    'cdmw/ui/archive_browser/mesh_patch_flow.py': '8e8091f9e2b9ae2a0e69da67225d749c1f7556619da5ffdc9ecf39f54830ce02',
    'cdmw/ui/archive_browser/mesh_setup_helpers.py': '1502225f06f2e5f13d2e130e0109388eba36e9b8f3f29a5fc5d92ed95046f444',
    'cdmw/ui/archive_browser/mesh_swap_scope_dialog.py': '926ee27ac1c18b921bbbf2621697ec727e7692787fd3bfc888f3ac512cd11ce7',
    'cdmw/ui/archive_browser/mesh_swap_support.py': '60601b0903ba8792ea0f8f3d3255497661fe16ab921a8a984fdf2d6697d7492e',
    'cdmw/ui/archive_browser/mod_ready_export.py': '721fb5b928e1672616b263244194bd7a667590664e4066c5fa5736c880856f8a',
    'cdmw/ui/archive_browser/patch_actions.py': '4c767932da1f7b7871187fcab5ace24f63734205b768a0614e7314ee0022fca6',
    'cdmw/ui/archive_browser/prefab_inspector_actions.py': '2e684e3d8d61926186f830da2e90f624433772de519dcc4f454f0c835fa25f13',
    'cdmw/ui/archive_browser/prefab_json_actions.py': 'cc4e8ca3e07af354b81535ebb40dbc9a0fc1e6a5b38a7e56a7887653cca03dce',
    'cdmw/ui/archive_browser/preview_cache.py': 'aa94c9731c3373d08db440e35b69950aeddeba971bc35dec0a3634a4fff95c2e',
    'cdmw/ui/archive_browser/preview_core_prewarm.py': '8cb1171b9dcc25ef226fb421d66b4e93d6fd4b1455811167f2a95f96f51a0d24',
    'cdmw/ui/archive_browser/preview_d3d11_parts.py': '9ddc2198249239286e4e010d5a3ae0a422d437e6ba37e4e97264b32d312d2cd8',
    'cdmw/ui/archive_browser/preview_details.py': '5be7b3da8af25fb1ace84d240a1dd915fd95965a7ad066301dec66d256bdd454',
    'cdmw/ui/archive_browser/preview_dotnet_lifecycle.py': 'afe272454489cf1895647a677a74eb47dca6f2af633742971f18e30f3eee1d9c',
    'cdmw/ui/archive_browser/preview_layout.py': 'f22b396a13bb3b04fed4872aa005b9e3702de5b2d31ac32489ba7ce6e4b64ad9',
    'cdmw/ui/archive_browser/preview_loading.py': 'f7daa38e6b39b822d3b11f7f892cc7f7fd82270512959650ff18c3f85f792555',
    'cdmw/ui/archive_browser/preview_memory.py': 'ecfc8bbed02b4204953b586f923c1accef82f773d65bc7a94a938de6a90cf131',
    'cdmw/ui/archive_browser/preview_native_core.py': '459f7495f9a3640117d508b0879cb9416dc0d53998825122ffc83f5e54911a91',
    'cdmw/ui/archive_browser/preview_panel.py': '5be0bf474d104540b853ee9aadda016724de0ef3fbe4d2b4faf214ed8f22a3f8',
    'cdmw/ui/archive_browser/preview_renderer_controls.py': '1bbb1adb8366cb82e014ba13f70de86234125e511268b232baf84b18a6863374',
    'cdmw/ui/archive_browser/preview_result.py': '0028343218a2af2dd2b586452222ea9f772178328ba127093150a6d8e2cafb96',
    'cdmw/ui/archive_browser/preview_settings.py': '632ecb2308fdded9b4922d04d50673b38296be0f6d327449fd0cab3060ec0163',
    'cdmw/ui/archive_browser/preview_state.py': '69bf9b96f7a7e98f0728f9485c4cf9c21c7c45e6de3a36ba571d46a5b89e70fa',
    'cdmw/ui/archive_browser/preview_timing.py': 'c084bdbc6fffdebe8229895ce9d23787b7e3ee7d7f6c4c63b4ae9142cb0c9911',
    'cdmw/ui/archive_browser/preview_zoom.py': '715af9124ee0d6c4c6d3111a9c993ad799b9512d037a85a8bacc851d69066fac',
    'cdmw/ui/archive_browser/progress.py': '04fea1bffb116e92d5fe00e0b3fd06bf3066e18a63db8e157613a808c02acfb6',
    'cdmw/ui/archive_browser/reference_export.py': '61193b95dd07786ac2e53aad176fc3a3afec2956682608d24f1376ab32802a0b',
    'cdmw/ui/archive_browser/reference_preview.py': '793fd033f4c734eb1be8d059c80af18728bdc5c499f4346460edd6ca33d23c31',
    'cdmw/ui/archive_browser/remote_related_export.py': '2b749620410f8e28949aecc08d18e8261003ef19378fc9c1fb8838d98699284f',
    'cdmw/ui/archive_browser/render_lifecycle.py': '0cc3ce4be5c654c58bb0ca6a132b481bbb208f6dc03c0be3a55c830a3970b1ca',
    'cdmw/ui/archive_browser/scan_lifecycle.py': 'b8b934422baac6444a4513e61b2ce6703e19a84317836c3d21e12e3fa1e9939a',
    'cdmw/ui/archive_browser/sidecar_index.py': 'dc8a7d2cbbe9ee3b5bcf5238e2246a03051e7e9dc8ffb6ca8f3c332bd2a92913',
    'cdmw/ui/archive_browser/source_mix_actions.py': '4f95479835b1af44c8e32b488096f4de37babd13b18af2e93751a448096e299e',
    'cdmw/ui/archive_browser/source_mix_overlay.py': 'b2dd84a9b7fb3e003d6d6b5839bb6548ee5689b3f8e1045d00ef6608740e9e71',
    'cdmw/ui/archive_browser/source_picker_dialog.py': '3878b645050b52098d3dd341b05528ce2ff6427d9db0917fcbbc3a42341c4816',
    'cdmw/ui/archive_browser/static_replacement_dialog.py': '41007d9b30e55b8ae188870af4795c6b48ae5e28b009b5d8f7ade8957a385620',
    'cdmw/ui/archive_browser/ui_formatting.py': '1e3e3f4c24c42400b845f24d1cb3c5ee32c80492acf20c85c3ee3d6aeda05b72',
    'cdmw/ui/archive_browser/virtual_path_lookup.py': 'f8566b0aeb2e13b2adc6071edc0b4c14d42eb2b3f560b0b03c676ac4a0fefc6d',
    'cdmw/ui/archive_browser/workers.py': 'be6927fb8653e304c5aacab54a12fae8900b936735d1345f2a368dac171fa1b0',
    'cdmw/ui/mesh_editor/shell_bridge.py': '501696311fe9e1038a8759fc534de3cfd27327c8e79e5d0fbae5870c0a545198',
    'cdmw/ui/shell/about_controller.py': 'af2eae47807e64c841912871108181b4e7b5fe93fff87e1d5205f80698bd898b',
    'cdmw/ui/shell/about_documentation.py': '2e0085e052855c808dbd0c842f18b7bdec7af578fc31af5587f633bf66f94716',
    'cdmw/ui/shell/about_documentation_de.py': 'c1712ebd9bd87dfc9431a192deb9e7e3b27331b904c23b1f70397977a980d37c',
    'cdmw/ui/shell/about_documentation_en.py': 'c4fcbd18c702be1efc494121807d89552b68b6e0742f375815ae9dff3135cf58',
    'cdmw/ui/shell/about_documentation_es.py': 'dff41680b9cdd9debd47344e89c7f8ffff6a51fd77079aeb1b84c066df91e733',
    'cdmw/ui/shell/close_controller.py': '02c6d7589c9a557874787a0c41066d66ba04e29c7fb3f5c421e60c194751a534',
    'cdmw/ui/shell/dashboard_controller.py': '29414e557d54146c1eb2272143b6069b24190337c35f3151b3971a485a7353e4',
    'cdmw/ui/shell/language_controller.py': '8d5ba7e3d37da108f180597588246e25a11b7b7467039ff40e905db822cbeafd',
    'cdmw/ui/shell/log_controller.py': '3ed5f7e804aec2b42cf63e8c95bd36e2994f701cff88589457312309a5b8dd17',
    'cdmw/ui/shell/menus.py': '1dcf44d1cbe442b2934b0b017f6041f1f5ecac6b01221aa92fe1145183cdf44f',
    'cdmw/ui/shell/model_library_bridge.py': '39daa11a3e94ac6b50279a6144d7e42f6c86398c1a68f75a6a790116544c812c',
    'cdmw/ui/shell/navigation_controller.py': '5f5b7e0e82a3f48cd3ed582878652688124759bac2e99e8bdc7de49eb3afd7c6',
    'cdmw/ui/shell/path_controller.py': '3b63b582a43e75c7175bafc62b893597f622f1b6e822e05f022b678c6f26ee10',
    'cdmw/ui/shell/profile_controller.py': '694d476dc8102c162b01885d3dfc6533a6264dbca779e1d7bac262cfe1ef34cb',
    'cdmw/ui/shell/responsiveness_controller.py': 'b6ae4b10d76b5d63c1d29d96f6770b675e62521c7d1d441bba6072630f2c8a43',
    'cdmw/ui/shell/root_layout.py': '92ca70a6b2286421ed6eabd19e7fe08125239d23982d650be0c1d031ec806f23',
    'cdmw/ui/shell/settings_autosave.py': '53bd778d6c992554031c5129e7c2bfa9780c474f9b59d4eb776c6a090331b15f',
    'cdmw/ui/shell/settings_persistence.py': '8c5e89522c3c4ec32efbce8a0c269108bf2b45b4a8bac78e1085d5d7b6ad4ed7',
    'cdmw/ui/shell/signal_wiring.py': '8818bcb9988d6ad99331c5f6e04cf7584ac7c32ee3333a92aa5888879b0e64f7',
    'cdmw/ui/shell/startup_controller.py': '76cb09f2698f348466861088067b2a279e93b07f78cfb0b7e70198dd79928121',
    'cdmw/ui/shell/startup_restore.py': '2b019a08a8d94b1cd605d1c19d4f4dba5305c5df0db9a9476e39b80c5fa1b6a2',
    'cdmw/ui/shell/support_dialog.py': '4c5b8d27ae4f45423a25481ea195fbe390cba57cc731c9ac2e910454ec773011',
    'cdmw/ui/shell/texture_workspace_layout.py': '286dc5a23d749a2cf2a5987818f6839b17382fbf6ed8333b74df561f6000d46b',
    'cdmw/ui/shell/theme_controller.py': '4e804a1afc6f7311e447c36dcb02c9d1a7e7e89d492a605d2aa03ec647aa698c',
    'cdmw/ui/shell/tool_tabs.py': '9fc9b1ad8c422e2f4d510b069b7ef19426a2c43bf01b4d392007a77c5bcdcdd3',
    'cdmw/ui/shell/utility_controller.py': 'e4362c7393a1c59c02165a6c7a6362f44fa653d3e3c184077366fecb63ee60ea',
    'cdmw/ui/shell/window_bootstrap_state.py': '77d2ff16d0d9fedc2bc481b08e2779deed512ff51b70bd3a9c08088bd917a2c4',
    'cdmw/ui/shell/window_feature_providers.py': 'c7342a1404eeb73d9f22144a30e0e72a7d8d68d34e8030181e2e98eaa877ee3f',
    'cdmw/ui/shell/window_runtime_state.py': '03f766c90ece19e2da978f1650b70a74a5b83702103b9933bcbb3dd7baa9d308',
    'cdmw/ui/shell/workspace_controller.py': '1939a8b5ba35b6df8f9c53ceda0a43522afddb180e99ee6f01959859936a35c8',
    'cdmw/ui/shell/workspace_layout.py': '5914c0d72df658aa8e9744fac59617e541d5be7a6f7ba15299b9f78cf914b684',
    'cdmw/ui/texture_workflow/asset_authoring_panel.py': '1883d70965aeb62f0511c0a630336cfc3fd6e09029832e69706ef8bd1dd30f65',
    'cdmw/ui/texture_workflow/compare_panel.py': '40a02252e2f9e8af28b02795a525b635d24161239943ab7440ff5ee7bbf46265',
    'cdmw/ui/texture_workflow/compare_preview.py': 'a34869a6165984b9f6d8a09a0aa63c137065aba5636167ffeeea9e098494b47d',
    'cdmw/ui/texture_workflow/config_collection.py': '647a795415805622dc587ad0ef091d45e33ba0062f42f1cbbf5bc959b4ae4127',
    'cdmw/ui/texture_workflow/dds_output_panel.py': '806c0e2e4cb2315a59c4bb41d2a70afc84cfed065266cb36514bdcf51212f38f',
    'cdmw/ui/texture_workflow/editor_bridge.py': '2ec7f7d9f01b3477c9330664fe3968380a1a89f62ced0e46dee0d44dab664ece',
    'cdmw/ui/texture_workflow/editor_handoff.py': '97a2646485833c9f091cb7c136f1d328280ffd992886f0f833b2f17cefff6dec',
    'cdmw/ui/texture_workflow/paths_panel.py': 'cfead75e031d45390e95dd696b41b0b0917d215e54033f8022764de72a8f0c7f',
    'cdmw/ui/texture_workflow/progress_panel.py': 'e073b635cc5725e90d3bbbc16e88fb7ff62d07364da8c37659c7eadf94330466',
    'cdmw/ui/texture_workflow/settings_panel.py': '1d30484518a4d03b5b934c96ec44c7a0f1177bec12be1dc921744f6cc6ed95b9',
    'cdmw/ui/texture_workflow/setup_overview_panel.py': 'ebcada18c07ba68ec0c13e3364c60ac6b9728c79c81ad6e07956d8b289f30a14',
    'cdmw/ui/texture_workflow/setup_panel.py': '80bd9de6810f2de6469ac423ba2823f78734f9e77507e3312dac2323de2cbf6e',
    'cdmw/ui/texture_workflow/shell_controls.py': '15a601003d3f669b3553682cf8977b27d3197850bb5195a116490c20106ba846',
    'cdmw/ui/texture_workflow/upscale_backend_panel.py': 'e0c85aa60a5f7bd3dba95aabfa0d0c8f7608962b6361aca2bdc2bb8f24285676',
    'cdmw/ui/texture_workflow/workers.py': '832ffcb12560f1c19127aecbd8ad5eac9953e3de9ad86f4690cd7df3a12a22d7',
    'cdmw/ui/texture_workflow/workflow_profiles_panel.py': '7449f354a7cf2a5c853e4e8c60f9e6606577a1d600f512d5284c567df3c97ea7',
    'cdmw/ui/texture_workflow/workflow_profiles_ui.py': '2a0ce1d5289eb2462679c536634cc52b57fb80c4362762a003778c590b74f195',
    'cdmw/ui/tools/mod_package_retrofit.py': '820894bd8462cf8bb950aedcad4762b62e80cc588859fd197a99a1f348b7785a',
    'scripts/generate_window_feature_provider_members.py': '6d9aaf3c3cf6f0afd505bb1c63f96b57f9a97d9f37fd342d3c9aca48b3053cc2',
}
_PROVIDER_MEMBERS_B85 = (
    'c-p0X+j1nit>C}RbIn9cJ>G|To14Sl7~37w<1-'
    'PvdqPpFN=fN1WtJ<m)GeRzzb`H%lNS&KWk=X<6_LDv00@G({Lfd1<MZcluH!fR%i(E!8Sd^c^XFx_e6v5S<2>CR=4rjmr{(`$-'
    '@$*rXP_S#=6eG9(LwxW{4!2oefK|KJrC>Cd|dFKch~cAzYcf4^XK_EobIx&zxwXx-@C7-{qq3-'
    '{J+L;{u@5gr>;y{oT~4|jr2TB*SmH2vVQg5``y+$!1%9s`}J<U48z@dUPgq5B@{5@a`*J<i`24Q&*%BFF3`=oKRm%m>)rXZKMeG*&-'
    '3Ne!)gAke)+I}9#5}?4w#~w^OAm&!N7lqX<@K;5g1G|8vU@Jjw9k9#+WZWY}zd?{9!&Fhs)i0zdmv6{dGJYx1qV&4~@8Fu)}<Y8C@?I94kPNrvbO'
    '0=askKkJBEPJ|2g|KFmmh#FaFfrG?7SK#fmvZ^IYFd;zv!mSJ_MRsj!B`wMInVC6WRhv_&>hgZPg;nV(cP(MWMcz_kVP#_-'
    '0%d*~Gr~S)*JnipKuv_zdTE{bEe};jJug{m^WgI@=eIBPHQr){6;4)t?2SCjDC7m~PaNb{rZTCF|$JFCT$vcfOyZ~_w1_Up|X*jGYJ&x<}Oaxn!9'
    'D_&GyT6`3MTD^KFOS2z_`W?e0oc02|1B%f$XDNei;YjPCY8i*b10geFsIk)APYDWJ3KT_DG`iS38hS2B?|jYOk$;5T)kB?8i-'
    'EkXjORBBzd3A>=8g#sn<cx?ITMQ>0MlAlKvL<X){k#kQjwr^CW7B<CZYCNi*ZA(jkxEc>Ji!)cHKXr_%wq;`w==61D34(E1}a%9>Tu1rea9%1?vW'
    'F6uDL_4#@44+#-2Foh$QqRZv;{tTGG{eoZbp7-'
    'nFiKTT8BzN@yWV3z0O@Kg{>q&OTC(gE+(HEZQVenM6x0k<bBGQZ=;~XvMG2poee|AdbwbhA{+wJs7|C*3xrkRw&Dpk%e!{q{U8Cm=?Fd5wskK-g_'
    'Gus8aEZ`SUfacSnf5Kw*GA!5A8fkFqH(t_Z+Pf%0v<|#(2fwc^j73YkX?zrr7ru5{6C7Nt0UIX9$#$rJN;@Nwya7XR+KV^td@o`4?893~*vQ=|MJ'
    'kN_5t>>&O+pAXqUp{dWRv4nY|uBJ@OAd&?)l_2@g{vBv7<hZyW_Y&&5t~t7RlguHIAh|Sugabl*)0*0!5}X&Bl%q>&6&Yw=+;f-'
    'xhRYtDAgOz93cbuwQW|DOX_2kKCYJwBj!C|A)u<G7gy?D1~~w%-1t$jq`XIGP{xlxS-BS%G_-ga;3W`AQqL+;SR2%!%6KrQsvV77+yn=8oeS{g78'
    'iDe!mPjD~1~iOQY$V=J1^h)|b08Y@2m2jGJqwKF1DKBK&Erl45eNlRC|99qkY7)26Ffb=DuTwRWa}(L$aC^%<1J2<$jsP_d5N#SX^l1;}YedICN8'
    '?mT{ZMiE|TAAh{JApr?@FZ<IKQHf9>W#-'
    'e%Q0o^i{E0R6ruhlqZIK(sI#X5W)IFol`B*X7xi$Ju?=0lfCRt}Ft1;RisafGO$$$Wp06`XAwI!Ix%l`aSGx<Br-aWwSD}0s$Kkb(k1}$?7oOsS$'
    '9GUhU!14(+P&8TM#ygsgpqBaY33_AUOH;_MQil^9uFBG#ZG66fypB5t1J1PI&w*P?)l6JSkXdxw*<awqP`kxRp6B!RMDJSVMw6v02a_zI1^5Mif4'
    '(0s%BI5mmB^pUK3Q<OYZ9ArdRB_;phpwBEu`2-4qe-'
    '4r*RXF*$CV$fKL0@`MTBw&@a>~3ZT>yj4I9bf_m=5a6u(#fu&4%1ED9k)BgEfm}q$(&uDBqpT-qTmJFS#)WHsnMkK_b0|qtjWq=#Y*T|dW1bX}F#'
    'FpeI(4PJU(EHQf=cfTwy~peRa%3jv_15PN!<??q_$2c+ACC_gd`%GPf>!8y^e<aa!|{3=Oz;V_8qsN7YR^KuR@t}4o~`fRcr%I9lxh_I0UHe`EY6'
    'j+Y0~afUx5v&#}Q_^f4$>Z?i&#X+!_YoOY+`cY*BT<5)>Z+uS;~3O67X_0ixDj3?EL{X!A=@_S0w{uI`i!g0a9KpJwkxAW4ccyx8ewfIso^QaVtp'
    '3ptI8w?gJbTwnFAc&O@|wQG@2i!jW4-KN4e`WoBXw_gSl=-'
    '4bXA$RSmo#xF#W|P!4N%O0RP^FFQ?tXuK%mm1%Y5qLjT^D$hxsS)Ii5XHZ(1ei#xUC1V`Vbo|oY)W_C>N))j5Q~k0)dIAi+ECGR}l4q6#knUJ<Hk'
    'g=gB19UGgX(XS>pd7hF73>*sImxnfyP3aJj<Sh5Vn3gkSU5}%sFX`s3g6QC&h5(+gDmW7C|$Tbs{iAWoaV?>mV)C@$?wU1W9wUCgB@eKsq!J!tGS'
    'EcWE0^Or^HWj;}@ds=ZC2n%xBj+0BDkoSB>YwDMi+AOlN_Qu_-U%CVcbq3+nezy@(u-'
    '(~3ZOqB<Oc#&>{971S{+AxY%+doTpgPAmdbkmd}#Owllh+vgCyF38yEPcG+X&Mo((<-'
    '`3j_S=poqfD2=mc_d~u59<Iyk1QA1`&)kXj7;byZc{mgXS<9Su?FIHsp?87CjXTZr!Y)>|?fV5G{s;i_9+q<g{dTyFIB(}_7di91Z{bn-'
    '*tjCsQ)M+DxYfEAZx{PKf&o1^X1Y6~3?92+l@M%$Ytb#)>z7TX6d*RQM>qyRAGjak(*DYHEfESiZ(JW9#xK=ABa_+aJTJjC@UXwH^A|v#O?|ufWb'
    'Q8+f}~D$-tIf+#@a;O=V5<F&FBPYo7c82pzHi;n3~-#*ZUG29{uLjl<2>5^3<X5y$b8r=@i><Sp~QlK${$udb4S?)}|aQ6<BD0*TZmTeAtm}-'
    '@3O^bT5zDskDnm&3w`)XS%r6D!C)o>fu3Gl0JCYp8)g?YLYmXRZ)^Zwy$!kFKRNp0Z5NJq{L49GraPzOA<g-=y%)BPAq8-'
    '=tgtW7wVz|qF@#kyz;OY+7q9haeA1U;Q{z@nwNDv_=ooEWSm#;&Pi`gy=d;4U?-'
    'k?v1QzEBaJTmhoQLXREYK?z((BI&57bzUw!w#O#3N+Y+a?3#m5m`6Kbm?n4bxxr8K(!zC54qrYk<uf}$UJT#0~Nd$Pm`f~U9fQSH3XJKfplW**sy'
    ')R%F&g8HtK%zqKg8)(IKUQ){+Ow>~Qyl-je{p)GoAJw&eV3-!gxE}8Z2q*JiZ3VS>p!vAPd$DJoQvq-'
    '5@L(kR@=9@9g3=rSr!9zyMI7A1E)WC*n}3=Q`%`^NU#Rawd-v@mk%9+62mq1i5&V-'
    '1_m%fD{L_A%@>ekt%*E+A(oS74+wjNvaD67XdU=(H6C#jz#ACYBwc9-'
    'k_{xT<V#R%f&Lx)tet<*d2`^0g5SydI0vlK*Dxf%gkUEY30(rnoIM3r$oehcvG+!`g94AzP;f?5W_s{Eot!-iO<diXD_^5J0b)Xa_lbT`gU-`xZ-'
    '=bqGzaJ}Kvw<Xxxy5H!;2mo4lveshM}9`kjRx`pM#=f|zSa@U?GwCo;u?;QXHB5oZ4J~QTNor^)577g_7zyEfI@*#uTypT=#@Jmp=}aI20V{1b2!'
    '|3hzOBSZi(OqRO_5zp060#d#a*>fG#t~G|M2~)iTIGc}mOhNPqHr{~*H@vb53{V}xZzlvLqXgZ6@s&j5|mz2@Y(;xdO@M-`ZlBI8s*JBO2_1-'
    'uD4I>U6b-hk;$^K$N{0jz?#Yjk?big&L_nTOYN;MMUE{BE3W^qusb!v{Vd<?y!>yyuGyw5BwwV*PFF=%L5H6`R*<QWs47-'
    'a$!y=c`pfS~U(`KQjv1wpcQ1nr3D(pH=4buR~CD2%rur*r!VTCu&QlEPu;M-'
    'lwR)^?K2Bd9WReotnMr*zUVs^j`qpsNlRov2Ln;eHYMO`%Y_C<Sp88Q>kuid<K25sqMAyJRQoA?K;tQKkT|4Y6g%jZ;F@-'
    'j6gmz1SbSr40i0S=YK4~z}saT)u<!T1nh_U#ipm`(3l<OY5y{RB5M{0DyhJR{;;PKBAXYyRGqK59rOx9G8IXjAM2O&Q|z>ax4@Krq8hgu^481sfI'
    'dpcY<dxF;r@gp$*zUk64h*5!k#7Yyts+99<g8Ntsbo><nX~Y;JXwEe|P%=r~UJAXw5=+#>l4W`iTs$x0}yZWh%Lzt&>=bz&Z%JO-_Bp)Wdmi=7L?'
    '9IOwA<BYpSMfStbV%-E)?4i>O+m655nLqSY_#GNK5!;c>BrvUadL5atM-(e-'
    'QQttliFr$9LFP;85Q3d50<c!=mubx?T%t_r2PT~owhm@l8*ZH&h9^pHK@i24(v<`e6g~^=8=W$JQ8n_WD`Z$V$y{&+x7GeRwCC*!<lmkAxVu9PU)'
    'V?L9Ve4B9LW%`qxLTwT{qCnxCQrDIAP-'
    '>IP$zO(1Yd>}UoYcjC1q{^_gHqIb?cF!DAWv9>%<zAUIg9k4@N!?U!+u_3>SQ7T7V>&BbYP{1eQq4BHyxiKJio;IR?HV)9Ab(9cu>5hcKXrhyqiJ'
    'k)ZR>dr(m&vhjQ3qLFW;$k-Yk7Mbk)$pja^0e{RLiPeR)v1;2$<2G7%z_Lu8;WQ>uS)|3MHZE<-'
    '9P5_11W!Y9sa$Gd^e#%)m_p^vrc~Os1^wGknBM>+KL!Z(l!-mxwhW`3`Y{!XaSqKQ)xwrN^AoT`t&M`Tg+@x~5{v5tPW-US@$ekmbt}bgaAMa;=q'
    'cHFfp1eOLQ}cmaeqmanVd|5WgGQ`>2WxU&>W^b>?sN837z<lm6%Q?+%qO|FIF=x-'
    'A#(bk=sYV=q23Q@~?PH_>ie(9FBv!a=kqXHxpa4td>h9)96Z`FG+V<cJz%vV7?=y8^I?fIYO(TC0lRi>AeO0Hp1v3HhnwmJgIP`!sRM)G)cC_W>t'
    '1D$pDQq+jO}z3c;!rX$c^M{9c40eP3>%9-'
    '*IZe%e*;k*30GGjz)zvwXNeho8l%IiE_<1ma`UU*pKkG%XycCqRH7<z<{6gM1z#R9WdNh48UF{0f!Ws^r1$Ik(#T796kXl*xG+_5m`GUwzJ06%wo'
    'rkD&T322h`av7BkT=K6{<ICVuCtg@mEQd?058m}k|ob+j@=d-K$a9f9A|Mmo=z+k<%3aIatPg}6T9BUNjt~uh4?T_x{i#?KqUUlOdD#U#g@-'
    'b#3dq6(}SdE`{IITkVt|JB=MAbIlDZudw?1Az@$^F_tUoOeuih>YJBV*5PqG*ytV`r>HV5TdhU{kl<EHP|?ttCQ@QpYOs>{4{sI3_AgW1uzzfp;*'
    'BkqOOWu_aGz(!F)=8AY#E?AwnLO_`v8RzcUnI99Ww6Llil<G`Ef5$!h=opHaPCV!1f!SLn}^F|{F-'
    '1BvHDT6f)xzncIz|raoMilj^{zz?VA*#dvOc@XgRc|?<8Gv+K9>V7)EA!uFxj#!V?qHFc!efX70+Dyz%FYy}9dc-A8i-'
    'RZ6`){LyPxAQ((KNZLnhaA(D^^*>%a_`-n^OLsfrm!)x0?I#X2kK-ap_sF~X^UO|5e<J>Ca>EW5KhkhEM+dIMG#x9cK}-'
    'j&(Oz)l2KTv<t_Yjf>XW!tDK3z=BZATQWtD2a>Tsl|}^Hx~=j^_;KC87ASacG*&r#&88jH_*ZY5OD521qAb%1xDD#9%!&~`@oGf`FXNt37{l$2b!'
    'gLHht8yF7v9)JG841Ljx%`N@;Jag*@6!AW{EEWIr?UOK+C&A_U&lWLAS3M9TsSJc-'
    'KKz)&^UrOht4`KwQ`&ep;T438LHAq$8t8U2maOp^#F%DcqS^@RG`QCL-YYb)M^e81UCZFmVI&**G1TWgZbF{$3@ws}u^vF`A72PcMBNuURKjax+c'
    'Wqh3WOvZR)^cjfX36S)B1(ymivW_d|s{7{^Qd%!Oh+ptc?aOHx;6}hy5MTKfV0zSR!iFU%FrW9Ms~gmsYy~nw2-'
    '|a=<yN4JWsf<$T!*}r>af&HNn)^%^8^<4^kFuTL3+;mPg1=kWks=6rhlm;^Kpzw2|8I%x{popWG5BqYzotGh1=!njZoXd6F;a8i<}HfR#;11hrr6'
    '@RO;I(D+5~A-dec@%RNNVBC$4q?$p!5&OmP!PMW-JO4}wG^$?L=?sbUM9wzMKZ~H0UbvRmuZ=X=_I}=r<Llx7F1EHx&v~-oa;-'
    'Km<Z8b?#0Qn(Ra)S61wHP$O_(2w~U@L6;BDg+q-tbV>r_#RQ#$8+nISexsApPSnT_myiDwzoP&lJ8_hi^bZOu>ldc-'
    '%Z)K<~TC1N6fA74II088CyJ<&7m@7uJ$wdGX4k>JS2^#%bM*CBrIq=S(B}m%*?d)JdH5GoF`QeraoorxbwXI>vru(sIUiUju1l`Zn82MAj|o-'
    'EE!7O(fQ)ft`utOmtw_Tb<s_`);K-RXBmycZmFxB6a@s>B~>9U5nF+-Q_pW!s7rIx$(R@Pv<eeFd=mCW(bbVV-'
    '^$L>iTJ8W1pW*ulCH$mAKnSb?a}cZCJ<w2<GUsW3VfISz%g@ZizA81WaQ$n&3sKj06O|B|;Z}8=nb0Py!$8kW(qw&{B+A3Y;ciIN3*L8x1jTLY?5'
    'g9!1Ujs!ndZ4hrriOgmXxk!?e@kpvAC)uyK|Dt^<Jc9D&VxHSf@iwBEvXbIdTO;#>#Idhmb)m71*n%Ay`)~4zzubqd}IHlQfF+uYO*U(Y+k~*x!f'
    'D~ooFsa?K_#{3(sLefq!ijmsBDdEm)jPKY$?i2cxjEHfr{Qr=uF&XOoedg*!W_9c-QE5L9;Em8{&0{|1ICDOj}*AHV}E_Z+_W7}YlJ)v>#On-vH?'
    '5nrJ$GQ_IVfR2~?izpn(IDIE+FvP=yk#kOm<<tUgA1QM4+?aTL9gDUloKIGwL>hfQw_RcOD9oImHE*Fj&8M;K)UziE6CwnF~22u3Iguu>97Lv;BT'
    'B+v%WMXz)vknGOL+1-5IB92Z5G%&Rh|7M!B^UmA2-Y(PH60(z|dimnbT+u<fo#MwN0nC!JL;iLMD)lI46-'
    'K(C{h6AyyV=7PZirr;%D9ZPasUQW4ZQ-L-Z2!QaK|`PSW_`7mb4?={Cxk95WB}=X%Z;<y~Q^I6*##%pxcuOMfq@@cT_G1TdQxc-'
    '8jdNbsKTH>)mcUl2rO62_!js{25ymKaZS|Vq<t+g8^H}h|d{(f-u~T0GAoew+{1ImS|MfMI#1`yfYN2&FB1m37E}K9Xf-pkDdXh6UYlnhPsbv`Nz'
    'kE_(d_5#__6xJ4pfMx5llAHs~`5L>W4ptHn!2n1*o&jQie!B@2P<3`B0ki+!){q-'
    'G>EBXjkTgN?5>u~XE3kq*eeI3Po|A+`Y*z53nvVaMcz9pzMX=AGg@A<C1Yso6cb2L6r`q#Q7yt^m1zU6a&3h1AYIaK=C}vq{l;md2-'
    'w20lbGYia=<3S=dDUd4{L(rA!B?MmN(x;62$N|G2L!kV8=<hSDjA%ul7#>vmwUE9D&jy|O>xg5hs!N2+@ku5F@*v(uR%=`V8!OZw>5~rDv-'
    'a<xALe@9JyrVtD+Dm^X>f60VbaV-}y2&sTZ%W|-C+3U33#<RFH!xSG;fxIUNL7bOPjC&kHQLTTbrq+0pp%J%@)tY|hgUd$Qd|Pa4-'
    'D~(2apd6jNV3n3EE0HaMAhUaVp9Z9+4LcEy8OT$k=W|4jfWDAhW`Kbj4+Eodz(HwFAZ0Y)=DzRdIrX>de@X%DUhqRPr4z+A41Ou@bOcDnk$KOYUY'
    'yk@1tM&onYXov2~CU3j)GXJ^`E8xl=BYsFrZ#PQPT)>IJpPsim0HyON6T#A>iyGZRRE!^3KHQIzNke0vT9LRCMA)m{Z=_fysyu{zir{=GZzO&^7`'
    'A?lz@GgH$S0-2*PAf~wg_|(2d9Aw+r1zrSzIOA<dpD*{tl&_1SlP5uQY$rnsMd)UOe&-iB;g{Q(=@Yy`1Oy^U}8?Z4T@Qj+am-Vc}oPAP>wS5#AC'
    'yqiqfCOaB+W8VkPggj7eBQ+Zm5&y}6?lJE1mS$h=w32~!H9r_SR50ey&m6)@zol3{#Zx)3v+&xK2dJ|i&fZdB(Xi*R;=dQ;8fQoA=fIp$22oeG9E'
    'w^wZ0);3N|+u2y2jdYCk+K2jGn^O#wXd{az!@I$S%#X<NY|J(!e3a~(!8VNMd~wO}K7huC<#jsL2{?vz?{B4Sl+!+1$F_{Dj=O7MqPY#H{S~r4-'
    '=QZ=u?fFW+aIAx33>K`#nc;FkSS`N*w2|7v+8x_7e0@L_?TRPiw0C-8j(gYPSsHbceC8+Cx&ZtT*I03Gv!_1pJvXY_1^jB;SgvptgpS)I-'
    'GRz?8WK!Y5m`p4`d~hDg>*mFqS>FPqYj5M#NhY+Cg`gowQS&3GIdrwDCfd!C^bbhgU4w@rcoj1(W}U+W+R7b@eLkDk_A@wXouc7g*h?`~so^7EW%'
    '1?BirlvwLQvycr&_*YSCXYD%z^&aD8u%`_>G9@zoe@Q{7RXx`+1E~~4fgd9GxH8O)fUf`nXf>!+X+E>9{sXC79g;Q_3)y8F>Q!1-'
    'tFTbU9E@Ee<fL_eo>BYYPU3l!kqH!a8$l5@5P4;FjRXo1wzEnNEgC;qVvL~Gv@dL8pA0XV5ommd771PmMQ<vsfVI76Fuwy!Jnar+4gEqV7X0U4aG'
    '@Q=)>o@MlM{NBQHOgZ4cucHY?8X8_$7;OKQF&Wj{~ejf1-D&gkM-'
    'HTOu6h64sx?4aYa|&l^P5bPl*k^RR*Wfs)}u|=hOCd8<Xus(9Vkb_Wq+5K<O|<13l6JKzu|1#jiIL(50T?a^Bo(V!ig2aSdFCU7kL-shYx;l^%>*'
    't^#(Pxso;1BqM<Eg@2Ce_!1oNQ0Z%Y;#(nN1`|VXMUG<Z7BPZYa%e?|uEGJ?wJ-'
    '4uHuwJutT=CW!P#C^#V;}Z_RN*lNDS5&N#NyMun5Lwlp6Eq`Gpt<is4P+n27i)Af!@=o0r2dC3R6V=Oi{_=v(P-'
    '8_`>46P5?J5f`mDy&($nm&hjTHmS*sHmD2*w03uzC6?#?^N>F&<B(3JiD)IOixM>@U$`>#Ids@W)~>zA<ew`u=s-HRVnB_+Ao5aF)T&g}rXe$)O-'
    'y2EZyPgpG4fmGMW2kbakrf@?QGdCzIUBx%Ue&DZfVgc4D5{7%kdrjuBrg@(J5n+VRk<LifxKnHqV5e_m`OZ%A05fwsC(IzuMU+qalRvSCTs!U9Z|'
    'sWXa<|BI)z&bqs+e7BHzL`oUaB$yIWHJ&v=GfH!RyFI38u^kLLNtZPy6%mQ;OoF$^1fd1@ZG~~M-'
    'cKu;&h%5L0z7{l@&mej<E}Pz$v31S<s=e*%(>0)ss-'
    '4xb^}nH6LsVtji4S60(9J`j7g$#Ju<{m>f1!pA2*9F8oj76hbUP;7G1bO)v4cOlwB{RyEk9yIvjWO1nA%p(K!UEZ^#omX?R`FTorf)4&O^9f{H%P'
    'GRTN_RK7vjrUj}WaZUhXqML<@dLfBU1%$kF`i)c7W(X}Ee7hmf<e$Y?jv67|uOp;h>I0uM4Tx0+@REFUE)CnGf<bLVu-'
    '4kEEKi=FF8^CHuxMDsIYaS&g`KyrPn>-HRjSqPwYPRJE6xhzeIs{&-WO08zhQnJ0+|mlFVB4?@s3t3B`C_E--cuqXS9c0e7k}7=dDn5m#!P&j&LM'
    'y>UtYam04s9*pc;8J!iUcqy^yI8Cns;AbD+o^ffXV&6TZrkCTzFKz_hnUN-?s-'
    '&M4w~#8*ogTDQ@_sAl?Yh#HGPwF@JIRIo}>vkW&0EF%xUm4kKuHJ#8nIahg2JgA}l12?P3wbUQq$MalUB4nh3WiQzhcv5FZ2Q04)l@3K)k22Staq'
    'YJ8jq5h9+OqME(P3tbwC_K?|LNxD1GcK$&b_!)bY4fq>o>6N6x{1#Z6^qr60$TlC%`N&15A3zY|G&kP~!=WbDSznNVXP%uk+*M$wvSbWv{e;UCc~'
    'uhm%*gl<Cjxh%3K(8joON;k|P~B)m?MhFb`4qkGr6-'
    ')~uJ&xZCOrE^bBlw#j@6C=V4{&<p^kee#jr)P4mPkkl1GgpN7Rtf5KqekU=W0ZO*tiGD|Nsy2oH4b*9W^x`XG(in?XIX@G3DyOec4S^B=t~Zl@mn'
    '*me;w9Fz)VzrE=ul!PN)8fK1;>}p;*qZ9CPM!4#NXRM1U*DROIdnc6`jH0Ch}Yq4(EEU$Th?%Wj%(28EpUD<2*n2A-'
    '_X+8Z)GCIz2|h2B5hi$iqvO44732(uu!%lahclA&DF1HO~9GD-f*;(5Py?_h+e@EDKl4C*<Ur-'
    'Nrk0qYj!v4jT1(H{&gU@XkzogkC+Q(=LLW*yvif$m<08e*ex_q;f+qtT>0hlyfWQ)1)osKbcKchcd)Y^X0M6!K59{YhY-uIq9BJSkN0G%u@U5YF#'
    'H7=f|+#Ok1GpN){<k(|ALV5#GK42&cxzX))CMXsErSn|cr$`*by(@2{_x_9-'
    'BtlF`?Mpo&PQ#+g3wQx&^h_DNYiZoWmrk%Um?A?~5CaSlwkX;~~`P|CooyVj_Er42M^L3S!fnTV_P%BN5G%4U_fZ?)gO3Jb-'
    '>a`wC>je!LcuHI_H<>H~UPyS43GwjF#v~WnlTS7WY4IzeL5VX-'
    '9Ec?Jw+@;$zyn6rtZ#B!Q(%P(*&1}RorVSO3~05XpaTItOS0~$9i<iug;aKsGEO4UzfjBf@Nl~}q9_rLUU=6$WRO~($NQw_tn^`i>4`qwHHK<*Y('
    'avzAA<o%!o**x8O?b5Wks@-'
    'yP{EXggyG5i?9SV`m%lDypljMUu;kkGL4Yhq>oSuqUeE?dD_!9O}cN&T@$wKVOfIH?cQ&2`2IH6ic1RC;?w%%ZtBvLCOHD1AoboA6^~F=M7|7Gfa'
    '4JK(m#+s!oz5(TNT_iVGEaVMXgAht-HungXv9Gb8U<V+Z^7s{0;<bc<Nofg`k3-'
    'CDtu<#PzEKQVW<mEm}UFxQb+El}I2$nabE1O6zQqK*Dm+%Le|f!r(!7U7|F`$0203kU!yv6{x?I&d9rj1nUv!1`GpjF<9BzmzlGmLInP@S(<N}pN'
    'tFM|H8{CBtu;~K7TmDQ_@Sv2V9vU<m>TiEU(L8*(>xjGi_LzN2y9p!tG+S`=R=t)_o;#!DS^%heY~*7($dEmAM<2*d%N-'
    '26i^KGw#uU!T~leYjcTNK6Gt;Cm;MrT-VD&{Y2R<M{EZHULa)Yk1ZB&&g95+&QKymd>zY{;?Y2vfI0hb#niavbYrIiJ{!vyw9=?V)KOPE*eM_oTv'
    'FRvyg9|oVVuWB=9eKoC$cj<TSk%IQyFmA*n!q`TKm(7AKPAb?4)rY+bFfrzc&m@9PrV#Ro>SiamgbZzT`tH&exPnf~hQ$1>%)r|M)3O{*WT^7V*6'
    'r;wUK!km4X*$7vz;nxV~|P9m`4r{&Fo-'
    'h0C*qe~{N&V&UbYOi<a`y+btz^Sm|DCxb@EuS$_=}mycm|+<@&Ozs)HMpR<7`CtW1}RR}zRQ7S6j0xtpclzh5fq~UU)wb^WI&ndovh=pxxF3ewe6'
    'T~F;?XCA>BrMJ@nkmuH78iAv|_Xx!6n8R(9zVp=N>ADQQh74xUZoaZ@jSF6w(u4UL@zsvh2g7UPPECIA&XgG>Ax3xu{m?^lfhJBHiYQDE5tNP1Cu'
    'xA=`(Otv)cBuzz7fpP0$7|h{WfdhY3EQ*VV-nXj#DjT~!vUOYw_Wm``q9^G8f!{3_qPU;bKy>`aRd{bjIA?$ql~!)A`tU{W$BF%3yh=sDL1nqEsK'
    'XEA8u|815VS&ggbA-j6?!K)pPVz@_%`Y~*4?pc(`5B6X`#)4v<6Y=)XGW!GfL$j4VT&li#exNBDOj3uXq$3d=WynZ`1&v(9J9cqZ}irYoyX-'
    '0}AvkOew9H>RjC8E|li?S+gtVgBA*S$<D+26v)OrOb9WeS6$Ig-@^vRTlm(9Eu?vsB87kTjY_ESrdXvNg`}-'
    'Q9akzCk(kZhH$rDFQX8`7@*$i=D9Z4!Ny4rYCdy(e8%t|zX%F1D6x$>l__OV<ltDUdua-l)X5@<kRYdH2G{n`6gFB8-'
    'Eu3tAVL&e6qw8{su;4(I6|l8-n<#u`w{ZgXw4QU`U0%(*JdnyyoCi`>OYPqT^NQXwy-pl-Y=w1yyU4~&jyf+*^-2T$-q`S&P9*$@k!F~vgr-Hg>L'
    'Hu(g8mbuFWbgn_#Bx<ogS7-'
    'sS#x>Np$%1NXdNxLHHx5Ovr$EX)!Q57|6j*9@ybwT%;bu3Fs1g@q2v?LF>h`OFpl7Ty!V{<#(9PJ0D)0ua`lo9K{Yme&!jtSc573A}{{rmdqRDYt'
    'cs=<kHQ>%;Ud7<_$IAIZtMEjmeM+lXwh;cP^i5U=hMKFiOJc!Cvnvr~80f3#}Ei78AK`EEamrja9y5xMn#jlvC?^xa~TwLGW@j8=c_;AMKKUKq^*'
    'TE+U<b2#QJ{F-4$T@KXyF&2nSELI$)CUMVR)%qVVug`+<W-^;&fNd@sEFCeOdLH=qc-'
    '&)M0lJS4}&UAt*7QqfIq&P;TQut`zQL{o^ijx2y7gwwDKn_X1Nl`m_3zG=-kjwrhpr<%w?b4-'
    'Jw)E0Q7t#zuzampxa$6w+9sAZ@>=ICh4K*J#Z(zM$=K<bvI=qFayR`$uN!}9dmNTqV^mht=+Yx0x9D0rh)0t~JzdIDLH=ahF;@&RL`&1-'
    'Nn<fi|tV@4{CS8;El{c2_0=qNLAkczRe;L^PA!>}9tD~=R84imF%w>zI9}*kNR>AdKsWvD-A-'
    '&vE2n=QKxvdyul2Wkri)$|8O520%j2OrVvf`t)gf_O+op&koXvB2mxrIs$n~DoZB?=c`b^_AlMQKVxHO2TUaa%?TrEsE|-'
    'Ggj9d0Pi^;f)H!X3hLokZReyAywmf8IGl4G@tkTf|nC?n+o!ZUl?(#PtU&4<_;MUYuLip2JRX(r_#BrqcMIF)4F}6W*~Ddt6O3Ui8}Q0b+KOvRl7'
    '{Vww(HGEA+~H9fG~~Xy*q38cqVxDJWw=WM+#XeAYJCn=^S9U|en)BLG=F^QM?B1ziMO6e2zPXCYsm<~IEx9UOAnz_|q4B9{5&{!`*Nf7pXM>xQ%t'
    'Y(j4baywDGGt;1v72L~<%nE<w#x^UkQy?Y+b^UFeP-'
    'b*&eq@+BD}hovc%J+RYFDzsXBPZ8_pv<n_6O>;IaPj~3}2c%LH)V`+0)qz1B7ZRw`!#l<x6cv*U{Zg*W3Z(@8cgsgZe}jN;SF%W2{u1Wq+7Y$?wb'
    'h8l4U0_i%mlXKoDWyJ6ek*YpA~hV#=Mb*FLi0YYO)Ega`sho3Lw@+qDV{KO-'
    '<KEfDjKJUt4;!wpv$}lpf^yTjw_%~u%BaK){JL#7Y$bWG=Wcq#jg<4fAapKbn^1EdMjpS+G5_KH2BzKMD#qh<hJ-'
    'D`f*3d*Z;NPjqq)SIdc0*}QxY8~dhdY6}$zLd?L~l`+5`L#P0Kcop)z+2gtrxntDG*TS3?h&H+fc=i_!)yIw*ZVShkeL-'
    'a@+S=G%t7M7oFMUL<W@Q8zN>Wh=zFe?;*13Hu(G{&`BN=F%sIV|EYsSWvXu=0rP%zP|90&pdV>nyYePlYHdo3+FSgxYw&ch2w~Zw8)A}x_tIc4q^'
    '<!%8_{ITuDw+-ub9^EtNO5w-b{0f(G}&T{APi=P>|>Af-Y=~FRZBZGc|t1wjZdetJ-OJq{(ZJZR6(EvEwH9Iv)idNDzpsxVC$}Jx)iMLuQ!@<EEk'
    '(b#*$Sj>o0~YS3}{NCmE_ELR8hcbCh6OJ0NHcKF~n{~#>N_(2NjiVx<~0L$t+<jCJg1(suAS41zQ#S!-'
    ')^~&H|VvYw!Q%;0Q*}BNlMk3abWqFHUsZ**iqMOj0S9gfsgZ*My6DTnWuR}wwW@)UYPtt(q{@GQzMrTYbTiVcS6)2XiHuG8!t6K$#fwwyOwNoD0B'
    'vKbIc8G$OxVJKOe5BDa_RanthV`#;r{Urh0Q~jG@S~ReiM}5Z(p4#p@;y---sU*Kv)z2>J<{tCSxPB_IFs*8e4hwE<GuG&@CN+{CNL+jG)g5NjB%'
    'k}G?=|kkk@2dhRAV=elEWDN<Or$PvhlCX;fb^A{;tcw$GUeXhM;(mVQ0Xhbz@lrR|gpE~>MxPflD-'
    'bG~&9s+-!{u-2AK+qtV!n1(zF-8G_5I*920r}+0K>HA(tnm!H~TvZZi0^~EOFwIrL7Oe8*58@bVVXxq&k~vKou-1`f8oTzgOGHCd-ZB)@<wyLrAz'
    'kvv&ybR6dwe6j3?SXM*J>UQr{wN4&W>>kd3e#oWh*l3#O#ti026$Ymo*y!Tn*d+bdNauhdGYoqpJnX6-'
    '%qZ^Xdh~uS<}*NgB$F#l1yoTfNS)LaJrI<RwjjO84mD7$$(%av0D7asEv=y3fiP9${h-'
    '=b^Mdkw|EREZ(Im9zJQK)%@%hli3%F<<`4u&apnjCI+e~HXztUNJb*qStz`R{4Bgsl6bObCHo%t%hUb5$DPYq_$S}eU}LyWN9q6gdhJtfQ1+rQLK'
    ';pL$N4xntJv4T)e~{H>8J6WdU=Lk%jfcR3b$fw(ys^Mh&7*D%cZ@*MhsJ=Y8-hVr=qm4X(h^d&Dm;;-'
    'Ko3LSV()TMD&*=71D?06!nX1Xq^k>@&?Zn+bJ3akc8e@L5noPZQMAUgS&6!p9!V*;t`czYg4I>B_L>iEO9eGw$VZ^Lc`@gelrZN0nraWEgX9NIe4'
    'duY_4AG9v*|@%!s5_3B9x6ccbT{x}W`@X`nT`f4Ni@+;j>b!%uwO-XsC)%mWJAh0W`9@nh28a_z+%m-'
    'Sg4zrONh1u7ES7#5MVQ#VdrV}ykQM<p>~?2WVOl4bHQ__w0cvT2jPlC{eiKp2i9a!=#^1uf-?g%n$U;f9ut)KxM{J1bMUQ?TmwF{--'
    'jVa1Zn?<tSh@p>Nep0{cwkR$7Wmy^6d2-'
    'H83<pR!dWLu|JdXAnCA<qTq3fT?Z83yYeF4u>L@rzfzQov9&%=vP2&AD4P{zRF!JUm<O(nH5Gw2m9ww7T%uwRdJz>v-'
    '8&NvkC6Y5y`l?&Ao!Ae;Xhnpz^-'
    'C#j>HC0mt><mWg6ldtG?I#C2MmDqC0N578RJrd~q6)U5@+ZvM(;|u3!crF2HMjs(Ndk;0|L<#EjI;3CUk^Sx|3c>XwN7#u|BJkIh`MJgv7wLGA-e'
    'G*cf`=>UOYUhIU($U)39j6EOl=;c{)}JvXYZMeb=7!E!8+|U=FoHW@_N~i%OIig0^0Vn4j0!(x%Ie}W7{Fs@%=!(LWj<$<9$?Mm*W;T)cNv>FFD#'
    'DhZ)FdyPVZQUcI(Tb^2lyQ5AWIYQ7RgxO1_ejv|N{d{(#JR}XN{U!r5_u;0jp+c?8FKWs*(31^9kTcg}m)E3oWi6xfOZGArV;c9fF60nFyZTB>aX'
    'fvIK<tkgKQLw^<iu|aNufVlB&(_3{D%%<q-'
    'sF)A&+a4vTob>#)ToM^oUAq8D$f}5UCK`v^jK=0E5{@IJ;6)<SKs{siH+X$V;BDmI)ZIQS~Gy~_K^bs5sy$*;==!M&P`G~xGD*)%L{44MZ@t(InN'
    '%^OjC?`94}N%+b7`WU-'
    '@G8?e;@a0>0>II!u#1F=}BQ07gri!gC4EvFH*EpXaME)LB}HSCae#Qv!qDq%b*<7l?#t&E&areSAbi6xwaT{CXH%r7t&EjQs=RPHM3xJDBAUkLg3'
    'gbB1MQb{d`pY_xHq(1eWj3Uz5DsgrY!UaHj6BEbfGHQ2MgyE=UcV&yXPt5Ggl_;-`J1$<{<PGn8x61-{QG>$^t#(@-'
    'iQj62!VYSl|yEvp!TUJEp`G|`Cb#!{E-$6LrA18=s1HYftJ=0ey_T7cFSyE#$me+p4fQ1j%l$|Yzh-'
    'l3FtII(c`8`I>KJ`V~tvfWzZp3(^3~T<q#ozw8aeab=+86tY@`L%ngMhC+@apR_hNlG9ViY`}y=FeY-eJ(?LKuTn@OjG^2i-'
    'WTFV+(`x)JE7@VLMI#7+kZx_yoxXbrKmDdQHYQHt$S=)gn;yC&hAkf?8zner`+r0#i(acVqV>|(KpZE{t}L}jT4Lz&n~qc5Gj>$F!2Sin0}L|s5o'
    'PxvO3%h_L(W|O!r%OAt)$!*4WMf&v;r-)%EdCCj$Feb@ke8dn{E5+-H`*st(K8`)=-'
    'zlu_+hn8&%B|IF{WUPUK0sgamoK4Hz+g!^d={aMdCyx};R293iM0Jg4F=SBOa?oH^TRmQfvQX7+g*w<d>Kiys&82jTuyQHF~urn_h?AYDt(aEE4r'
    'xB3>^q>SsJ~Yq>b@Oa0|RAg(~333B_7WC2*<4q)YHhxj%(R?lqqk)aM~<T0AC#r87yhUuQ!kuPPipCg9L}EAEpJWH$`cI3Z^7<(R;&AdNB3y1Nax'
    'Uy5hBC;N+-'
    'ct2VyEiGGaS%NU0RKitT24I2ZVvLi<%Za%nR={F<{N_O@`#HS*GY3e|=W$E=ov?fr{|2%(@Kc+|EktV)C~XN~p_3*fn)srRtajbfyd|;C;>jZIdW'
    '64GUfapvB1udVO<_kfQ%l0mD5YA`yLLJYN(5Z(k{X=!NcJoI+AP1xPjb`&*y_}GyA7zELC`*Nl1O209`5Jw-LJK59JEpFGz%R(fqh_l<jQZHs|de'
    'M&#B7KXb5mOe)V&2Qou{_1LR66p>HDS>lxmA=^CJPxpl?L>|z8Ds1w0`u68szpfOb{C&5Ncc!54=An8S?z+4YLcJ_VhTBL37413YF6AEIRXjO<G('
    ')KQB#E0WFrT-'
    '6GgQB^6qm+}x(K||+z*9)Y@3RE%k41%!s6to$O9I=JAo>%~xL>2cM{h$QGkT?h030Sbi;!<*|B?;mLifUr)l+*Axmi<I)6h1y6>BC070akjR$g7P'
    'F$un7?53FC>9irxBAsn;#9Ts{I~@ie>G$91XI%=%!5i*Ao?HPuARh`_lPqkM-'
    'l}~Gt8(eu^6T+O{`~`G2v9i7e}4}g_(U1DvVwk5asdJi`Rq8IR^-'
    'dXUT_q?;nUtuM=4bssj&VWVVgpc)s8IdoZo=ocRj^Y|6oo&TvvJtgf~cVlRjTU5=ZCSSuU)ao3r|b&sXMB&~esn;R{e1(G<dPBsZO^7bP^Ud_oSY'
    '_=L56rNQ414>MO$*`GAH$#)ZP$HTzNBSp1_Yz4jo1#p&v+a=C=ipK?g5TaowKLPg)!-**#qR6S(*p9O3d4zbbDO6M<KV}-'
    '=&yw;itf6}A?FLqERO-B*fw{>f-r#9cL`ItbcpWbldW@3-k<il-mPD90sLQ>FRz7mO>JvBB=q!|T;hb^cvVHe>#e@%05s~0^7=O<_O6cI1*E(~?U'
    '2oCxwZ+QWMFTm3Nz)}2kieoGkm+ia*-'
    '3EQq=Mb4(!7=Ljd;Jhky~I>wrxRV#)Td*;7~_aP8m_Xz<j4bK)RRzyhV%`5ILjPMRnBnLaoP#nIu(tXA_z>!g@OscApM?XG2|jnWVEx(wn54@kll'
    'aciTDDuVR>FjVc+M{B9E*JBzwyI^fzO_6>*5Tf|YX-'
    'qfp^wU08J=(io|R#mj`MC{Xq>dL))5{)k{-0~|o$SE<>grrfWIhGpR71{^98$g4f9$!mRfIK;wrPrNtqK&Zy+_`$padNhg{F{=C%~|!_w-Cbv|2r'
    'O>7b)+2(r>=#>i6>3<+RxdpWo(w!(VN0obbORJ8#}mVz;1)Ive<Y-TN4*qS0r(c9U=gm!tPPXgmdPBYru?3}Y^6AclDwAD<wK?}-'
    'm_8OGK94s(gCMDrBl)wo`A5O<dHCPnu@3;@|*$X4M+?{Lm)Xl)?8)~#g4jRKXK7$aP{mgwE27$I>d2`o~XE3Oru?XMMx7=ZQ_kyx&l0SMV)S87m>'
    'WYXpv4*vwH_GPWjB$%^;+biM4S#{z%Km|%daj~1cYHD~(W9kU)NzR7QUj;z<mgblnXvBRr?rM9H7V1-'
    'JPiNL9{WmD8O_Xg~X!5X1Z97$x=@g<!xd!RfsiR6#I>9Sas=>2ODQRKpwm5DJb>VPwuIzE>+i&pOZ}3yqhx)Yt*Q-'
    '0TIgaDoUHW<!dUYm2cG!32GC)m-T$UJ$?ju}WJJpd#d@e;(vWa=ye2j9^tQUG@6oBHWtgLmyviCUpvR;qlT(ocbcq#y><-?-xUiO!9Kdp-ZKz-nQ'
    '61<J<r&WOPmyoQ1_pja-'
    'c?%cK==XN=jGE5e36)|m=@h%(pW=Mtz_X~_T!)bHiJtF4%X<!)BSK6^K>|+8Oe;nBS_qthe^W=VK5GCb4$Ah01|mnbqM>x;&KFi+a-'
    'GaH`l)YFKLU*ist`+y${J*<Qd5;X4gA;OA6+msiCE{}3Z1kFtSZMe0xzZNbtNlEq4fWqe{W@iaG5Dx#tu$08|kN8?|i*Iimg#}wb&lac0tj7zX7?'
    'SU2<8kE&5L}@;jtINq)Wi`~+AZy=ybI(@#;{IJah2%)EE)TYX#|69znJh^}C0CvRFw7*1)p$1q@^>vLQsp3dIi3E&6cUau7&CCHFF&6VKx2i55Uw'
    'xNXhP?_wn+-jQYW)Q+Gx`?N^YhNd@1XrP?S+-Z7g712!X_=&e%n*Z;i-q5POEX2x9FppQK^|j{TtMvYE^GDA&y)mz2_8OF2Pc7Gqp1&7<>(9-'
    '!~~?ict5Tsz1{||lPKbd3n<WyC#fmS$t1R3o$cNM-bPV6)i6BnA`I$+`?0|tL2Pex9_vdSL$Spqxt}9K@Mw<$EQ0etq!;3{(>`$uwZm}WVsm+fgc'
    '#Iu4wled1(8O~bYQ!Jpvq#aSkrM}!hng&8nn7o2wmLP76oanSU3^}UTk_3=8BqA3sAq_k_QyNW*Jn-'
    'K^1wAxqz=Mp;PYYCCj<i)J%P<^Rg^0#&{0)4LuZHoKu@KhBD0W4&+CM_<#V)1{4$UKBw;HDIiAw#5V1?ICy2^N{MiG1HSXU{cE0|V+&|DN|KXBh9'
    'Ku+<OHAVB7x%mZz2Vy9KqKEV_z<Bget~~3c=&+-jFULycldMQr<&Zs-'
    'T=pUaG)DgwcZy`!;0abs*^5=r%2l;e*y?(D3$dD?yM!`Rc9|1?Su5hlj;ygjgap;Jt@C%v%US5BtOF*U#^A`ILMD_dk$C!}u!7Kj)z!AJ!Dg=b`~'
    'CAm@Ne16C~@qs$}%2m~)MDY>Us-x_6gh_B))5G`UWx#Epv8#}{$nR8;_JVSh<GY^GzQFGR;kditBna~ZJZQ!HYwkn&tlNq~8JBBT=kavBTn<P@%8'
    'UyEbND2#;sI*>Z%oY>1giK3JwIp&&qBhPFj2iXfwIQc&ahf31j{!(JPke-'
    '~k0npEfvi!TQtps0&giG(@;8EM9nDd1_w(^J)`+5}pz26Ei~zT*b+4|>S+n9CYuU26Acc}=P0r203TvEoI0LvJnL#MCFln?~%|7=;o~Z0mvrq}i='
    'O<<G0WD%LagW<;R-xqx&`Gs7&!v%!DXJEvlMx_q6p2;zmRTZw%6H+D_x=-'
    'C&`kijjbgfmB_#(^08H|7P`J6^%*>hXbEB#kd`Xda5t5T$<Zv08Y@y>@0>?BVekdG_)0FTY=ea1zNzsFKLe)D~iMY9G-'
    'GtDC6D!Ty`M^kFZ5G%yq=}70tfXlp%pT#<Et@)6&LYO~&;}(+k>h`22*sl&F9RQD?#%|7b9MGQpKeX`G3`<ItutkW*OM)MqdPrf%UrE%bT#;V8MF'
    'IU`X;rF@Cf-'
    '6F8ehr$(EDbK#AU>XB`W4K}eR5@~!mWEbWaTO>v$>>cYjk3+aat;DiMPw_Cr{+(M<_D8ixEG0C<#8BYVA``(0pYpq)XZrc(g2b^$Ik&XvSyd6w5t'
    'TN}z7i*9<7S=_!edz7O!y5_X?R;(B&~75%y+J^=ch^AwZ{YiWuI~{=JwnbPWG#%M9zK-aSGgEr^1-'
    'FsUdg?xx1h#1`lS8KrZR5_(m(a2Z|mICkJQPhLDb^pL%?x$@_F?3g4J}wmCfa*10uR$T8HO7J?Q!zOcxExRS`;49s<{n&+rN|&WX9B3KXu}3XCtQ'
    'y}`(+%~zV=x|<&aD%9RC{GM>{w+6`2?QI-'
    '}E@AwDUVEog=FL!n4Z(p;(6m5?1C23E?gR4RC0H_UHXvJBu9xBH6Q#c^fj07r_EaXW2p}abX_y!yq@&~xZnNfs?7Shcm<F4(7=DT3;0nZSj#=_@q'
    'fB)YRLo60fY?pco*@MEj9M#{dV8oefuz`@!=_Ps6*O&Slzt}c<nvu!(izCKMPE%JXpyCD>DHE!22tB!rZzvStfVlKPS`5-'
    'X*6A>=sGJ}#Ft4D>bz){yJlH#KOpQf%OaIpY6$4bp$wm@j9kxub8y}2R5nbXN?7^Wu&%~(6vc{t@*@-'
    'd_H4Md`7Fgkju%%d$mO>Qg}pWaUTc(57&9&74u?WUJ`Maf33rin1_sxTF@_Y+;55~^978sKs7#06s9ZoJPH9XL(9TTafT-Cy_ig~e5+2H#T`$S+$'
    '!Baq+aN-1sBK|STe=3{T42UK|Kl-'
    '`p=7f`1YDpPbuZEQN+|3D1m!*r7+#RP1=FZ!E~fM36Jcyi;`z9RMP5_jt+}PcO>?JIcEU8X1|7Ais7fOuwseZCVBWwEyDB$nw4iK>fOMH28)R%?g'
    '%&;6X+x!CU2>6^k&hCRg%^T2U&=+1UqxE-'
    'LO^X0U_t?!xfI@40aS7+3P~)#)^1|_x_*CMSFBX*`89u4#v)vlaE|>ZxiSoAKirIH6g8Bm{(P5uEf<qaA{{vnsd%<`lK{I@lDs1L5TyCy$LV3tQ-'
    'GEb{_7&=l^IcH9GG^giS!=y7;)afp%sI>21%O<T4lXl%+}S1zcb_y4A@eK!pgRe9}_hoA2_!^6!O0`W|SbO;Sk<WQy5C$8lpEAX(kTD^S4C5wMpr'
    '#YEO8lqpi7`##&SgaP?8eJ^!8B<ZY&UtFE%o79n!8%bG^6>k_IWaB`6AbU2~m`C)`ZlXDz8PigurG1)lGh~^yECfSZWLvy<Qr~waNFioGGn^W=O`'
    'DwolVh9bls8KeXZR!u(k5p~ZyL~2!FR3ORhQY+X77jBms@BONd{Kys^=*DhF8#54mJTVLeC5`3&J@>4qj;5OGvj2H;2aG_h8DLq;qMKR(T})R_a~'
    'G9_MgPO6v0&o6^2M>p^(|GMx0gz8_;Ve<OB~Q>SZ#KiKIrPO%koJg+RA5*;F}BXRA6BH${?=0JZkqK_JS-_DJ)+pYctJo(jnG`gkmS<-'
    'NOg+;q8~Qa5ZC+C%v@y*e!oSnN&!jNkiK_n4K`l36gh<W^8)7P<zt9%$0{%PWSIOV=TZ*e+)6?$EcScu{Jd3R?2k2s2PTld=HRzbyfx&!6WPxq<Q'
    '*6f+)=sivA?!1EzHdw+c+LHe%ZYYZZ+(s7_ejNGlj(9Ui(M5wcy8erU0&<4|W#Hw^~I+n=J)oXkw0@17zh}DtC{i~;rP~<!B8Hx?AOo%R7K3|Z&4'
    '&Lh9Ber|?jR1V{x4cunXl~UTL|~e>2wC(8>loefS&oHQbZ?~)AwX`Qj*$y|38A$S`N#v%3bv*qmOYV38NbT=r167+Kw9Kc$88-'
    'eEu1%TR>fEs(;C^akIZ!%Z%c^=>)ScR$Q}ksVw9QYqt15D)ec+z+)$1q@rYIqncCSUpFEwXt>p-'
    'B37+QZ+^H>HM^#n&`>0&p^96DS`S`wEj+c8Tln{namN*nG17g1Mod_56dUvg9Hz%#nX4k-5vU6DC^&2U-25;B*>>38u;y-'
    'Zvudcb73Qx}05put9eo_f06eUg*)VJVw?ScRM-~ayqwAhwg'
)
_RAW_PROVIDER_MEMBERS = json.loads(
    zlib.decompress(base64.b85decode("".join(_PROVIDER_MEMBERS_B85))).decode("utf-8")
)
PROVIDER_MEMBERS: dict[tuple[str, str], tuple[str, ...]] = {
    tuple(key.split("\0", 1)): tuple(value["names"])
    for key, value in _RAW_PROVIDER_MEMBERS.items()
}
PROVIDER_METHOD_ARITIES: dict[tuple[str, str], dict[str, int]] = {
    tuple(key.split("\0", 1)): dict(value["methods"])
    for key, value in _RAW_PROVIDER_MEMBERS.items()
}
del _PROVIDER_MEMBERS_B85, _RAW_PROVIDER_MEMBERS


__all__ = ["PROVIDER_MEMBERS", "PROVIDER_METHOD_ARITIES"]
