"""Compile HLSL compute shaders to .inc headers with fxc, replacing
DirectXTex's CompileShaders.cmd.

DirectXTex's BCDirectCompute.cpp #includes 14 generated headers: 7 entry points,
each compiled twice - once as cs_5_0 and once as cs_4_0 with /DEMULATE_F16C.
CMake produces them by shelling out to CompileShaders.cmd; that script is a .cmd
and Bazel has no shell on this machine, so the fxc calls are issued directly.

fxc.exe ships with the Windows SDK and is referenced by absolute path. That is
the one deliberately non-hermetic edge here: pinning it properly would need a
repository rule that discovers the installed SDK.
"""

_FXC_OPTS = [
    "/nologo",
    "/WX",
    "/Ges",
    "/Zi",
    "/Zpc",
    "/Qstrip_reflect",
    "/Qstrip_debug",
]

# (profile, output suffix, extra flags) - mirrors %fxc% and %fxc4% in the script.
_SHADER_VARIANTS = [
    ("cs_5_0", "", []),
    ("cs_4_0", "_cs40", ["/DEMULATE_F16C"]),
]

def _fxc_shader_headers_impl(ctx):
    outputs = []

    for src in ctx.files.srcs:
        base = src.basename[:-len(".hlsl")] if src.basename.endswith(".hlsl") else src.basename

        for entry in ctx.attr.entry_points:
            for profile, suffix, extra in _SHADER_VARIANTS:
                stem = "{}/{}_{}{}".format(ctx.attr.output_dir, base, entry, suffix)
                header = ctx.actions.declare_file(stem + ".inc")

                # /Zi makes fxc emit a PDB; it must be declared or Bazel treats
                # it as an undeclared output and the action fails.
                pdb = ctx.actions.declare_file(stem + ".pdb")

                args = ctx.actions.args()
                args.add(src.path)
                args.add_all(_FXC_OPTS)
                args.add("/T" + profile)
                args.add("/E" + entry)
                args.add_all(extra)
                args.add("/Fh" + header.path)
                args.add("/Fd" + pdb.path)
                # /Vn names the generated byte array; the C++ refers to it as
                # <file>_<entry> with no profile suffix, so both variants share
                # the same symbol name and only one .inc is included per build.
                args.add("/Vn{}_{}".format(base, entry))

                ctx.actions.run(
                    outputs = [header, pdb],
                    inputs = [src],
                    executable = ctx.attr.fxc_path,
                    arguments = [args],
                    mnemonic = "FxcCompile",
                    progress_message = "Compiling shader %s %s (%s)" % (base, entry, profile),
                    use_default_shell_env = True,
                )
                outputs.append(header)

    return [DefaultInfo(files = depset(outputs))]

fxc_shader_headers = rule(
    implementation = _fxc_shader_headers_impl,
    doc = "Run fxc over each src for every entry point, in both shader profiles.",
    attrs = {
        "srcs": attr.label_list(allow_files = [".hlsl"], mandatory = True),
        "entry_points": attr.string_list(mandatory = True),
        "output_dir": attr.string(default = "Compiled"),
        "fxc_path": attr.string(
            default = "C:/Program Files (x86)/Windows Kits/10/bin/10.0.26100.0/x64/fxc.exe",
            doc = "Absolute path to the Windows SDK shader compiler.",
        ),
    },
)
