"""Panel construction for the Model Library tab."""

from __future__ import annotations

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QAbstractItemView,
    QButtonGroup,
    QCheckBox,
    QComboBox,
    QFormLayout,
    QGridLayout,
    QGroupBox,
    QHeaderView,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QMenu,
    QPlainTextEdit,
    QProgressBar,
    QPushButton,
    QScrollArea,
    QSizePolicy,
    QSpinBox,
    QStackedWidget,
    QTreeWidget,
    QVBoxLayout,
    QWidget,
)

from cdmw.domain.library.models import DEFAULT_MODEL_MIRROR_URL
from cdmw.models import ModelPreviewRenderSettings, clamp_model_preview_render_settings
from cdmw.ui.model_library.settings import MODEL_LIBRARY_FILTER_COLUMNS
from cdmw.ui.preview import DotNetPreviewHostFrame, DotNetPreviewProfile


def build_controls_panel(tab: object) -> QWidget:
    panel = QWidget()
    panel.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Minimum)
    layout = QVBoxLayout(panel)
    layout.setContentsMargins(0, 0, 0, 0)
    layout.setSpacing(8)

    tab._updating_results_query = False
    local_group = QGroupBox("Local Folders")
    tab.local_group = local_group
    local_layout = QVBoxLayout(local_group)
    local_layout.setContentsMargins(8, 8, 8, 8)
    local_layout.setSpacing(6)
    path_row = QHBoxLayout()
    tab.local_path_edit = QLineEdit()
    tab.local_path_edit.setPlaceholderText("Folder containing local models")
    tab.browse_local_button = QPushButton("Browse")
    path_row.addWidget(tab.local_path_edit, stretch=1)
    path_row.addWidget(tab.browse_local_button)
    local_layout.addLayout(path_row)
    local_buttons = QGridLayout()
    tab.add_local_root_button = QPushButton("Add Folder")
    tab.remove_local_root_button = QPushButton("Remove")
    tab.scan_local_button = QPushButton("Show Local Models")
    tab.open_local_root_button = QPushButton("Open Folder")
    local_buttons.addWidget(tab.add_local_root_button, 0, 0)
    local_buttons.addWidget(tab.remove_local_root_button, 0, 1)
    local_buttons.addWidget(tab.scan_local_button, 1, 0)
    local_buttons.addWidget(tab.open_local_root_button, 1, 1)
    local_layout.addLayout(local_buttons)
    tab.roots_tree = QTreeWidget()
    tab.roots_tree.setColumnCount(1)
    tab.roots_tree.setHeaderLabels(["Folders"])
    tab.roots_tree.setRootIsDecorated(False)
    tab.roots_tree.setUniformRowHeights(True)
    tab.roots_tree.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
    tab.roots_tree.setMaximumHeight(120)
    local_layout.addWidget(tab.roots_tree)
    tab.roots_tree.currentItemChanged.connect(lambda _current, _previous: tab._update_selection_state())
    layout.addWidget(local_group)

    mirror_group = QGroupBox("Mirror Index Source")
    tab.mirror_group = mirror_group
    mirror_layout = QVBoxLayout(mirror_group)
    mirror_layout.setContentsMargins(8, 8, 8, 8)
    mirror_layout.setSpacing(6)
    mirror_form = QFormLayout()
    mirror_form.setContentsMargins(0, 0, 0, 0)
    mirror_form.setHorizontalSpacing(8)
    mirror_form.setVerticalSpacing(6)
    tab.mirror_url_edit = QLineEdit()
    tab.mirror_url_edit.setPlaceholderText(DEFAULT_MODEL_MIRROR_URL)
    mirror_form.addRow("Mirror URL", tab.mirror_url_edit)
    catalogue_dir_row = QHBoxLayout()
    tab.catalogue_dir_edit = QLineEdit()
    tab.catalogue_dir_edit.setPlaceholderText("Local catalogue folder")
    tab.browse_catalogue_dir_button = QPushButton("Browse")
    catalogue_dir_row.addWidget(tab.catalogue_dir_edit, stretch=1)
    catalogue_dir_row.addWidget(tab.browse_catalogue_dir_button)
    mirror_form.addRow("Catalogue", catalogue_dir_row)
    tab.max_shards_spin = QSpinBox()
    tab.max_shards_spin.setRange(0, 100_000)
    tab.max_shards_spin.setSpecialValueText("All")
    tab.max_shards_spin.setValue(int(tab.settings.value("model_library/max_shards", 1000) or 1000))
    tab.max_shards_spin.setKeyboardTracking(False)
    mirror_form.addRow("Index pages", tab.max_shards_spin)
    tab.result_limit_spin = QSpinBox()
    tab.result_limit_spin.setRange(1, 5000)
    tab.result_limit_spin.setValue(int(tab.settings.value("model_library/result_limit", 100) or 100))
    tab.result_limit_spin.setKeyboardTracking(False)
    mirror_form.addRow("Results", tab.result_limit_spin)
    preferred_files_layout = QGridLayout()
    preferred_files_layout.setContentsMargins(0, 0, 0, 0)
    preferred_files_layout.setHorizontalSpacing(8)
    preferred_files_layout.setVerticalSpacing(4)
    tab.preferred_format_checks: dict[str, QCheckBox] = {}
    preferred_file_options = (
        ("gltf", "glTF ZIP"),
        ("glb", "GLB"),
        ("source", "Original source ZIP (OBJ/FBX/etc.)"),
        ("extra", "Extra ZIP"),
    )
    selected_preferred_files = set(tab._settings_string_list("model_library/preferred_formats_json", default=("gltf",)))
    if not selected_preferred_files:
        selected_preferred_files = {"gltf"}
    for option_index, (format_key, label) in enumerate(preferred_file_options):
        checkbox = QCheckBox(label)
        checkbox.setChecked(format_key in selected_preferred_files)
        checkbox.toggled.connect(lambda _checked=False: tab._save_preferred_format_settings())
        tab.preferred_format_checks[format_key] = checkbox
        preferred_files_layout.addWidget(checkbox, option_index // 2, option_index % 2)
    mirror_form.addRow("Preferred files", preferred_files_layout)
    mirror_layout.addLayout(mirror_form)
    build_buttons = QGridLayout()
    tab.build_index_button = QPushButton("Build Search Index")
    tab.cancel_task_button = QPushButton("Cancel")
    tab.cancel_task_button.setEnabled(False)
    build_buttons.addWidget(tab.build_index_button, 0, 0)
    build_buttons.addWidget(tab.cancel_task_button, 0, 1)
    mirror_layout.addLayout(build_buttons)
    tab.index_current_search_checkbox = QCheckBox("Build index from current search/filter only")
    tab.index_current_search_checkbox.setChecked(bool(tab.settings.value("model_library/index_current_search", False, type=bool)))
    tab.index_current_search_checkbox.setToolTip(
        "Rebuilds the local metadata database with only records matching the Search, License, Creator, Exclude creators, and Format fields. "
        "Catalogue pages still need to be read, but cached shard files are reused."
    )
    mirror_layout.addWidget(tab.index_current_search_checkbox)
    tab.task_status_label = QLabel("Mirror catalogue is idle.")
    tab.task_status_label.setObjectName("HintLabel")
    tab.task_status_label.setWordWrap(True)
    mirror_layout.addWidget(tab.task_status_label)
    tab.search_edit = QLineEdit()
    tab.search_edit.setPlaceholderText("Search by name, tag, creator, or UID")
    tab.search_edit.setText(str(tab.settings.value("model_library/search_query", "sword") or "sword"))
    filter_form = QFormLayout()
    filter_form.setContentsMargins(0, 0, 0, 0)
    filter_form.setHorizontalSpacing(8)
    filter_form.setVerticalSpacing(6)
    tab.license_filter_edit = QLineEdit()
    tab.license_filter_edit.setPlaceholderText("CC0, Attribution, NonCommercial")
    tab.creator_filter_edit = QLineEdit()
    tab.creator_filter_edit.setPlaceholderText("Creator name")
    tab.creator_exclude_edit = QLineEdit()
    tab.creator_exclude_edit.setPlaceholderText("Creator names/usernames, comma separated")
    tab.format_filter_combo = QComboBox()
    tab.format_filter_combo.addItem("Any format", "")
    tab.format_filter_combo.addItem("glTF ZIP", "gltf")
    tab.format_filter_combo.addItem("GLB", "glb")
    tab.format_filter_combo.addItem("Original source", "source")
    filter_form.addRow("License", tab.license_filter_edit)
    filter_form.addRow("Creator", tab.creator_filter_edit)
    filter_form.addRow("Exclude creators", tab.creator_exclude_edit)
    filter_form.addRow("Format", tab.format_filter_combo)
    mirror_layout.addLayout(filter_form)
    tab.hide_downloaded_checkbox = QCheckBox("Hide downloaded")
    tab.hide_downloaded_checkbox.setChecked(bool(tab.settings.value("model_library/hide_downloaded", False, type=bool)))
    mirror_layout.addWidget(tab.hide_downloaded_checkbox)
    search_buttons = QGridLayout()
    tab.search_mirror_button = QPushButton("Search Mirror")
    tab.show_indexed_button = QPushButton("Popular")
    search_buttons.addWidget(tab.search_mirror_button, 0, 0)
    search_buttons.addWidget(tab.show_indexed_button, 0, 1)
    mirror_layout.addLayout(search_buttons)
    tab.catalogue_status_label = QLabel("")
    tab.catalogue_status_label.setObjectName("HintLabel")
    tab.catalogue_status_label.setWordWrap(True)
    mirror_layout.addWidget(tab.catalogue_status_label)
    layout.addWidget(mirror_group)

    actions_group = QGroupBox("Actions")
    actions_layout = QGridLayout(actions_group)
    actions_layout.setContentsMargins(8, 8, 8, 8)
    actions_layout.setSpacing(6)
    tab.preview_button = QPushButton("Preview")
    tab.import_mesh_button = QPushButton("Import Mesh")
    tab.import_mesh_button.setToolTip("Replaces the mesh currently selected in Archive Browser.")
    tab.download_button = QPushButton("Download Checked")
    tab.generate_icon_button = QPushButton("Generate Icon")
    tab.more_actions_button = QPushButton("More Actions")
    tab.more_actions_menu = QMenu(tab.more_actions_button)
    tab.download_import_button = tab.more_actions_menu.addAction("Download + Import")
    tab.delete_local_button = tab.more_actions_menu.addAction("Delete Local")
    tab.delete_no_texture_downloads_button = tab.more_actions_menu.addAction("Delete No-Texture Downloads")
    tab.open_file_url_button = tab.more_actions_menu.addAction("Open File URL")
    tab.open_location_button = tab.more_actions_menu.addAction("Open Location")
    tab.open_page_button = tab.more_actions_menu.addAction("Open Page")
    tab.more_actions_button.setMenu(tab.more_actions_menu)
    actions_layout.addWidget(tab.preview_button, 0, 0)
    actions_layout.addWidget(tab.import_mesh_button, 0, 1)
    actions_layout.addWidget(tab.download_button, 1, 0)
    actions_layout.addWidget(tab.generate_icon_button, 1, 1)
    actions_layout.addWidget(tab.more_actions_button, 2, 0, 1, 2)
    tab.auto_preview_checkbox = QCheckBox("Auto preview local selection")
    tab.auto_preview_checkbox.setToolTip(
        "Automatically previews local selections in the Model Library preview panel."
    )
    tab.auto_preview_checkbox.setChecked(bool(tab.settings.value("model_library/auto_preview", True, type=bool)))
    actions_layout.addWidget(tab.auto_preview_checkbox, 3, 0, 1, 2)
    layout.addWidget(actions_group)

    selection_group = QGroupBox("Selection")
    selection_group.setObjectName("ModelLibrarySelectionGroup")
    selection_group.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    selection_layout = QVBoxLayout(selection_group)
    selection_layout.setContentsMargins(8, 8, 8, 8)
    selection_layout.setSpacing(6)
    tab.details_edit = QLineEdit()
    tab.details_edit.setReadOnly(True)
    tab.details_edit.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
    selection_layout.addWidget(tab.details_edit)
    tab.details_text = QPlainTextEdit()
    tab.details_text.setObjectName("ModelLibraryDetailsText")
    tab.details_text.setReadOnly(True)
    tab.details_text.setLineWrapMode(QPlainTextEdit.LineWrapMode.WidgetWidth)
    tab.details_text.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
    tab.details_text.setMinimumHeight(180)
    tab.details_text.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    selection_layout.addWidget(tab.details_text, stretch=1)
    layout.addWidget(selection_group, stretch=1)

    tab.browse_local_button.clicked.connect(tab.browse_local_folder)
    tab.add_local_root_button.clicked.connect(tab.add_local_root)
    tab.remove_local_root_button.clicked.connect(tab.remove_selected_local_root)
    tab.scan_local_button.clicked.connect(tab.scan_local_roots)
    tab.open_local_root_button.clicked.connect(tab.open_selected_local_root)
    tab.browse_catalogue_dir_button.clicked.connect(tab.browse_catalogue_dir)
    tab.build_index_button.clicked.connect(tab.build_mirror_index)
    tab.cancel_task_button.clicked.connect(tab.cancel_current_task)
    tab.search_mirror_button.clicked.connect(tab.search_mirror)
    tab.show_indexed_button.clicked.connect(lambda _checked=False: tab.search_mirror(query_override=""))
    tab.search_edit.returnPressed.connect(tab._apply_active_results_query)
    tab.search_edit.textChanged.connect(tab._handle_results_query_changed)
    tab.hide_downloaded_checkbox.toggled.connect(tab._handle_hide_downloaded_toggled)
    tab.index_current_search_checkbox.toggled.connect(
        lambda value: tab.settings.setValue("model_library/index_current_search", bool(value))
    )
    tab.max_shards_spin.valueChanged.connect(lambda value: tab.settings.setValue("model_library/max_shards", value))
    tab.result_limit_spin.valueChanged.connect(lambda value: tab.settings.setValue("model_library/result_limit", value))
    tab.mirror_url_edit.editingFinished.connect(tab._save_mirror_settings)
    tab.mirror_url_edit.textChanged.connect(lambda _value: tab._update_selection_state())
    tab.catalogue_dir_edit.editingFinished.connect(tab._save_mirror_settings)
    tab.preview_button.clicked.connect(tab.preview_selected_model_here)
    tab.auto_preview_checkbox.toggled.connect(tab._handle_auto_preview_toggled)
    tab.import_mesh_button.clicked.connect(tab.import_selected_model)
    tab.download_button.clicked.connect(lambda _checked=False: tab.download_selected_models())
    tab.download_import_button.triggered.connect(lambda _checked=False: tab.download_selected_model(import_after=True))
    tab.generate_icon_button.clicked.connect(tab.generate_icon_from_preview)
    tab.open_file_url_button.triggered.connect(tab.open_selected_file_url)
    tab.open_location_button.triggered.connect(tab.open_selected_location)
    tab.open_page_button.triggered.connect(tab.open_selected_page)
    tab.delete_local_button.triggered.connect(tab.delete_selected_local_models)
    tab.delete_no_texture_downloads_button.triggered.connect(tab.delete_no_texture_downloads)

    scroll = QScrollArea()
    scroll.setObjectName("ModelLibraryControlsScroll")
    scroll.setWidgetResizable(True)
    scroll.setFrameShape(QScrollArea.Shape.NoFrame)
    scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
    scroll.setWidget(panel)
    return scroll


def build_results_panel(tab: object) -> QWidget:
    panel = QWidget()
    layout = QVBoxLayout(panel)
    layout.setContentsMargins(0, 0, 0, 0)
    layout.setSpacing(6)
    view_row = QHBoxLayout()
    view_row.setContentsMargins(0, 0, 0, 0)
    view_row.setSpacing(6)
    tab.mirror_results_view_button = QPushButton("Mirror Catalogue")
    tab.local_results_view_button = QPushButton("Local Library")
    tab.refresh_results_view_button = QPushButton("Refresh")
    tab.mirror_results_view_button.setCheckable(True)
    tab.local_results_view_button.setCheckable(True)
    for button in (tab.mirror_results_view_button, tab.local_results_view_button):
        button.setMinimumWidth(button.sizeHint().width() + 12)
        button.setSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
    tab.results_view_button_group = QButtonGroup(tab)
    tab.results_view_button_group.setExclusive(True)
    tab.results_view_button_group.addButton(tab.mirror_results_view_button)
    tab.results_view_button_group.addButton(tab.local_results_view_button)
    view_row.addWidget(tab.mirror_results_view_button)
    view_row.addWidget(tab.local_results_view_button)
    view_row.addWidget(tab.refresh_results_view_button)
    view_row.addStretch(1)
    layout.addLayout(view_row)
    filter_layout = QVBoxLayout()
    filter_layout.setContentsMargins(0, 0, 0, 0)
    filter_layout.setSpacing(4)
    filter_options_row = QHBoxLayout()
    filter_options_row.setContentsMargins(0, 0, 0, 0)
    filter_options_row.setSpacing(6)
    tab.results_search_label = QLabel("Mirror search")
    tab.results_filter_field_combo = QComboBox()
    tab.results_filter_field_combo.addItem("All fields", "all")
    tab.results_filter_field_combo.addItem("Name", "name")
    tab.results_filter_field_combo.addItem("Creator", "creator")
    tab.results_filter_field_combo.addItem("License", "license")
    tab.results_filter_field_combo.addItem("Format", "format")
    tab.results_filter_field_combo.addItem("Path / URL", "path")
    tab.results_filter_field_combo.addItem("UID", "uid")
    tab.local_texture_filter_label = QLabel("Textures")
    tab.local_texture_filter_combo = QComboBox()
    tab.local_texture_filter_combo.addItem("All", "all")
    tab.local_texture_filter_combo.addItem("Has textures", "has")
    tab.local_texture_filter_combo.addItem("No textures found", "missing")
    tab.apply_results_query_button = QPushButton("Search")
    tab.clear_results_query_button = QPushButton("Clear")
    filter_options_row.addWidget(tab.results_search_label)
    filter_options_row.addWidget(tab.results_filter_field_combo)
    filter_options_row.addWidget(tab.local_texture_filter_label)
    filter_options_row.addWidget(tab.local_texture_filter_combo)
    filter_options_row.addStretch(1)
    filter_layout.addLayout(filter_options_row)
    filter_search_row = QHBoxLayout()
    filter_search_row.setContentsMargins(0, 0, 0, 0)
    filter_search_row.setSpacing(6)
    filter_search_row.addWidget(tab.search_edit, stretch=1)
    filter_search_row.addWidget(tab.apply_results_query_button)
    filter_search_row.addWidget(tab.clear_results_query_button)
    filter_layout.addLayout(filter_search_row)
    layout.addLayout(filter_layout)
    column_filter_row = QHBoxLayout()
    column_filter_row.setContentsMargins(0, 0, 0, 0)
    column_filter_row.setSpacing(4)
    tab.results_column_filter_edits: dict[int, QLineEdit] = {}
    column_filter_row.addWidget(QLabel("Columns"))
    for column, label in MODEL_LIBRARY_FILTER_COLUMNS:
        edit = QLineEdit()
        edit.setPlaceholderText(label)
        edit.setClearButtonEnabled(True)
        edit.setMinimumWidth(70)
        edit.setMaximumWidth(160 if column in {1, 7, 8, 9} else 110)
        tab.results_column_filter_edits[column] = edit
        column_filter_row.addWidget(edit, stretch=1 if column in {1, 9} else 0)
    column_filter_panel = QWidget()
    column_filter_panel.setLayout(column_filter_row)
    column_filter_scroll = QScrollArea()
    column_filter_scroll.setWidgetResizable(False)
    column_filter_scroll.setFrameShape(QScrollArea.Shape.NoFrame)
    column_filter_scroll.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
    column_filter_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
    column_filter_scroll.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
    column_filter_scroll.setMinimumHeight(34)
    column_filter_scroll.setWidget(column_filter_panel)
    layout.addWidget(column_filter_scroll)
    tab.results_view_label = QLabel("")
    tab.results_view_label.setObjectName("HintLabel")
    tab.results_view_label.setWordWrap(True)
    layout.addWidget(tab.results_view_label)
    tab.empty_results_label = QLabel("")
    tab.empty_results_label.setObjectName("HintLabel")
    tab.empty_results_label.setWordWrap(True)
    tab.empty_results_label.setVisible(False)
    layout.addWidget(tab.empty_results_label)
    tab.active_task_label = QLabel("")
    tab.active_task_label.setObjectName("HintLabel")
    tab.active_task_label.setWordWrap(True)
    tab.active_task_label.setVisible(False)
    layout.addWidget(tab.active_task_label)
    tab.active_task_progress = QProgressBar()
    tab.active_task_progress.setRange(0, 0)
    tab.active_task_progress.setTextVisible(True)
    tab.active_task_progress.setFormat("Working...")
    tab.active_task_progress.setVisible(False)
    layout.addWidget(tab.active_task_progress)
    tab.results_tree = QTreeWidget()
    tab.results_tree.setColumnCount(10)
    tab.results_tree.setHeaderLabels(["", "Name", "Source", "Local", "Textures", "Format", "Size", "License", "Creator", "Location"])
    tab.results_tree.setRootIsDecorated(False)
    tab.results_tree.setAlternatingRowColors(True)
    tab.results_tree.setUniformRowHeights(True)
    tab.results_tree.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
    tab.results_tree.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
    tab.results_tree.setSortingEnabled(False)
    tab.results_tree.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
    tab.results_tree.setHorizontalScrollMode(QAbstractItemView.ScrollMode.ScrollPerPixel)
    tab.results_tree.header().setStretchLastSection(False)
    tab.results_tree.header().setSectionsClickable(True)
    tab.results_tree.header().setSortIndicatorShown(True)
    tab.results_tree.header().setSortIndicator(tab._result_sort_column, tab._result_sort_order)
    tab.results_tree.header().setMinimumSectionSize(34)
    tab.results_tree.header().setSectionResizeMode(QHeaderView.ResizeMode.Interactive)
    tab.results_tree.header().setSectionResizeMode(0, QHeaderView.ResizeMode.Fixed)
    tab.results_tree.header().resizeSection(0, 34)
    tab.results_tree.header().resizeSection(1, 260)
    tab.results_tree.header().resizeSection(2, 95)
    tab.results_tree.header().resizeSection(3, 110)
    tab.results_tree.header().resizeSection(4, 105)
    tab.results_tree.header().resizeSection(5, 90)
    tab.results_tree.header().resizeSection(6, 90)
    tab.results_tree.header().resizeSection(7, 150)
    tab.results_tree.header().resizeSection(8, 150)
    tab.results_tree.header().resizeSection(9, 280)
    layout.addWidget(tab.results_tree, stretch=1)
    selection_row = QHBoxLayout()
    selection_row.setContentsMargins(0, 0, 0, 0)
    selection_row.setSpacing(6)
    tab.select_all_button = QPushButton("Select All")
    tab.select_none_button = QPushButton("Select None")
    selection_row.addWidget(tab.select_all_button)
    selection_row.addWidget(tab.select_none_button)
    selection_row.addStretch(1)
    layout.addLayout(selection_row)
    tab.results_status_label = QLabel("")
    tab.results_status_label.setObjectName("HintLabel")
    tab.results_status_label.setWordWrap(True)
    layout.addWidget(tab.results_status_label)
    tab.results_tree.currentItemChanged.connect(tab._handle_results_current_item_changed)
    tab.results_tree.itemChanged.connect(tab._handle_result_item_changed)
    tab.results_tree.itemDoubleClicked.connect(lambda _item, _column: tab.import_selected_model())
    tab.results_tree.customContextMenuRequested.connect(tab._show_results_context_menu)
    tab.results_tree.header().sectionClicked.connect(tab._handle_results_header_clicked)
    tab.select_all_button.clicked.connect(lambda _checked=False: tab._set_all_result_checks(True))
    tab.select_none_button.clicked.connect(lambda _checked=False: tab._set_all_result_checks(False))
    tab.mirror_results_view_button.clicked.connect(lambda _checked=False: tab.show_mirror_catalogue_view())
    tab.local_results_view_button.clicked.connect(lambda _checked=False: tab.show_local_library_view())
    tab.refresh_results_view_button.clicked.connect(lambda _checked=False: tab.refresh_active_results_view())
    tab.apply_results_query_button.clicked.connect(tab._apply_active_results_query)
    tab.clear_results_query_button.clicked.connect(tab._clear_active_results_query)
    tab.results_filter_field_combo.currentIndexChanged.connect(lambda _index=0: tab._handle_results_filter_field_changed())
    tab.local_texture_filter_combo.currentIndexChanged.connect(lambda _index=0: tab._handle_local_texture_filter_changed())
    for edit in tab.results_column_filter_edits.values():
        edit.textChanged.connect(lambda _text="", editor=edit: tab._handle_column_filter_changed(editor))
    return panel


def build_preview_panel(tab: object) -> QWidget:
    panel = QWidget()
    layout = QVBoxLayout(panel)
    layout.setContentsMargins(0, 0, 0, 0)
    layout.setSpacing(6)
    preview_group = QGroupBox("Model Preview")
    preview_layout = QVBoxLayout(preview_group)
    preview_layout.setContentsMargins(8, 8, 8, 8)
    preview_layout.setSpacing(6)
    # The inline preview is drawn by the resident .NET/Vortice host, so these are
    # preparation settings only: no preview widget owns them.
    inline_render_settings = ModelPreviewRenderSettings()
    inline_render_settings.visible_texture_mode = "sidecar_visible_first"
    inline_render_settings.render_diagnostic_mode = "base_direct"
    inline_render_settings.disable_tint = True
    inline_render_settings.disable_brightness = True
    inline_render_settings.disable_all_support_maps = True
    inline_render_settings.disable_normal_map = True
    inline_render_settings.disable_material_map = True
    inline_render_settings.disable_height_map = True
    inline_render_settings.low_quality_texture_max_dimension = 1024
    inline_render_settings.use_textures_by_default = True
    inline_render_settings.high_quality_by_default = True
    tab.inline_preview_render_settings = clamp_model_preview_render_settings(inline_render_settings)
    tab.inline_preview_stack = QStackedWidget()
    tab.inline_d3d11_preview_host = DotNetPreviewHostFrame(
        profile=DotNetPreviewProfile.PREVIEW,
    )
    tab.inline_d3d11_preview_host.setMinimumHeight(280)
    tab.inline_preview_stack.addWidget(tab.inline_d3d11_preview_host)
    tab.inline_preview_stack.setCurrentWidget(tab.inline_d3d11_preview_host)
    preview_layout.addWidget(tab.inline_preview_stack, stretch=1)
    orientation_controls_layout = QHBoxLayout()
    orientation_controls_layout.setContentsMargins(0, 0, 0, 0)
    orientation_controls_layout.setSpacing(8)
    tab.inline_preview_flip_v_checkbox = QCheckBox("Flip V")
    tab.inline_preview_flip_v_checkbox.setToolTip(
        "Temporarily invert the texture V direction for the current Model Library preview only."
    )
    tab.inline_preview_reset_orientation_button = QPushButton("Reset")
    tab.inline_preview_reset_orientation_button.setToolTip("Clear temporary Model Library texture orientation overrides.")
    tab.inline_preview_flip_v_checkbox.setEnabled(False)
    tab.inline_preview_reset_orientation_button.setEnabled(False)
    orientation_controls_layout.addWidget(tab.inline_preview_flip_v_checkbox)
    orientation_controls_layout.addWidget(tab.inline_preview_reset_orientation_button)
    orientation_controls_layout.addStretch(1)
    preview_layout.addLayout(orientation_controls_layout)
    tab.inline_preview_status_label = QLabel(
        "Local preview resolves glTF/GLB/OBJ/DAE textures into the shared .NET/Vortice renderer."
    )
    tab.inline_preview_status_label.setObjectName("HintLabel")
    tab.inline_preview_status_label.setWordWrap(False)
    tab.inline_preview_status_label.setMinimumHeight(24)
    tab.inline_preview_status_label.setMaximumHeight(32)
    tab.inline_preview_status_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
    preview_layout.addWidget(tab.inline_preview_status_label)
    tab.inline_preview_flip_v_checkbox.toggled.connect(tab._handle_inline_preview_flip_v_toggled)
    tab.inline_preview_reset_orientation_button.clicked.connect(tab._handle_inline_preview_orientation_reset_clicked)
    tab.inline_d3d11_preview_host.controller.state_changed.connect(tab._handle_inline_dotnet_state)
    tab.inline_d3d11_preview_host.controller.capture_completed.connect(tab._handle_inline_dotnet_capture_completed)
    layout.addWidget(preview_group, stretch=1)
    tab.status_label = QLabel("")
    tab.status_label.setObjectName("HintLabel")
    tab.status_label.setWordWrap(True)
    tab.status_label.setVisible(False)
    layout.addWidget(tab.status_label)
    return panel


__all__ = ["build_controls_panel", "build_preview_panel", "build_results_panel"]
